import { Container,Graphics,Text } from 'pixi.js';
import { Locale } from '../../i18n';
import { color,layout,radius,type } from './tokens';

const style=(locale:Locale,size:number,fill:number=color.ink,weight='600')=>({fontFamily:'Georgia, "Noto Serif TC", serif',fontSize:size,fill,fontWeight:weight as any,letterSpacing:locale==='zh-TW'?1:2});
export function uiText(parent:Container,locale:Locale,value:string,x:number,y:number,size:number=type.body,fill:number=color.ink,weight='600'){const t=new Text({text:value,style:style(locale,size,fill,weight)});t.position.set(x,y);parent.addChild(t);return t;}
export function surface(parent:Container,x:number,y:number,w:number,h:number,raised=true){const g=new Graphics().roundRect(x,y,w,h,radius.md).fill(raised?color.paperRaised:color.paper).stroke({color:color.edge,width:1});parent.addChild(g);return g;}
export function actionButton(parent:Container,locale:Locale,x:number,y:number,w:number,h:number,value:string,onTap?:()=>void,active=false){const g=new Graphics().roundRect(x,y,w,Math.max(h,layout.touchMin),radius.md).fill(active?color.panel:color.paperRaised).stroke({color:active?color.gold:color.edge,width:1});g.eventMode='static';g.cursor='pointer';if(onTap)g.on('pointertap',onTap);parent.addChild(g);const t=uiText(parent,locale,value,0,0,type.label,active?color.parchment:color.ink,'700');t.anchor.set(.5);t.position.set(x+w/2,y+Math.max(h,layout.touchMin)/2);return g;}
export function pageHeader(parent:Container,locale:Locale,title:string,onBack?:()=>void){if(onBack){const hit=new Graphics().rect(10,12,layout.touchMin,layout.touchMin).fill({color:color.paper,alpha:.001});hit.eventMode='static';hit.cursor='pointer';hit.on('pointertap',onBack);parent.addChild(hit);const back=uiText(parent,locale,'‹',22,9,34);back.eventMode='none';}const t=uiText(parent,locale,title,0,22,type.title,color.ink,'700');t.anchor.set(.5,0);t.x=195;return t;}
export type NavItem<T extends string>={id:T;label:string};
function navIcon(id:string,cx:number,y:number,fill:number){const g=new Graphics();if(id==='home'){g.moveTo(cx,y).lineTo(cx+10,y+10).lineTo(cx,y+20).lineTo(cx-10,y+10).closePath().stroke({color:fill,width:2});g.circle(cx,y+10,2).fill(fill);}else if(id==='history'){g.roundRect(cx-9,y+1,18,18,2).stroke({color:fill,width:2});g.moveTo(cx-5,y+6).lineTo(cx+5,y+6).moveTo(cx-5,y+10).lineTo(cx+5,y+10).moveTo(cx-5,y+14).lineTo(cx+2,y+14).stroke({color:fill,width:1.5});}else if(id==='stats'){g.rect(cx-9,y+11,4,8).rect(cx-2,y+6,4,13).rect(cx+5,y+1,4,18).fill(fill);}else{g.moveTo(cx-9,y+5).lineTo(cx+9,y+5).moveTo(cx-9,y+15).lineTo(cx+9,y+15).stroke({color:fill,width:2});g.circle(cx-3,y+5,3).fill(color.panel).stroke({color:fill,width:2});g.circle(cx+4,y+15,3).fill(color.panel).stroke({color:fill,width:2});}return g;}
export function bottomNav<T extends string>(parent:Container,locale:Locale,current:T,items:readonly NavItem<T>[],onNavigate:(id:T)=>void){const nav=new Container(),w=390,h=layout.bottomNavHeight,y=844-h,itemW=w/items.length;nav.position.set(0,y);nav.addChild(new Graphics().rect(0,0,w,h).fill(color.panel));nav.addChild(new Graphics().moveTo(0,0).lineTo(w,0).stroke({color:color.goldSoft,width:1,alpha:.75}));items.forEach((item,i)=>{const left=i*itemW,cx=left+itemW/2,active=item.id===current,hit=new Graphics().rect(left,0,itemW,h).fill({color:color.panel,alpha:.001});hit.eventMode='static';hit.cursor='pointer';hit.on('pointertap',()=>onNavigate(item.id));nav.addChild(hit);if(active){nav.addChild(new Graphics().roundRect(cx-18,5,36,3,2).fill(color.gold));nav.addChild(new Graphics().roundRect(left+10,9,itemW-20,h-14,radius.md).fill({color:color.paper,alpha:.055}));}nav.addChild(navIcon(item.id,cx,active?19:21,active?color.parchment:color.goldSoft));const label=uiText(nav,locale,item.label,0,50,type.caption,active?color.parchment:color.goldSoft,active?'700':'600');label.anchor.set(.5,0);label.x=cx;});parent.addChild(nav);}
