import{Application,Container,Graphics,Text,TextStyle}from'pixi.js';
import{WEAPONS,weaponAt,type WeaponDefinition}from'./content/weapons';
import{TOWERS,towerAt}from'./content/towers';
import{ENEMIES,waveComposition,waveLabel,type EnemyRole}from'./content/enemies';
import{createInitialGameState,type Facing,type TowerType}from'./domain/models';
import{KeyboardInput}from'./input/KeyboardInput';
import{COLORS as C}from'./presentation/theme';

const app=new Application();await app.init({background:'#05070b',resizeTo:window,antialias:false});document.querySelector('#app')!.appendChild(app.canvas);
const world=new Container(),bg=new Graphics(),actors=new Container(),fx=new Container(),hud=new Container();world.addChild(bg,actors);app.stage.addChild(world,fx,hud);
const state=createInitialGameState();const floor=()=>app.renderer.height*.78,coreX=()=>app.renderer.width*.88;state.playerX=app.renderer.width*.55;state.playerY=floor();
type Phase='move'|'windup'|'recover';
interface Enemy{g:Graphics;role:EnemyRole;x:number;y:number;hp:number;maxHp:number;speed:number;elite:boolean;flying:boolean;phase:Phase;timer:number;knock:number;disabled:number;flash:number;}
interface Tower{g:Graphics;type:TowerType;x:number;y:number;hp:number;maxHp:number;cool:number;disabled:number;mineReady:boolean;}
interface Bullet{g:Graphics;x:number;y:number;px:number;py:number;vx:number;vy:number;damage:number;knock:number;pierce:number;energy:boolean;hit:Set<Enemy>;}
const enemies:Enemy[]=[],towers:Tower[]=[],bullets:Bullet[]=[];let queue:{role:EnemyRole;elite:boolean}[]=[];let wavePreview=waveLabel(1),repairTick=0;
const player=new Graphics();actors.addChild(player);
const pads=()=>[.18,.31,.44,.57,.70,.79].map(r=>app.renderer.width*r).filter(x=>x<coreX()-75);
function msg(s:string,color=C.cyan){const t=new Text({text:s,style:new TextStyle({fill:color,fontSize:13,fontWeight:'900',letterSpacing:1})});t.anchor.set(.5);t.position.set(app.renderer.width/2,88);fx.addChild(t);let life=1.3;const f=()=>{life-=app.ticker.deltaMS/1000;t.alpha=Math.max(0,life/.35);if(life<=0){t.destroy();app.ticker.remove(f)}};app.ticker.add(f)}
function burst(x:number,y:number,color=C.pink){for(let i=0;i<5;i++){const g=new Graphics().circle(0,0,2).fill(color);g.position.set(x+(Math.random()-.5)*20,y+(Math.random()-.5)*20);fx.addChild(g);setTimeout(()=>g.destroy(),100)}}
function drawWorld(){const w=app.renderer.width,h=app.renderer.height,y=floor();bg.clear().rect(0,0,w,h).fill(C.bg).rect(0,0,w,y).fill(0x07171d).rect(0,y,w,h-y).fill(0x0a0d12).rect(0,y-3,w,3).fill({color:C.cyan,alpha:.45});for(let i=0;i<10;i++){const x=i*w/9-30,bh=90+(i*53)%150;bg.rect(x,y-bh-80,90+(i*31)%80,bh).fill(i%2?0x0a151c:0x0d1920)}pads().forEach(x=>bg.poly([x-34,y,x+34,y,x+26,y-9,x-26,y-9]).fill(towers.some(t=>Math.abs(t.x-x)<12)?0x20262c:0x121a20).stroke({color:C.cyanDim,width:1}));bg.poly([coreX()-48,y,coreX()-38,y-120,coreX()+38,y-120,coreX()+48,y]).fill(0x182029).stroke({color:state.coreHp<35?C.red:C.cyan,width:4}).circle(coreX(),y-64,24).stroke({color:C.amber,width:5});drawPlayer()}
function drawPlayer(){const x=state.playerX,y=state.playerY,d=state.facing;player.clear().poly([x-15,y-62,x+13,y-62,x+20,y-12,x-18,y-12]).fill(0x26313a).rect(x-16,y-52,30,18).fill(C.pink).circle(x,y-70,12).fill(0xdde5e8).rect(x-12,y-73,24,4).fill(C.cyan).rect(x+d*18-(d<0?32:0),y-44,32,6).fill(0x66717a)}
function enemyShape(e:Enemy){const g=e.g,r=e.role;g.clear();if(r==='drone')g.poly([-20,-16,20,-16,28,0,0,12,-28,0]).fill(0x26323b).rect(-14,-13,28,5).fill(C.cyan);else if(r==='heavy')g.poly([-25,-58,25,-58,32,0,-32,0]).fill(0x313943).rect(-20,-50,40,8).fill(C.red);else if(r==='runner')g.poly([-12,-40,13,-40,19,0,-19,0]).fill(0xdde4e7).rect(-12,-34,24,5).fill(C.amber);else if(r==='shield')g.poly([-20,-48,20,-48,24,0,-24,0]).fill(0x27323a).rect(12,-50,10,50).fill(C.cyan);else if(r==='hacker')g.poly([-15,-45,15,-45,20,0,-20,0]).fill(0x202c34).circle(0,-34,9).stroke({color:C.pink,width:3});else if(r==='sniper')g.poly([-13,-48,13,-48,17,0,-17,0]).fill(0x293139).rect(8,-36,34,4).fill(C.red);else if(r==='bomber')g.poly([-18,-46,18,-46,23,0,-23,0]).fill(0x332d27).circle(0,-30,10).fill(C.amber);else g.poly([-14,-44,14,-44,19,0,-19,0]).fill(0xd6dee1).rect(-12,-36,24,5).fill(C.pink);if(e.elite)g.circle(0,-30,28).stroke({color:C.amber,width:2,alpha:.8});}
function spawn(role:EnemyRole,elite=false){const d=ENEMIES[role],g=new Graphics(),e:Enemy={g,role,x:-45,y:floor()-(d.flying?90:0),hp:d.hp*(elite?1.65:1),maxHp:d.hp*(elite?1.65:1),speed:d.speed*(elite?1.12:1),elite,flying:!!d.flying,phase:'move',timer:0,knock:0,disabled:0,flash:0};enemyShape(e);g.position.set(e.x,e.y);actors.addChild(g);enemies.push(e);state.spawned++}
function drawTower(t:Tower){const g=t.g,r=t.hp/Math.max(1,t.maxHp);g.clear();if(t.type==='barrier')g.rect(-23,-66,46,66).fill(0x243039).stroke({color:C.amber,width:3});else if(t.type==='tesla')g.rect(-18,-28,36,28).fill(0x26313a).moveTo(-18,-28).lineTo(0,-56).lineTo(18,-28).stroke({color:C.cyan,width:4}).circle(0,-47,9).stroke({color:C.cyan,width:4});else if(t.type==='droneDock')g.rect(-25,-20,50,20).fill(0x27323a).poly([-20,-25,0,-48,20,-25]).stroke({color:C.pink,width:3});else if(t.type==='hackNode')g.rect(-20,-32,40,32).fill(0x222d35).circle(0,-43,15).stroke({color:C.pink,width:4});else if(t.type==='mineLayer')g.rect(-24,-22,48,22).fill(0x302d27).circle(0,-30,10).fill(C.amber);else g.rect(-20,-38,40,38).fill(0x27323a).rect(-48,-43,52,7).fill(0x66717a).rect(-12,-48,28,8).fill(C.cyan);g.rect(-24,-75,48,4).fill(0x252d35).rect(-24,-75,48*r,4).fill(r<.3?C.red:C.cyan);if(t.disabled>0)g.circle(0,-38,30).stroke({color:C.red,width:2,alpha:.8});}
function build(){const d=towerAt(state.towerMode);if(state.credits<d.cost)return msg('CREDITS // INSUFFICIENT',C.red);const free=pads().filter(x=>!towers.some(t=>Math.abs(t.x-x)<20));const x=free.sort((a,b)=>Math.abs(a-state.playerX)-Math.abs(b-state.playerX))[0];if(x===undefined)return msg('GRID // FULL',C.amber);state.credits-=d.cost;const t:Tower={g:new Graphics(),type:d.id,x,y:floor(),hp:d.maxHp,maxHp:d.maxHp,cool:0,disabled:0,mineReady:true};drawTower(t);t.g.position.set(x,t.y);actors.addChild(t.g);towers.push(t);msg(`${d.name} // ONLINE`)}
const input=new KeyboardInput({selectTower:i=>{state.towerMode=i;msg(`GRID // ${towerAt(i).name}`)},selectWeapon:i=>{state.weaponIndex=i;msg(`WEAPON // ${weaponAt(i).name}`,C.pink)},build,restart:()=>{if(state.gameOver)location.reload()}});
function fireProjectile(x:number,y:number,dmg:number,speed:number,dir:Facing,angle=0,knock=80,pierce=1,energy=false){const g=new Graphics().rect(-8,-2,16,4).fill(energy?C.cyan:C.pink);g.position.set(x,y);fx.addChild(g);bullets.push({g,x,y,px:x,py:y,vx:Math.cos(angle)*speed*dir,vy:Math.sin(angle)*speed,damage:dmg,knock,pierce,energy,hit:new Set()})}
function fireWeapon(w:WeaponDefinition){for(let i=0;i<w.pellets;i++){const a=w.pellets>1?-w.spreadRadians+w.spreadRadians*2*i/(w.pellets-1):(Math.random()*2-1)*w.spreadRadians;fireProjectile(state.playerX+state.facing*55,state.playerY-42,w.damage,w.projectileSpeed,state.facing,a,w.knockback,w.pierce,w.id==='railgun')}burst(state.playerX+state.facing*58,state.playerY-42)}
function damageEnemy(e:Enemy,damage:number,energy:boolean,knock=0){const d=ENEMIES[e.role];let mult=1;if(d.resistance===(energy?'energy':'ballistic'))mult=.55;if(d.vulnerability===(energy?'energy':'ballistic'))mult=1.35;e.hp-=damage*mult;e.knock+=knock*(e.flying?.25:1);e.flash=.08;burst(e.x,e.y-25,energy?C.cyan:C.pink)}
function updatePlayer(dt:number){const a=input.actions;if(a.left){state.playerX-=260*dt;state.facing=-1}if(a.right){state.playerX+=260*dt;state.facing=1}state.playerX=Math.max(50,Math.min(coreX()-70,state.playerX));if(a.jump&&state.grounded){state.vy=-420;state.grounded=false}if(!state.grounded){state.vy+=980*dt;state.playerY+=state.vy*dt;if(state.playerY>=floor()){state.playerY=floor();state.vy=0;state.grounded=true}}else state.playerY=floor();state.shootTimer-=dt;if(a.fire&&state.shootTimer<=0){const target=enemies.sort((x,y)=>Math.abs(x.x-state.playerX)-Math.abs(y.x-state.playerX))[0];if(target)state.facing=target.x<state.playerX?-1:1;const w=weaponAt(state.weaponIndex);fireWeapon(w);state.shootTimer=w.cooldown}repairTick-=dt;if(a.repair&&repairTick<=0){const t=towers.filter(t=>t.hp<t.maxHp&&Math.abs(t.x-state.playerX)<85).sort((a,b)=>Math.abs(a.x-state.playerX)-Math.abs(b.x-state.playerX))[0];if(t&&state.credits>=8){state.credits-=8;t.hp=Math.min(t.maxHp,t.hp+28);drawTower(t);repairTick=.25}}}
function nearestTower(e:Enemy,range=9999){return towers.filter(t=>t.hp>0&&Math.abs(t.x-e.x)<=range).sort((a,b)=>Math.abs(a.x-e.x)-Math.abs(b.x-e.x))[0]}
function updateEnemies(dt:number){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],d=ENEMIES[e.role];e.disabled=Math.max(0,e.disabled-dt);e.flash=Math.max(0,e.flash-dt);e.g.tint=e.flash>0?0xffd7e6:0xffffff;e.knock*=Math.pow(.03,dt);const barrier=!e.flying?towers.filter(t=>t.type==='barrier'&&t.hp>0&&t.x>=e.x&&t.x-e.x<48).sort((a,b)=>a.x-b.x)[0]:undefined;const structure=nearestTower(e,65);if(e.role==='hacker'){const target=nearestTower(e,d.hackRange);if(target){target.disabled=Math.max(target.disabled,1.2);drawTower(target);e.x+=e.speed*.18*dt}else e.x+=e.speed*dt}else if(e.role==='sniper'&&Math.abs(e.x-state.playerX)<=d.preferredRange!){e.timer-=dt;if(e.timer<=0){msg('SNIPER // LOCK',C.red);if(state.playerY>floor()-55){state.playerHp-=d.contactDamage;burst(state.playerX,state.playerY-40,C.red)}e.timer=2.3}}else if(e.role==='bomber'&&structure){structure.hp-=d.structureDamage!;for(const t of towers)if(Math.abs(t.x-structure.x)<95)t.hp-=28;burst(e.x,e.y-20,C.amber);e.hp=0}else if(barrier){barrier.hp-=((d.structureDamage??14)*(e.elite?1.3:1))*dt;e.x=barrier.x-(e.role==='heavy'?36:27);drawTower(barrier)}else{e.x+=e.speed*dt+e.knock*dt;if(structure&&e.role==='heavy'){structure.hp-=d.structureDamage!*dt;drawTower(structure)}}if(e.x>coreX()-45){state.coreHp-=d.coreDamage*dt;e.x-=10*dt}e.y=floor()-(e.flying?90+Math.sin(performance.now()/260+i)*14:0);e.g.position.set(e.x,e.y);if(e.hp<=0){state.credits+=d.reward*(e.elite?2:1);state.killed++;burst(e.x,e.y-25,C.amber);e.g.destroy();enemies.splice(i,1)}}for(let i=towers.length-1;i>=0;i--)if(towers[i].hp<=0){msg(`${towerAt(TOWERS.findIndex(d=>d.id===towers[i].type)).name} // DESTROYED`,C.red);towers[i].g.destroy();towers.splice(i,1)}}
function updateBullets(dt:number){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.g.position.set(b.x,b.y);for(const e of enemies){if(b.hit.has(e))continue;const hw=e.role==='heavy'?34:24,hh=e.flying?28:48,minX=Math.min(b.px,b.x),maxX=Math.max(b.px,b.x);if(maxX>=e.x-hw&&minX<=e.x+hw&&Math.abs(b.y-(e.y-(e.flying?0:26)))<hh){damageEnemy(e,b.damage,b.energy,Math.sign(b.vx)*b.knock);b.hit.add(e);if(--b.pierce<=0)break}}if(b.pierce<=0||b.x<-140||b.x>app.renderer.width+140){b.g.destroy();bullets.splice(i,1)}}}
function updateTowers(dt:number){for(const t of towers){t.cool-=dt;t.disabled=Math.max(0,t.disabled-dt);if(t.disabled>0||t.type==='barrier')continue;const def=TOWERS.find(d=>d.id===t.type)!;const targets=enemies.filter(e=>Math.abs(e.x-t.x)<=def.range).sort((a,b)=>Math.abs(a.x-coreX())-Math.abs(b.x-coreX()));if(!targets.length||t.cool>0)continue;if(t.type==='tesla'){for(const e of targets.slice(0,3)){damageEnemy(e,20,true);e.disabled=Math.max(e.disabled,.35)}burst(targets[0].x,targets[0].y-20,C.cyan)}else if(t.type==='hackNode'){const machine=targets.find(e=>['drone','hacker','shield'].includes(e.role));if(machine){machine.disabled=2.4;machine.knock=-55;damageEnemy(machine,12,true);msg('HOSTILE // JAMMED',C.pink)}}else if(t.type==='mineLayer'){for(const e of targets.filter(e=>!e.flying).slice(0,4))damageEnemy(e,38,false,150);burst(t.x,t.y-10,C.amber)}else{const e=targets[0],dir=(e.x<t.x?-1:1)as Facing;fireProjectile(t.x+dir*35,t.y-38,t.type==='droneDock'?14:17,t.type==='droneDock'?620:760,dir,0,t.type==='droneDock'?55:70,1,false)}t.cool=def.cadence}}
function prepareWave(){queue=[];for(const entry of waveComposition(state.wave))for(let i=0;i<entry.count;i++)queue.push({role:entry.role,elite:Math.random()<(entry.eliteChance??0)});queue.sort(()=>Math.random()-.5);state.waveSize=queue.length;state.spawned=0;state.killed=0;wavePreview=waveLabel(state.wave);msg(`WAVE ${state.wave} // ${wavePreview}`,C.amber)}prepareWave();
function updateWave(dt:number){state.spawnTimer-=dt;if(queue.length&&state.spawnTimer<=0){const n=queue.shift()!;spawn(n.role,n.elite);state.spawnTimer=Math.max(.42,1.05-state.wave*.035)}if(!queue.length&&enemies.length===0){state.wave++;state.credits+=100;state.spawnTimer=2;prepareWave()}if(state.playerHp<=0||state.coreHp<=0){state.gameOver=true;msg(state.coreHp<=0?'CORE // BREACHED // R':'OPERATOR // DOWN // R',C.red)}}
function drawHud(){hud.removeChildren();const w=app.renderer.width;const p=new Graphics().roundRect(12,12,w-24,66,5).fill({color:0x080d12,alpha:.86}).stroke({color:0x33414a,width:1});hud.addChild(p);const text=new Text({text:`NEON // SIEGE    W${state.wave}  ${wavePreview}\nCORE ${Math.max(0,state.coreHp).toFixed(0)}   HP ${Math.max(0,state.playerHp).toFixed(0)}   $${Math.floor(state.credits)}   ${weaponAt(state.weaponIndex).name}   ${towerAt(state.towerMode).name}`,style:new TextStyle({fill:C.white,fontSize:11,fontWeight:'800',letterSpacing:1})});text.position.set(24,25);hud.addChild(text);if(innerWidth>900){const h=new Text({text:'1-6 TOWERS  |  B BUILD  E REPAIR  |  Z/X/C/V WEAPONS  |  A/D MOVE  SPACE JUMP  J FIRE',style:new TextStyle({fill:C.muted,fontSize:10,fontWeight:'700'})});h.position.set(20,app.renderer.height-26);hud.addChild(h)}}
app.ticker.add(t=>{const dt=Math.min(.033,t.deltaMS/1000);if(!state.gameOver){updatePlayer(dt);updateEnemies(dt);updateBullets(dt);updateTowers(dt);updateWave(dt)}drawWorld();drawHud()});
