import{Application,Container,Graphics,Text,TextStyle}from'pixi.js';
import{WEAPONS,weaponAt,type WeaponDefinition}from'./content/weapons';
import{TOWERS,towerAt}from'./content/towers';
import{ENEMIES,waveComposition,waveLabel,type EnemyRole}from'./content/enemies';
import{CONNECTORS,LANE_NAMES,lanePads,laneY,preferredLane,type LaneId}from'./content/lanes';
import{defaultModifiers,upgradeChoices,type RunModifiers}from'./content/upgrades';
import{createInitialGameState,type Facing,type TowerType}from'./domain/models';
import{KeyboardInput}from'./input/KeyboardInput';
import{COLORS as C}from'./presentation/theme';

const app=new Application();await app.init({background:'#05070b',resizeTo:window,antialias:false});document.querySelector('#app')!.appendChild(app.canvas);
const world=new Container(),bg=new Graphics(),actors=new Container(),fx=new Container(),hud=new Container();world.addChild(bg,actors);app.stage.addChild(world,fx,hud);
const state=createInitialGameState(),mods:RunModifiers=defaultModifiers(),owned=new Set<string>();state.playerX=app.renderer.width*.54;let lane:LaneId=1,stateY=laneY(app.renderer.height,lane),laneCooldown=0,prevUp=false,prevDown=false,choosing=false,runComplete=false,repairTick=0;
interface Enemy{g:Graphics;role:EnemyRole;lane:LaneId;x:number;y:number;hp:number;maxHp:number;speed:number;elite:boolean;flying:boolean;timer:number;knock:number;disabled:number;flash:number;}
interface Tower{g:Graphics;type:TowerType;lane:LaneId;x:number;y:number;hp:number;maxHp:number;cool:number;disabled:number;}
interface Bullet{g:Graphics;lane:LaneId;x:number;y:number;px:number;py:number;vx:number;vy:number;damage:number;knock:number;pierce:number;energy:boolean;hit:Set<Enemy>;}
const enemies:Enemy[]=[],towers:Tower[]=[],bullets:Bullet[]=[];let queue:{role:EnemyRole;elite:boolean;lane:LaneId}[]=[];let spawnTimer=.5;
let boss:Enemy|undefined,bossActive=false,bossAbility=0,escapeActive=false,escapeTime=60;
const player=new Graphics();actors.addChild(player);
const coreX=()=>app.renderer.width*.91;const floor=(l:LaneId)=>laneY(app.renderer.height,l);
const pads=(l:LaneId)=>lanePads(app.renderer.width,l,mods.extraPads).filter(x=>x<coreX()-72);
function msg(s:string,color=C.cyan){const t=new Text({text:s,style:new TextStyle({fill:color,fontSize:13,fontWeight:'900',letterSpacing:1})});t.anchor.set(.5);t.position.set(app.renderer.width/2,82);fx.addChild(t);let life=1.25;const f=()=>{life-=app.ticker.deltaMS/1000;t.alpha=Math.min(1,Math.max(0,life/.3));if(life<=0){t.destroy();app.ticker.remove(f)}};app.ticker.add(f)}
function burst(x:number,y:number,color=C.pink){for(let i=0;i<5;i++){const g=new Graphics().circle(0,0,2).fill(color);g.position.set(x+(Math.random()-.5)*22,y+(Math.random()-.5)*18);fx.addChild(g);setTimeout(()=>g.destroy(),120)}}
function drawWorld(){const w=app.renderer.width,h=app.renderer.height;bg.clear().rect(0,0,w,h).fill(C.bg);for(let i=0;i<10;i++){const x=i*w/9-30,bh=70+(i*47)%120;bg.rect(x,h*.25-bh,90+(i*29)%75,bh).fill(i%2?0x0a151c:0x0d1920)}for(let l=0;l<3;l++){const li=l as LaneId,y=floor(li);bg.rect(0,y,w,li===2?h-y:7).fill(li===2?0x090d12:0x121920).rect(0,y-3,w,3).fill({color:li===1?C.cyan:C.cyanDim,alpha:.58});pads(li).forEach(x=>bg.poly([x-28,y,x+28,y,x+22,y-7,x-22,y-7]).fill(towers.some(t=>t.lane===li&&Math.abs(t.x-x)<14)?0x20262c:0x11181e).stroke({color:C.cyanDim,width:1,alpha:.7}));const label=new Text({text:LANE_NAMES[li],style:new TextStyle({fill:C.muted,fontSize:9,fontWeight:'800'})});label.position.set(8,y-18);hud.addChild(label);bg.poly([coreX()-34,y,coreX()-28,y-72,coreX()+28,y-72,coreX()+34,y]).fill(0x172029).stroke({color:state.coreHp<35?C.red:C.cyan,width:2}).circle(coreX(),y-38,13).stroke({color:C.amber,width:3})}for(const c of CONNECTORS){const x=c.x*w,y1=floor(c.from as LaneId),y2=floor(c.to as LaneId);bg.moveTo(x,y1).lineTo(x,y2).stroke({color:c.name==='ZIPLINE'?C.pink:C.amber,width:c.name==='ELEVATOR'?4:2,alpha:.28});bg.circle(x,(y1+y2)/2,4).fill(c.name==='ZIPLINE'?C.pink:C.amber)}if(escapeActive){bg.rect(12,floor(0)-92,88,88).stroke({color:C.amber,width:3}).poly([30,floor(0)-45,72,floor(0)-70,72,floor(0)-20]).fill(C.amber)}drawPlayer()}
function drawPlayer(){const y=stateY,x=state.playerX,d=state.facing;player.clear().poly([x-14,y-58,x+13,y-58,x+19,y-10,x-18,y-10]).fill(0x26313a).rect(x-16,y-49,30,17).fill(C.pink).circle(x,y-66,11).fill(0xdde5e8).rect(x-11,y-69,22,4).fill(C.cyan).rect(x+d*17-(d<0?30:0),y-41,30,5).fill(0x66717a)}
function enemyShape(e:Enemy){const g=e.g,r=e.role;g.clear();if(r==='drone')g.poly([-18,-14,18,-14,25,0,0,10,-25,0]).fill(0x26323b).rect(-12,-11,24,4).fill(C.cyan);else if(r==='heavy')g.poly([-23,-54,23,-54,30,0,-30,0]).fill(0x313943).rect(-18,-46,36,7).fill(C.red);else if(r==='runner')g.poly([-11,-38,12,-38,17,0,-17,0]).fill(0xdde4e7).rect(-10,-31,20,4).fill(C.amber);else if(r==='shield')g.poly([-18,-44,18,-44,22,0,-22,0]).fill(0x27323a).rect(11,-46,9,46).fill(C.cyan);else if(r==='hacker')g.poly([-14,-42,14,-42,18,0,-18,0]).fill(0x202c34).circle(0,-31,8).stroke({color:C.pink,width:3});else if(r==='sniper')g.poly([-12,-44,12,-44,16,0,-16,0]).fill(0x293139).rect(7,-33,30,4).fill(C.red);else if(r==='bomber')g.poly([-16,-43,16,-43,21,0,-21,0]).fill(0x332d27).circle(0,-28,9).fill(C.amber);else g.poly([-13,-41,13,-41,18,0,-18,0]).fill(0xd6dee1).rect(-11,-33,22,4).fill(C.pink);if(e.elite)g.circle(0,-27,26).stroke({color:C.amber,width:2,alpha:.8});if(e===boss)g.circle(0,-28,40).stroke({color:C.pink,width:4,alpha:.9})}
function spawn(role:EnemyRole,elite:boolean,l:LaneId){const d=ENEMIES[role],g=new Graphics(),e:Enemy={g,role,lane:l,x:-45,y:floor(l),hp:d.hp*(elite?1.65:1),maxHp:d.hp*(elite?1.65:1),speed:d.speed*(elite?1.12:1),elite,flying:!!d.flying,timer:0,knock:0,disabled:0,flash:0};enemyShape(e);g.position.set(e.x,e.y-(e.flying?38:0));actors.addChild(g);enemies.push(e);state.spawned++;return e}
function drawTower(t:Tower){const g=t.g,r=t.hp/Math.max(1,t.maxHp);g.clear();if(t.type==='barrier')g.rect(-22,-58,44,58).fill(0x243039).stroke({color:C.amber,width:3});else if(t.type==='tesla')g.rect(-17,-25,34,25).fill(0x26313a).moveTo(-16,-25).lineTo(0,-50).lineTo(16,-25).stroke({color:C.cyan,width:4}).circle(0,-42,8).stroke({color:C.cyan,width:4});else if(t.type==='droneDock')g.rect(-23,-18,46,18).fill(0x27323a).poly([-18,-22,0,-43,18,-22]).stroke({color:C.pink,width:3});else if(t.type==='hackNode')g.rect(-18,-29,36,29).fill(0x222d35).circle(0,-38,13).stroke({color:C.pink,width:4});else if(t.type==='mineLayer')g.rect(-22,-20,44,20).fill(0x302d27).circle(0,-27,9).fill(C.amber);else g.rect(-18,-34,36,34).fill(0x27323a).rect(-43,-39,47,6).fill(0x66717a).rect(-10,-44,26,7).fill(C.cyan);g.rect(-22,-66,44,4).fill(0x252d35).rect(-22,-66,44*r,4).fill(r<.3?C.red:C.cyan);if(t.disabled>0)g.circle(0,-34,27).stroke({color:C.red,width:2,alpha:.8})}
function build(){const d=towerAt(state.towerMode),cost=Math.ceil(d.cost*(1-mods.buildDiscount));if(state.credits<cost)return msg('CREDITS // INSUFFICIENT',C.red);const free=pads(lane).filter(x=>!towers.some(t=>t.lane===lane&&Math.abs(t.x-x)<18)),x=free.sort((a,b)=>Math.abs(a-state.playerX)-Math.abs(b-state.playerX))[0];if(x===undefined)return msg(`${LANE_NAMES[lane]} // GRID FULL`,C.amber);state.credits-=cost;const maxHp=d.maxHp*mods.towerHp,t:Tower={g:new Graphics(),type:d.id,lane,x,y:floor(lane),hp:maxHp,maxHp,cool:0,disabled:0};drawTower(t);t.g.position.set(x,t.y);actors.addChild(t.g);towers.push(t);msg(`${LANE_NAMES[lane]} // ${d.name} ONLINE`)}
const input=new KeyboardInput({selectTower:i=>{state.towerMode=i;msg(`GRID // ${towerAt(i).name}`)},selectWeapon:i=>{state.weaponIndex=i;msg(`WEAPON // ${weaponAt(i).name}`,C.pink)},build,restart:()=>{if(state.gameOver||runComplete)location.reload()}});
function fireProjectile(x:number,y:number,dmg:number,speed:number,dir:Facing,angle=0,knock=80,pierce=1,energy=false){const g=new Graphics().rect(-8,-2,16,4).fill(energy?C.cyan:C.pink);g.position.set(x,y);fx.addChild(g);bullets.push({g,lane,x,y,px:x,py:y,vx:Math.cos(angle)*speed*dir,vy:Math.sin(angle)*speed,damage:dmg,knock,pierce,energy,hit:new Set()})}
function fireWeapon(w:WeaponDefinition){const energy=w.id==='railgun';for(let i=0;i<w.pellets;i++){const a=w.pellets>1?-w.spreadRadians+w.spreadRadians*2*i/(w.pellets-1):(Math.random()*2-1)*w.spreadRadians,base=w.damage*mods.playerDamage*(energy?mods.energy:mods.ballistic)*(state.grounded?1:mods.airDamage);fireProjectile(state.playerX+state.facing*52,stateY-38,base,w.projectileSpeed,state.facing,a,w.knockback*mods.weaponKnock,w.pierce+mods.weaponPierce,energy)}burst(state.playerX+state.facing*54,stateY-38)}
function damageEnemy(e:Enemy,damage:number,energy:boolean,knock=0){const d=ENEMIES[e.role];let mult=1;if(d.resistance===(energy?'energy':'ballistic'))mult=.55;if(d.vulnerability===(energy?'energy':'ballistic'))mult=1.35;e.hp-=damage*mult;e.knock+=knock*(e.flying?.25:1);e.flash=.08;burst(e.x,e.y-24,energy?C.cyan:C.pink)}
function transfer(direction:-1|1){if(laneCooldown>0)return;const next=lane+direction;if(next<0||next>2)return;lane=next as LaneId;stateY=floor(lane);state.playerY=stateY;state.grounded=true;laneCooldown=.42/mods.laneTransfer;msg(`TRANSIT // ${LANE_NAMES[lane]}`,C.cyan)}
function updatePlayer(dt:number){const a=input.actions;laneCooldown-=dt;const upEdge=a.laneUp&&!prevUp,downEdge=a.laneDown&&!prevDown;prevUp=a.laneUp;prevDown=a.laneDown;if(upEdge)transfer(-1);if(downEdge)transfer(1);if(a.left){state.playerX-=260*mods.moveSpeed*dt;state.facing=-1}if(a.right){state.playerX+=260*mods.moveSpeed*dt;state.facing=1}state.playerX=Math.max(45,Math.min(coreX()-58,state.playerX));const base=floor(lane);if(a.jump&&state.grounded){state.vy=-410;state.grounded=false}if(!state.grounded){state.vy+=960*dt;stateY+=state.vy*dt;if(stateY>=base){stateY=base;state.vy=0;state.grounded=true}}else stateY=base;state.playerY=stateY;state.shootTimer-=dt;if(a.fire&&state.shootTimer<=0){const target=enemies.filter(e=>e.lane===lane).sort((x,y)=>Math.abs(x.x-state.playerX)-Math.abs(y.x-state.playerX))[0];if(target)state.facing=target.x<state.playerX?-1:1;const w=weaponAt(state.weaponIndex);fireWeapon(w);state.shootTimer=w.cooldown/mods.fireRate}repairTick-=dt;if(a.repair&&repairTick<=0){const t=towers.filter(t=>t.lane===lane&&t.hp<t.maxHp&&Math.abs(t.x-state.playerX)<82).sort((a,b)=>Math.abs(a.x-state.playerX)-Math.abs(b.x-state.playerX))[0];if(t&&state.credits>=8){state.credits-=8;t.hp=Math.min(t.maxHp,t.hp+28*mods.repairPower);drawTower(t);repairTick=.25}}}
function nearestTower(e:Enemy,range=9999){return towers.filter(t=>t.hp>0&&t.lane===e.lane&&Math.abs(t.x-e.x)<=range).sort((a,b)=>Math.abs(a.x-e.x)-Math.abs(b.x-e.x))[0]}
function startEscape(){boss=undefined;bossActive=false;escapeActive=true;escapeTime=60;for(const e of enemies)e.g.destroy();enemies.length=0;queue=[];msg('HACK COMPLETE // CORPORATE STRIKE IN 60 SEC',C.amber)}
function killEnemy(e:Enemy,index:number){if(e===boss){burst(e.x,e.y-25,C.amber);e.g.destroy();enemies.splice(index,1);startEscape();return}const d=ENEMIES[e.role];state.credits+=d.reward*(e.elite?2:1)+mods.killCredits;state.playerHp=Math.min(mods.maxHp,state.playerHp+mods.killHeal);state.killed++;burst(e.x,e.y-25,C.amber);e.g.destroy();enemies.splice(index,1)}
function updateEnemies(dt:number){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i],d=ENEMIES[e.role];e.disabled=Math.max(0,e.disabled-dt);e.flash=Math.max(0,e.flash-dt);e.g.tint=e.flash>0?0xffd7e6:0xffffff;e.knock*=Math.pow(.03,dt);const barrier=!e.flying?towers.filter(t=>t.type==='barrier'&&t.lane===e.lane&&t.hp>0&&t.x>=e.x&&t.x-e.x<48).sort((a,b)=>a.x-b.x)[0]:undefined,structure=nearestTower(e,65);if(e.disabled<=0){if(e.role==='hacker'){const target=nearestTower(e,d.hackRange);if(target){target.disabled=Math.max(target.disabled,1.25);drawTower(target);e.x+=e.speed*.16*dt}else e.x+=e.speed*dt}else if(e.role==='sniper'&&e.lane===lane&&Math.abs(e.x-state.playerX)<=d.preferredRange!){e.timer-=dt;if(e.timer<=0){msg(`SNIPER // ${LANE_NAMES[e.lane]} LOCK`,C.red);if(state.grounded){state.playerHp-=d.contactDamage*(1-mods.contactResist);burst(state.playerX,stateY-36,C.red)}e.timer=2.2}}else if(e.role==='bomber'&&structure){structure.hp-=d.structureDamage!;for(const t of towers)if(t.lane===e.lane&&Math.abs(t.x-structure.x)<88)t.hp-=26;burst(e.x,e.y-18,C.amber);e.hp=0}else if(barrier){barrier.hp-=((d.structureDamage??14)*(e.elite?1.3:1))*dt;e.x=barrier.x-(e.role==='heavy'?34:25);drawTower(barrier)}else{e.x+=e.speed*dt+e.knock*dt;if(structure&&e.role==='heavy'){structure.hp-=d.structureDamage!*dt;drawTower(structure)}}}if(e.lane===lane&&Math.abs(e.x-state.playerX)<27&&state.grounded&&state.hitCooldown<=0){state.playerHp-=d.contactDamage*(1-mods.contactResist);state.hitCooldown=.65;state.playerX+=e.x<state.playerX?42:-42;burst(state.playerX,stateY-32,C.red)}if(e.x>coreX()-38){state.coreHp-=d.coreDamage*(1-mods.coreShield)*dt;e.x-=8*dt}e.y=floor(e.lane);e.g.position.set(e.x,e.y-(e.flying?38+Math.sin(performance.now()/250+i)*7:0));if(e.hp<=0)killEnemy(e,i)}state.hitCooldown=Math.max(0,state.hitCooldown-dt);for(let i=towers.length-1;i>=0;i--){const t=towers[i];if(mods.autoRepair>0&&t.hp>0)t.hp=Math.min(t.maxHp,t.hp+mods.autoRepair*dt);if(t.hp<=0){msg(`${LANE_NAMES[t.lane]} // ${t.type.toUpperCase()} LOST`,C.red);t.g.destroy();towers.splice(i,1)}}}
function updateBullets(dt:number){for(let i=bullets.length-1;i>=0;i--){const b=bullets[i];b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.g.position.set(b.x,b.y);for(const e of enemies){if(e.lane!==b.lane||b.hit.has(e))continue;const hw=e===boss?45:e.role==='heavy'?34:23,hh=e===boss?62:e.flying?30:46,minX=Math.min(b.px,b.x),maxX=Math.max(b.px,b.x);if(maxX>=e.x-hw&&minX<=e.x+hw&&Math.abs(b.y-(e.y-(e.flying?38:25)))<hh){damageEnemy(e,b.damage,b.energy,Math.sign(b.vx)*b.knock);b.hit.add(e);if(--b.pierce<=0)break}}if(b.pierce<=0||b.x<-150||b.x>app.renderer.width+150){b.g.destroy();bullets.splice(i,1)}}}
function updateTowers(dt:number){for(const t of towers){t.cool-=dt;t.disabled=Math.max(0,t.disabled-dt);if(t.disabled>0||t.type==='barrier')continue;const def=TOWERS.find(d=>d.id===t.type)!;let targets=enemies.filter(e=>(t.type==='droneDock'?Math.abs(e.lane-t.lane)<=1:e.lane===t.lane)&&Math.abs(e.x-t.x)<=def.range*mods.towerRange).sort((a,b)=>Math.abs(a.x-coreX())-Math.abs(b.x-coreX()));if(!targets.length||t.cool>0)continue;const cadence=def.cadence/mods.towerRate;if(t.type==='tesla'){for(const e of targets.slice(0,3))damageEnemy(e,20*mods.towerDamage*mods.energy,true);burst(t.x,t.y-40,C.cyan)}else if(t.type==='hackNode'){const e=targets.find(e=>['drone','hacker','bomber'].includes(e.role));if(e){e.disabled=Math.max(e.disabled,1.8);damageEnemy(e,9*mods.towerDamage*mods.energy,true)}}else if(t.type==='mineLayer'){for(const e of targets.filter(e=>e.lane===t.lane).slice(0,5))damageEnemy(e,34*mods.towerDamage,false,80);burst(t.x,t.y-18,C.amber)}else if(t.type==='droneDock'){const e=targets[0];damageEnemy(e,14*mods.towerDamage*mods.ballistic,false,28);burst(e.x,e.y-20,C.pink)}else{const e=targets[0],dir:Facing=e.x<t.x?-1:1;const g=new Graphics().rect(-6,-2,13,4).fill(C.cyan);g.position.set(t.x,t.y-34);fx.addChild(g);setTimeout(()=>g.destroy(),70);damageEnemy(e,17*mods.towerDamage*mods.ballistic,false,50*dir)}t.cool=cadence}}
function startBoss(){bossActive=true;bossAbility=2.5;boss=spawn('heavy',true,1);boss.x=app.renderer.width*.18;boss.hp=boss.maxHp=1350;boss.speed=18;enemyShape(boss);boss.g.scale.set(1.45);msg('BOSS // CORPORATE SIEGE FRAME',C.red)}
function updateBoss(dt:number){if(!bossActive||!boss)return;bossAbility-=dt;if(bossAbility>0)return;bossAbility=4.5;const next=((boss.lane+1+Math.floor(Math.random()*2))%3)as LaneId;boss.lane=next;boss.x=Math.min(boss.x,app.renderer.width*.55);for(const t of towers)if(t.lane===next){t.disabled=Math.max(t.disabled,2.2);t.hp-=18;drawTower(t)}for(let i=0;i<2;i++){const d=spawn('drone',false,next);d.x=Math.max(-35,boss.x-90-i*35)}msg(`BOSS BREACH // ${LANE_NAMES[next]}`,C.red)}
function updateEscape(dt:number){if(!escapeActive)return;escapeTime-=dt;if(lane===0&&state.playerX<=105){escapeActive=false;runComplete=true;msg('EXTRACTION COMPLETE // RUN SECURED // R',C.amber);return}if(escapeTime<=0){escapeActive=false;state.gameOver=true;msg('CORPORATE STRIKE // EXTRACTION FAILED // R',C.red)}}
function prepareWave(w:number){queue=[];let idx=0;for(const entry of waveComposition(w))for(let i=0;i<entry.count;i++){const elite=Math.random()<(entry.eliteChance??0);queue.push({role:entry.role,elite,lane:preferredLane(entry.role,idx++)})}queue.sort(()=>Math.random()-.5);state.spawned=0;state.killed=0;spawnTimer=.6;msg(`WAVE ${w} // ${waveLabel(w)}`,C.pink)}
function showUpgrade(nextWave:number){choosing=true;const overlay=document.querySelector<HTMLElement>('#upgrade-overlay'),cards=document.querySelector<HTMLElement>('#upgrade-cards'),title=document.querySelector<HTMLElement>('#upgrade-title');if(!overlay||!cards)return resume(nextWave);cards.innerHTML='';if(title)title.textContent=`WAVE ${state.wave} CLEARED // INSTALL 1 OF 3`;for(const choice of upgradeChoices(owned)){const b=document.createElement('button');b.className='upgrade-card';b.innerHTML=`<b>${choice.domain} // ${choice.name}</b><span>${choice.description}</span>`;b.onclick=()=>{const oldMax=mods.maxHp;choice.apply(mods);owned.add(choice.id);if(mods.maxHp>oldMax)state.playerHp+=mods.maxHp-oldMax;overlay.classList.remove('is-open');resume(nextWave)};cards.appendChild(b)}overlay.classList.add('is-open')}
function resume(w:number){choosing=false;state.wave=w;prepareWave(w)}
function updateWave(dt:number){if(choosing||runComplete||bossActive||escapeActive)return;spawnTimer-=dt;if(queue.length&&spawnTimer<=0){const n=queue.shift()!;spawn(n.role,n.elite,n.lane);spawnTimer=Math.max(.34,.95-state.wave*.045)}if(!queue.length&&enemies.length===0){if(state.wave>=10){startBoss();return}const next=state.wave+1;if(state.wave%2===0)showUpgrade(next);else resume(next)}}
function drawHud(){hud.removeChildren();const w=app.renderer.width;const panel=new Graphics().roundRect(12,10,w-24,56,5).fill({color:0x0b1016,alpha:.88}).stroke({color:0x313b45,width:1});hud.addChild(panel);let phase=`W${state.wave}/10`;if(bossActive&&boss)phase=`BOSS ${Math.max(0,boss.hp/boss.maxHp*100).toFixed(0)}%`;if(escapeActive)phase=`ESCAPE ${Math.max(0,escapeTime).toFixed(0)}s`;const t=new Text({text:`NEON//SIEGE   ${phase}   ${LANE_NAMES[lane]}   ${weaponAt(state.weaponIndex).name}   CORE ${Math.max(0,state.coreHp).toFixed(0)}   HP ${Math.max(0,state.playerHp).toFixed(0)}/${mods.maxHp}   $${Math.floor(state.credits)}`,style:new TextStyle({fill:escapeActive?C.amber:C.white,fontSize:11,fontWeight:'900'})});t.position.set(24,29);hud.addChild(t);const preview=new Text({text:escapeActive?'EXTRACTION // ROOFTOP LEFT':bossActive?'STATIC DEFENSE INVALIDATED':waveLabel(state.wave),style:new TextStyle({fill:bossActive?C.red:C.muted,fontSize:8,fontWeight:'700'})});preview.anchor.set(1,0);preview.position.set(w-25,49);hud.addChild(preview)}
prepareWave(1);
app.ticker.add(t=>{const dt=Math.min(.033,t.deltaMS/1000);hud.removeChildren();drawWorld();drawHud();if(!state.gameOver&&!choosing&&!runComplete){updatePlayer(dt);updateEnemies(dt);updateBullets(dt);updateTowers(dt);updateWave(dt);updateBoss(dt);updateEscape(dt);if(state.playerHp<=0||state.coreHp<=0){state.gameOver=true;msg(state.playerHp<=0?'OPERATOR DOWN // R':'CORE BREACHED // R',C.red)}}});
window.addEventListener('resize',()=>{state.playerX=Math.min(state.playerX,coreX()-58);stateY=floor(lane)});
