import { Application,Container } from 'pixi.js';
import { HeroId,createLoadout } from './heroes';import { SkillId } from './skills';import { Locale } from './i18n';import { summaryText } from './telemetry';import { createMatchRecord,deleteMatchRecords,loadMatchRecords,saveMatchRecord } from './match-records';import { downloadText,exportMatchesCsv,exportMatchesJson } from './match-export';import { GameSettings,loadSettings,resetSettings,saveSettings } from './settings';import { MatchEvent,createMatchRuntime } from './runtime/match-runtime';import { ViewContext,prepareStage } from './ui/theme';import { renderBoard } from './ui/board-view';import { FEEDBACK_MS,createCombatFeedback } from './ui/feedback';import { renderFooter,renderHudPanel,renderHudTop } from './ui/hud-view';import { renderSkillBar } from './ui/skill-view';import { renderHeroSelect } from './ui/hero-select-view';import { renderHeroCollection,renderHeroDetail,renderLoadoutManagement } from './ui/hero-management-view';import { renderCpuMatchSetup } from './ui/cpu-match-setup-view';import { MenuScreen,renderMenuShell } from './ui/menu-shell';import { BattleMode,renderBattlePreview,renderModeSelect,renderPauseOverlay,renderResultOverlay } from './ui/lifecycle-view';import './style.css';
let settings=loadSettings(),locale:Locale=settings.locale;const app=new Application();await app.init({resizeTo:window,antialias:settings.animations,background:settings.theme==='dark'?'#211f29':'#f3efe7',resolution:Math.min(devicePixelRatio,2)});document.querySelector('#app')!.appendChild(app.canvas);const root=new Container();app.stage.addChild(root);
type Screen='menu'|'hero-collection'|'hero-detail'|'loadout'|'mode-select'|'hero-select'|'cpu-match-setup'|'battle-preview'|'match';let screen:Screen='menu';let managedHeroId:HeroId='arcanist';let menuScreen:MenuScreen='home';let battleMode:BattleMode='cpu',paused=false,cpuRandomOpponent=false;let selectedRecordId:string|null=null,replayIndex=0;let selectedRecordIds=new Set<string>();let matchStartedAt=new Date().toISOString(),recordedOutcome:string|null=null;const feedback=createCombatFeedback(()=>render());const runtime=createMatchRuntime({heroId:'arcanist',schedule:setTimeout,cancel:clearTimeout,onChange:()=>{persistCompletedMatch();render();},onEvent:applyEvent});
function applyEvent(event:MatchEvent){switch(event.kind){case 'reset':return feedback.clear();case 'move':return feedback.markMove(event.at);case 'mana-gain':return feedback.showManaGain(event.amount,event.fromSkill?FEEDBACK_MS.manaSkill:FEEDBACK_MS.manaPlace);case 'passive':return feedback.showPassiveTriggered(event.at);case 'action':return feedback.showAction(event.at);case 'action-feedback':if(settings.animations&&event.feedback.kind==='skill'&&event.feedback.source)feedback.showSkillTrail(event.feedback.source,event.feedback.at);return;case 'invalid':return feedback.showInvalidTarget(event.at);case 'winning-line':return feedback.markWinningLine(event.cells);}}
function persistCompletedMatch(){const match=runtime.snapshot(),outcome=match.turn.status;if(outcome==='playing'||recordedOutcome===outcome)return;const metrics=runtime.metrics();saveMatchRecord(createMatchRecord({startedAt:matchStartedAt,heroId:runtime.heroId(),cpuHeroId:runtime.cpuHeroId(),result:outcome,turns:match.turn.turn,actions:match.actionHistory,metrics:{...metrics,skillUses:{...metrics.skillUses},skillOpportunities:{...metrics.skillOpportunities},skillUseManaTotal:{...metrics.skillUseManaTotal}}}));recordedOutcome=outcome;}
const view=():ViewContext=>({root,locale});function updateSettings(next:GameSettings){settings=next;locale=next.locale;saveSettings(next);app.renderer.background.color=next.theme==='dark'?0x211f29:0xf3efe7;render();}
function goHome(){paused=false;screen='menu';menuScreen='home';render();}
function drawMenu(){const ctx=view();prepareStage(root,app.screen.width,app.screen.height);const records=loadMatchRecords();renderMenuShell(ctx,{screen:menuScreen,records,settings,selectedRecordId,selectedRecordIds,replayIndex,onReplayIndex:(index)=>{replayIndex=index;render();},onNavigate:(next)=>{menuScreen=next;selectedRecordId=null;replayIndex=0;screen='menu';render();},onHeroes:()=>{screen='hero-collection';render();},onSelectRecord:(id)=>{selectedRecordId=id;replayIndex=0;render();},onToggleRecord:(id)=>{selectedRecordIds.has(id)?selectedRecordIds.delete(id):selectedRecordIds.add(id);render();},onSelectAll:()=>{selectedRecordIds=selectedRecordIds.size===records.length?new Set():new Set(records.map(r=>r.id));render();},onDeleteSelected:()=>{deleteMatchRecords([...selectedRecordIds]);selectedRecordIds.clear();render();},onExport:(format)=>{const chosen=records.filter(r=>selectedRecordIds.has(r.id));const target=chosen.length?chosen:records;if(!target.length)return;downloadText(`gomoku-rpg-matches.${format}`,format==='json'?exportMatchesJson(target):exportMatchesCsv(target),format==='json'?'application/json':'text/csv');},onSettingsChange:updateSettings,onResetSettings:()=>updateSettings(resetSettings()),onStart:()=>{screen='mode-select';render();}});}
function drawHeroCollection(){prepareStage(root,app.screen.width,app.screen.height);renderHeroCollection(view(),{onBack:goHome,onHero:(id)=>{managedHeroId=id;screen='hero-detail';render();}});}
function drawHeroDetail(){prepareStage(root,app.screen.width,app.screen.height);renderHeroDetail(view(),{heroId:managedHeroId,loadout:createLoadout(managedHeroId),onBack:()=>{screen='hero-collection';render();},onManageLoadout:()=>{screen='loadout';render();}});}
function drawLoadout(){prepareStage(root,app.screen.width,app.screen.height);renderLoadoutManagement(view(),{heroId:managedHeroId,loadout:createLoadout(managedHeroId),onBack:()=>{screen='hero-detail';render();}});}
function drawModeSelect(){prepareStage(root,app.screen.width,app.screen.height);renderModeSelect(view(),{onBack:goHome,onMode:(mode)=>{battleMode=mode;if(mode==='cpu'){cpuRandomOpponent=false;screen='hero-select';render();}else window.alert(locale==='en'?'This multiplayer mode is reserved for a future slice.':'此多人模式已納入生命週期，將於後續 Slice 實作。');}});}
function drawHeroSelect(){prepareStage(root,app.screen.width,app.screen.height);renderHeroSelect(view(),{selectedHero:runtime.heroId(),onSelectHero,onStart:()=>{screen='cpu-match-setup';render();},onBack:()=>{screen='mode-select';render();}});}
function drawCpuSetup(){const match=runtime.snapshot();prepareStage(root,app.screen.width,app.screen.height);renderCpuMatchSetup(view(),{playerHeroId:runtime.heroId(),playerLoadout:match.loadout,cpuHeroId:runtime.cpuHeroId(),randomOpponent:cpuRandomOpponent,onBack:()=>{screen='hero-select';render();},onCpuHero:(id)=>{cpuRandomOpponent=false;runtime.selectCpuHero(id);render();},onRandom:()=>{cpuRandomOpponent=true;render();},onContinue:()=>{screen='battle-preview';render();}});}
function drawPreview(){prepareStage(root,app.screen.width,app.screen.height);renderBattlePreview(view(),{heroId:runtime.heroId(),cpuHeroId:runtime.cpuHeroId(),randomOpponent:cpuRandomOpponent,onBack:()=>{screen='cpu-match-setup';render();},onStart:startBattle});}
function drawMatch(){const ctx=view(),match=runtime.snapshot(),marks=feedback.state(),highlights=match.highlights;prepareStage(root,app.screen.width,app.screen.height);renderHudTop(ctx,{turn:match.turn.turn,cpuHero:match.cpuHero,cpuMana:match.cpuMana,history:match.actionHistory.slice(-3),onPause:()=>{paused=true;render();}});renderBoard(ctx,{state:match.state,highlights,feedback:marks,onCell:onCell});renderHudPanel(ctx,{hero:match.hero,mana:match.mana,status:match.status,manaPulse:marks.manaPulse>0,passivePulse:!!marks.passivePulse,passiveBanner:marks.passiveBanner});if(match.turn.status==='playing')renderSkillBar(ctx,{items:match.skillBar,onSelect:onSelectSkill});renderFooter(ctx);if(paused)renderPauseOverlay(ctx,{onResume:()=>{paused=false;render();},onRestart:()=>{paused=false;beginMatch();render();},onQuit:goHome});else if(match.turn.status!=='playing')renderResultOverlay(ctx,{result:match.turn.status,turns:match.turn.turn,onRematch:restart,onChangeHero:chooseHero,onHome:goHome});}
function render(){if(screen==='menu')drawMenu();else if(screen==='hero-collection')drawHeroCollection();else if(screen==='hero-detail')drawHeroDetail();else if(screen==='loadout')drawLoadout();else if(screen==='mode-select')drawModeSelect();else if(screen==='hero-select')drawHeroSelect();else if(screen==='cpu-match-setup')drawCpuSetup();else if(screen==='battle-preview')drawPreview();else drawMatch();}
function onSelectHero(heroId:HeroId){runtime.selectHero(heroId);render();}function onSelectSkill(skillId:SkillId){runtime.selectSkill(skillId);}function onCell(pos:Parameters<typeof runtime.tapCell>[0]){if(paused||runtime.snapshot().turn.status!=='playing')return;runtime.tapCell(pos);if(settings.haptics&&navigator.vibrate)navigator.vibrate(8);}function beginMatch(){matchStartedAt=new Date().toISOString();recordedOutcome=null;runtime.reset();paused=false;}function startBattle(){if(cpuRandomOpponent)runtime.randomizeCpuHero();beginMatch();screen='match';render();}function chooseHero(){runtime.reset();recordedOutcome=null;paused=false;cpuRandomOpponent=false;screen='hero-select';render();}function restart(){beginMatch();screen='match';render();}async function copySummary(){const text=summaryText(runtime.metrics());console.info('[Gomoku RPG playtest metrics]',text);}void copySummary;void battleMode;render();window.addEventListener('resize',render);
