import { Cell, Player, Pos } from './game';
import { CombatState, addCorruption, addFlame, addGuard, addSeal, isCorrupted, isGuarded, isSealed, samePos, spendMana } from './combat';
import type { HeroId } from './heroes';

export type SkillId='blink'|'guard'|'seal'|'corrupt'|'bulwark'|'charge'|'phase'|'rally'|'lattice';
/** @deprecated compatibility alias; use SkillAvailability. */
export type SkillOwnership='common'|'hero';
export type SkillAvailability={kind:'common'}|{kind:'hero-pool';heroIds:readonly HeroId[]};
export type SkillCategory='placement'|'protection'|'control'|'disruption'|'zone';
export type EffectTag='place'|'move'|'reposition'|'protection'|'guard'|'control'|'seal'|'force'|'disruption'|'push'|'remove'|'convert'|'zone'|'corruption'|'resource'|'refund'|'drain'|'information'|'pattern'|'setup'|'tempo';
export type RiskProfile='low'|'medium'|'high';
export type SkillTargetType='friendly-then-empty'|'friendly'|'empty'|'enemy-adjacent'|'friendly-then-adjacent';
export type SkillDescriptionKey='blinkHelp'|'guardHelp'|'sealHelp'|'corruptHelp'|'bulwarkHelp'|'chargeHelp'|'phaseHelp'|'rallyHelp'|'latticeHelp';
export type SkillContext={state:CombatState;player:Player};
export type SkillDefinition={
  id:SkillId;
  cost:number;
  consumesTurn:boolean;
  targetType:SkillTargetType;
  descriptionKey:SkillDescriptionKey;
  legalSources?:(context:SkillContext)=>Pos[];
  legalTargets:(context:SkillContext,source?:Pos)=>Pos[];
  execute:(context:SkillContext,target:Pos,source?:Pos)=>CombatState;
  availability:SkillAvailability;
  category:SkillCategory;
  effectTags:readonly EffectTag[];
  synergyTags:readonly EffectTag[];
  counterTags:readonly EffectTag[];
  riskProfile:RiskProfile;
  /** @deprecated compatibility alias while consumers migrate from ownership. */
  ownership:SkillOwnership;
};
function positions(board:Cell[][],predicate:(cell:Cell,pos:Pos)=>boolean):Pos[]{const out:Pos[]=[];board.forEach((row,r)=>row.forEach((cell,c)=>{const pos={row:r,col:c};if(predicate(cell,pos))out.push(pos);}));return out;}
const adjacent=(a:Pos,b:Pos)=>Math.max(Math.abs(a.row-b.row),Math.abs(a.col-b.col))===1;
const adjacentFriendly=(state:CombatState,pos:Pos,player:Player)=>positions(state.board,(cell,other)=>cell===player&&adjacent(pos,other));
const inside=(board:Cell[][],pos:Pos)=>pos.row>=0&&pos.row<board.length&&pos.col>=0&&pos.col<(board[0]?.length??0);
const blocked=(state:CombatState,pos:Pos)=>isSealed(state,pos)||isCorrupted(state,pos);
const orthogonal=([-1,0],[1,0],[0,-1],[0,1]) as never;
function chargeTargets(state:CombatState,source:Pos,player:Player):Pos[]{const enemy=player===1?2:1;const out:Pos[]=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const target={row:source.row+dr,col:source.col+dc};if(!inside(state.board,target)||blocked(state,target))continue;const cell=state.board[target.row][target.col];if(cell===0){out.push(target);continue;}if(cell!==enemy||isGuarded(state,target))continue;const pushed={row:target.row+dr,col:target.col+dc};if(inside(state.board,pushed)&&state.board[pushed.row][pushed.col]===0&&!blocked(state,pushed))out.push(target);}return out;}
function rallyTargets(state:CombatState,source:Pos,player:Player):Pos[]{return positions(state.board,(cell,target)=>cell===0&&!blocked(state,target)&&positions(state.board,(own,other)=>own===player&&!samePos(other,source)&&adjacent(target,other)).length>=2);}
const latticeCells=(state:CombatState,target:Pos)=>[[-1,0],[1,0],[0,-1],[0,1]].map(([dr,dc])=>({row:target.row+dr,col:target.col+dc})).filter((pos)=>inside(state.board,pos)&&state.board[pos.row][pos.col]===0&&!blocked(state,pos));
const heroPool=(...heroIds:HeroId[]):SkillAvailability=>({kind:'hero-pool',heroIds});
export const blinkSkill:SkillDefinition={id:'blink',ownership:'common',availability:{kind:'common'},category:'placement',effectTags:['move','reposition'],synergyTags:['tempo'],counterTags:['zone'],riskProfile:'medium',cost:2,consumesTurn:true,targetType:'friendly-then-empty',descriptionKey:'blinkHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)),legalTargets:({state},source)=>source?positions(state.board,(cell,pos)=>cell===0&&!isSealed(state,pos)&&!isCorrupted(state,pos)):[],execute:({state,player},target,source)=>{if(!source)return state;const board=state.board.map((row)=>[...row]);board[source.row][source.col]=0;board[target.row][target.col]=player;return spendMana({...state,board},player,2);}};
export const guardSkill:SkillDefinition={id:'guard',ownership:'hero',availability:heroPool('vanguard'),category:'protection',effectTags:['guard','protection'],synergyTags:['setup'],counterTags:['disruption'],riskProfile:'low',cost:2,consumesTurn:true,targetType:'friendly',descriptionKey:'guardHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)),execute:({state,player},target)=>spendMana(addGuard(state,target,player),player,2)};
export const sealSkill:SkillDefinition={id:'seal',ownership:'hero',availability:heroPool('arcanist'),category:'control',effectTags:['seal','control','zone'],synergyTags:['setup'],counterTags:['reposition'],riskProfile:'medium',cost:2,consumesTurn:true,targetType:'empty',descriptionKey:'sealHelp',legalTargets:({state})=>positions(state.board,(cell,pos)=>cell===0&&!isSealed(state,pos)&&!isCorrupted(state,pos)),execute:({state,player},target)=>spendMana(addSeal(state,target,player),player,2)};
export const corruptSkill:SkillDefinition={id:'corrupt',ownership:'hero',availability:heroPool('shade'),category:'disruption',effectTags:['remove','corruption','zone'],synergyTags:['resource'],counterTags:['protection'],riskProfile:'high',cost:3,consumesTurn:true,targetType:'enemy-adjacent',descriptionKey:'corruptHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell!==0&&cell!==player&&!isGuarded(state,pos)&&state.board.some((row,r)=>row.some((own,c)=>own===player&&adjacent(pos,{row:r,col:c})))),execute:({state,player},target)=>{const enemy=player===1?2:1;if(state.board[target.row]?.[target.col]!==enemy)return state;const board=state.board.map((row)=>[...row]);board[target.row][target.col]=0;return spendMana(addCorruption({...state,board},target,player),player,3);}};
export const bulwarkSkill:SkillDefinition={id:'bulwark',ownership:'hero',availability:heroPool('vanguard'),category:'protection',effectTags:['guard','protection'],synergyTags:['setup'],counterTags:['disruption'],riskProfile:'medium',cost:3,consumesTurn:true,targetType:'friendly',descriptionKey:'bulwarkHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&adjacentFriendly(state,pos,player).length>0),execute:({state,player},target)=>{if(state.board[target.row]?.[target.col]!==player)return state;const group=[target,...adjacentFriendly(state,target,player)];let next=state;for(const pos of group)next=addGuard(next,pos,player);return spendMana(next,player,3);}};
export const chargeSkill:SkillDefinition={id:'charge',ownership:'hero',availability:heroPool('vanguard'),category:'disruption',effectTags:['move','push','reposition'],synergyTags:['tempo'],counterTags:['protection'],riskProfile:'medium',cost:3,consumesTurn:true,targetType:'friendly-then-adjacent',descriptionKey:'chargeHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&chargeTargets(state,pos,player).length>0),legalTargets:({state,player},source)=>source?chargeTargets(state,source,player):[],execute:({state,player},target,source)=>{if(!source||!adjacent(source,target))return state;const legal=chargeTargets(state,source,player);if(!legal.some((p)=>samePos(p,target)))return state;const board=state.board.map((row)=>[...row]);const enemy=player===1?2:1,dr=target.row-source.row,dc=target.col-source.col;if(board[target.row][target.col]===enemy){const pushed={row:target.row+dr,col:target.col+dc};board[pushed.row][pushed.col]=enemy;}board[source.row][source.col]=0;board[target.row][target.col]=player;return spendMana({...state,board},player,3);}};
/** M2.4d Flame prototype. The legacy `phase` id is retained temporarily for telemetry compatibility. Flame places a stone, then blocks the four orthogonal empty neighbours for both players through the opponent's turn. */
export const phaseSkill:SkillDefinition={id:'phase',ownership:'hero',availability:heroPool('arcanist'),category:'zone',effectTags:['place','zone','seal'],synergyTags:['resource','setup'],counterTags:['reposition'],riskProfile:'high',cost:3,consumesTurn:true,targetType:'empty',descriptionKey:'phaseHelp',legalTargets:({state})=>positions(state.board,(cell,pos)=>cell===0&&!blocked(state,pos)),execute:({state,player},target)=>{if(state.board[target.row]?.[target.col]!==0||blocked(state,target))return state;const board=state.board.map((row)=>[...row]);board[target.row][target.col]=player;let next:CombatState={...state,board,forcedPlacements:state.forcedPlacements.filter((e)=>e.player!==player)};for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]] as const){const pos={row:target.row+dr,col:target.col+dc};if(inside(board,pos)&&board[pos.row][pos.col]===0&&!blocked(next,pos))next=addFlame(next,pos,player);}return spendMana(next,player,3);}};
/** Architect Rally: reposition an existing stone into an already-supported formation. */
export const rallySkill:SkillDefinition={id:'rally',ownership:'hero',availability:heroPool('architect'),category:'placement',effectTags:['move','reposition','pattern','setup'],synergyTags:['pattern','setup'],counterTags:['disruption'],riskProfile:'medium',cost:2,consumesTurn:true,targetType:'friendly-then-empty',descriptionKey:'rallyHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&rallyTargets(state,pos,player).length>0),legalTargets:({state,player},source)=>source?rallyTargets(state,source,player):[],execute:({state,player},target,source)=>{if(!source||!rallyTargets(state,source,player).some((p)=>samePos(p,target)))return state;const board=state.board.map((row)=>[...row]);board[source.row][source.col]=0;board[target.row][target.col]=player;return spendMana({...state,board},player,2);}};
/** Architect Lattice: spend a full turn converting one friendly anchor into short-lived local denial. */
export const latticeSkill:SkillDefinition={id:'lattice',ownership:'hero',availability:heroPool('architect'),category:'control',effectTags:['seal','control','zone','setup'],synergyTags:['pattern','setup'],counterTags:['reposition','disruption'],riskProfile:'high',cost:3,consumesTurn:true,targetType:'friendly',descriptionKey:'latticeHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&latticeCells(state,pos).length>0),execute:({state,player},target)=>{if(state.board[target.row]?.[target.col]!==player)return state;let next=state;for(const pos of latticeCells(next,target))next=addSeal(next,pos,player);return spendMana(next,player,3);}};
export const skills:Record<SkillId,SkillDefinition>={blink:blinkSkill,guard:guardSkill,seal:sealSkill,corrupt:corruptSkill,bulwark:bulwarkSkill,charge:chargeSkill,phase:phaseSkill,rally:rallySkill,lattice:latticeSkill};
export const commonSkillIds=Object.values(skills).filter((skill)=>skill.availability.kind==='common').map((skill)=>skill.id);
export function isLegalPosition(candidate:Pos,legal:Pos[]){return legal.some((pos)=>samePos(candidate,pos));}
