import { Cell, Player, Pos } from './game';
import { CombatState, addCorruption, addGuard, addSeal, isCorrupted, isGuarded, isSealed, samePos, spendMana } from './combat';

export type SkillId='blink'|'guard'|'seal'|'corrupt'|'bulwark'|'charge'|'phase';
export type SkillOwnership='common'|'hero';
export type SkillTargetType='friendly-then-empty'|'friendly'|'empty'|'enemy-adjacent'|'friendly-then-adjacent';
export type SkillContext={state:CombatState;player:Player};
export type SkillDefinition={id:SkillId;ownership:SkillOwnership;cost:number;consumesTurn:boolean;targetType:SkillTargetType;descriptionKey:'blinkHelp'|'guardHelp'|'sealHelp'|'corruptHelp'|'bulwarkHelp'|'chargeHelp'|'phaseHelp';legalSources?:(context:SkillContext)=>Pos[];legalTargets:(context:SkillContext,source?:Pos)=>Pos[];execute:(context:SkillContext,target:Pos,source?:Pos)=>CombatState};
function positions(board:Cell[][],predicate:(cell:Cell,pos:Pos)=>boolean):Pos[]{const out:Pos[]=[];board.forEach((row,r)=>row.forEach((cell,c)=>{const pos={row:r,col:c};if(predicate(cell,pos))out.push(pos);}));return out;}
const adjacent=(a:Pos,b:Pos)=>Math.max(Math.abs(a.row-b.row),Math.abs(a.col-b.col))===1;
const adjacentFriendly=(state:CombatState,pos:Pos,player:Player)=>positions(state.board,(cell,other)=>cell===player&&adjacent(pos,other));
const inside=(board:Cell[][],pos:Pos)=>pos.row>=0&&pos.row<board.length&&pos.col>=0&&pos.col<(board[0]?.length??0);
const blocked=(state:CombatState,pos:Pos)=>isSealed(state,pos)||isCorrupted(state,pos);
function chargeTargets(state:CombatState,source:Pos,player:Player):Pos[]{const enemy=player===1?2:1;const out:Pos[]=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const target={row:source.row+dr,col:source.col+dc};if(!inside(state.board,target)||blocked(state,target))continue;const cell=state.board[target.row][target.col];if(cell===0){out.push(target);continue;}if(cell!==enemy||isGuarded(state,target))continue;const pushed={row:target.row+dr,col:target.col+dc};if(inside(state.board,pushed)&&state.board[pushed.row][pushed.col]===0&&!blocked(state,pushed))out.push(target);}return out;}
export const blinkSkill:SkillDefinition={id:'blink',ownership:'common',cost:2,consumesTurn:true,targetType:'friendly-then-empty',descriptionKey:'blinkHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)),legalTargets:({state},source)=>source?positions(state.board,(cell,pos)=>cell===0&&!isSealed(state,pos)&&!isCorrupted(state,pos)):[],execute:({state,player},target,source)=>{if(!source)return state;const board=state.board.map((row)=>[...row]);board[source.row][source.col]=0;board[target.row][target.col]=player;return spendMana({...state,board},player,2);}};
export const guardSkill:SkillDefinition={id:'guard',ownership:'hero',cost:2,consumesTurn:true,targetType:'friendly',descriptionKey:'guardHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)),execute:({state,player},target)=>spendMana(addGuard(state,target,player),player,2)};
export const sealSkill:SkillDefinition={id:'seal',ownership:'hero',cost:2,consumesTurn:true,targetType:'empty',descriptionKey:'sealHelp',legalTargets:({state})=>positions(state.board,(cell,pos)=>cell===0&&!isSealed(state,pos)&&!isCorrupted(state,pos)),execute:({state,player},target)=>spendMana(addSeal(state,target,player),player,2)};
export const corruptSkill:SkillDefinition={id:'corrupt',ownership:'hero',cost:3,consumesTurn:true,targetType:'enemy-adjacent',descriptionKey:'corruptHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell!==0&&cell!==player&&!isGuarded(state,pos)&&state.board.some((row,r)=>row.some((own,c)=>own===player&&adjacent(pos,{row:r,col:c})))),execute:({state,player},target)=>{const enemy=player===1?2:1;if(state.board[target.row]?.[target.col]!==enemy)return state;const board=state.board.map((row)=>[...row]);board[target.row][target.col]=0;return spendMana(addCorruption({...state,board},target,player),player,3);}};
/** Deferred: Seal and Bulwark stay in the registry but are unequipped until the CPU can threaten structures. */
export const bulwarkSkill:SkillDefinition={id:'bulwark',ownership:'hero',cost:3,consumesTurn:true,targetType:'friendly',descriptionKey:'bulwarkHelp',legalTargets:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&adjacentFriendly(state,pos,player).length>0),execute:({state,player},target)=>{if(state.board[target.row]?.[target.col]!==player)return state;const group=[target,...adjacentFriendly(state,target,player)];let next=state;for(const pos of group)next=addGuard(next,pos,player);return spendMana(next,player,3);}};
/** Vanguard offense: advance one stone one step; an enemy on the destination is pushed one further step when legal. */
export const chargeSkill:SkillDefinition={id:'charge',ownership:'hero',cost:3,consumesTurn:true,targetType:'friendly-then-adjacent',descriptionKey:'chargeHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&chargeTargets(state,pos,player).length>0),legalTargets:({state,player},source)=>source?chargeTargets(state,source,player):[],execute:({state,player},target,source)=>{if(!source||!adjacent(source,target))return state;const legal=chargeTargets(state,source,player);if(!legal.some((p)=>samePos(p,target)))return state;const board=state.board.map((row)=>[...row]);const enemy=player===1?2:1,dr=target.row-source.row,dc=target.col-source.col;if(board[target.row][target.col]===enemy){const pushed={row:target.row+dr,col:target.col+dc};board[pushed.row][pushed.col]=enemy;}board[source.row][source.col]=0;board[target.row][target.col]=player;return spendMana({...state,board},player,3);}};
function phaseTargets(state:CombatState,source:Pos):Pos[]{const out:Pos[]=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){if(!dr&&!dc)continue;const target={row:source.row+dr,col:source.col+dc};if(!inside(state.board,target)||blocked(state,target))continue;if(state.board[target.row][target.col]===0)out.push(target);}return out;}
/** Arcanist control: reposition one stone, consume the turn, and leave its origin blocked through the opponent response. Flow refunds 1 Mana after resolution. */
export const phaseSkill:SkillDefinition={id:'phase',ownership:'hero',cost:2,consumesTurn:true,targetType:'friendly-then-adjacent',descriptionKey:'phaseHelp',legalSources:({state,player})=>positions(state.board,(cell,pos)=>cell===player&&!isGuarded(state,pos)&&phaseTargets(state,pos).length>0),legalTargets:({state},source)=>source?phaseTargets(state,source):[],execute:({state,player},target,source)=>{if(!source||!adjacent(source,target))return state;if(!phaseTargets(state,source).some((p)=>samePos(p,target)))return state;const board=state.board.map((row)=>[...row]);board[source.row][source.col]=0;board[target.row][target.col]=player;const shifted={...state,board};return spendMana(addSeal(shifted,source,player),player,2);}};
export const skills:Record<SkillId,SkillDefinition>={blink:blinkSkill,guard:guardSkill,seal:sealSkill,corrupt:corruptSkill,bulwark:bulwarkSkill,charge:chargeSkill,phase:phaseSkill};
export const commonSkillIds=Object.values(skills).filter((skill)=>skill.ownership==='common').map((skill)=>skill.id);
export function isLegalPosition(candidate:Pos,legal:Pos[]){return legal.some((pos)=>samePos(candidate,pos));}
