import type { HeroId } from './heroes';
import type { SkillId } from './skills';
export type MatchOutcome='playing'|'victory'|'defeat'|'draw';
export interface PlaytestMetrics {hero:HeroId;startedAt:number;endedAt:number|null;outcome:MatchOutcome;playerTurns:number;placements:number;patternMana:number;passiveMana:number;manaSpent:number;manaWasted:number;manaCappedTurns:number;passiveTriggers:number;skillUses:Record<SkillId,number>;skillOpportunities:Record<SkillId,number>;skillUseManaTotal:Record<SkillId,number>;peakMana:number;endingMana:number;}
export type MatchSummary=ReturnType<typeof summarizeMetrics>;export const HISTORY_STORAGE_KEY='gomoku-rpg.playtest-history.v1';
const emptySkillCounts=():Record<SkillId,number>=>({blink:0,guard:0,seal:0,corrupt:0,bulwark:0,charge:0,phase:0,rally:0,lattice:0});
export function createPlaytestMetrics(hero:HeroId,startingMana=0):PlaytestMetrics{return {hero,startedAt:Date.now(),endedAt:null,outcome:'playing',playerTurns:0,placements:0,patternMana:0,passiveMana:0,manaSpent:0,manaWasted:0,manaCappedTurns:0,passiveTriggers:0,skillUses:emptySkillCounts(),skillOpportunities:emptySkillCounts(),skillUseManaTotal:emptySkillCounts(),peakMana:startingMana,endingMana:startingMana};}
export function recordMana(metrics:PlaytestMetrics,mana:number){metrics.peakMana=Math.max(metrics.peakMana,mana);metrics.endingMana=mana;}
export function recordTurnStart(metrics:PlaytestMetrics,mana:number,maxMana=5){if(mana>=maxMana)metrics.manaCappedTurns++;}
export function recordManaWaste(metrics:PlaytestMetrics,attemptedGain:number,before:number,after:number){metrics.manaWasted+=Math.max(0,attemptedGain-(after-before));}
export function recordSkillOpportunities(metrics:PlaytestMetrics,skillIds:readonly SkillId[]){for(const skillId of skillIds)metrics.skillOpportunities[skillId]=(metrics.skillOpportunities[skillId]??0)+1;}
export function recordPlacement(metrics:PlaytestMetrics,patternMana:number,passiveTriggered:boolean,passiveMana:number,mana:number){metrics.playerTurns++;metrics.placements++;metrics.patternMana+=patternMana;metrics.passiveMana+=passiveMana;if(passiveTriggered)metrics.passiveTriggers++;recordMana(metrics,mana);}
export function recordSkill(metrics:PlaytestMetrics,skill:SkillId,cost:number,passiveTriggered:boolean,passiveMana:number,mana:number,manaBeforeUse=mana+cost-passiveMana){metrics.playerTurns++;metrics.skillUses[skill]=(metrics.skillUses[skill]??0)+1;metrics.skillUseManaTotal[skill]=(metrics.skillUseManaTotal[skill]??0)+manaBeforeUse;metrics.manaSpent+=cost;metrics.passiveMana+=passiveMana;if(passiveTriggered)metrics.passiveTriggers++;recordMana(metrics,mana);}
export function finishMetrics(metrics:PlaytestMetrics,outcome:Exclude<MatchOutcome,'playing'>,mana:number){if(metrics.outcome!=='playing')return;metrics.outcome=outcome;metrics.endedAt=Date.now();recordMana(metrics,mana);saveCompletedMatch(metrics);}
export function summarizeMetrics(metrics:PlaytestMetrics){const durationSeconds=Math.round(((metrics.endedAt??Date.now())-metrics.startedAt)/1000);const skillUsesTotal=Object.values(metrics.skillUses).reduce((sum,value)=>sum+value,0);const skillOpportunitiesTotal=Object.values(metrics.skillOpportunities).reduce((sum,value)=>sum+value,0);const skillUseRate=skillOpportunitiesTotal?Number((skillUsesTotal/skillOpportunitiesTotal).toFixed(3)):0;const averageManaAtSkillUse=Object.fromEntries(Object.keys(metrics.skillUses).map((id)=>{const skillId=id as SkillId;const uses=metrics.skillUses[skillId];return [skillId,uses?Number((metrics.skillUseManaTotal[skillId]/uses).toFixed(2)):0];})) as Record<SkillId,number>;const skillStats=Object.fromEntries(Object.keys(metrics.skillUses).map((id)=>{const skillId=id as SkillId;const uses=metrics.skillUses[skillId],opportunities=metrics.skillOpportunities[skillId];return [skillId,{uses,opportunities,useRate:opportunities?Number((uses/opportunities).toFixed(3)):0,averageManaAtUse:averageManaAtSkillUse[skillId]}];})) as Record<SkillId,{uses:number;opportunities:number;useRate:number;averageManaAtUse:number}>;return {version:3,hero:metrics.hero,outcome:metrics.outcome,durationSeconds,playerTurns:metrics.playerTurns,placements:metrics.placements,skillUsesTotal,skillUses:metrics.skillUses,skillOpportunitiesTotal,skillOpportunities:metrics.skillOpportunities,skillUseRate,skillStats,averageManaAtSkillUse,patternMana:metrics.patternMana,passiveMana:metrics.passiveMana,manaSpent:metrics.manaSpent,manaWasted:metrics.manaWasted,manaCappedTurns:metrics.manaCappedTurns,manaCappedTurnRate:metrics.playerTurns?Number((metrics.manaCappedTurns/metrics.playerTurns).toFixed(3)):0,unusedManaAtEnd:metrics.endingMana,passiveTriggers:metrics.passiveTriggers,passiveTriggerRate:metrics.playerTurns?Number((metrics.passiveTriggers/metrics.playerTurns).toFixed(3)):0,peakMana:metrics.peakMana,endingMana:metrics.endingMana};}
export function loadHistory():MatchSummary[]{try{const raw=localStorage.getItem(HISTORY_STORAGE_KEY);if(!raw)return [];const value=JSON.parse(raw);return Array.isArray(value)?value:[];}catch{return [];} }
export function saveCompletedMatch(metrics:PlaytestMetrics){if(metrics.outcome==='playing')return loadHistory();const history=loadHistory();history.push(summarizeMetrics(metrics));try{localStorage.setItem(HISTORY_STORAGE_KEY,JSON.stringify(history));}catch{}return history;}
export function clearHistory(){try{localStorage.removeItem(HISTORY_STORAGE_KEY);}catch{}}
export function exportHistory(){const matches=loadHistory();const heroCounts:Record<HeroId,number>={vanguard:0,arcanist:0,shade:0,architect:0};matches.forEach((match)=>heroCounts[match.hero]++);return {version:3,exportedAt:new Date().toISOString(),totalMatches:matches.length,heroCounts,matches};}
export function historyText(){return JSON.stringify(exportHistory(),null,2);}export function summaryText(_metrics:PlaytestMetrics){return historyText();}
