import { describe,expect,it } from 'vitest';
import { createCombatState,getMana,isSealed } from '../src/combat';
import { createBoard } from '../src/game';
import { createLoadout,heroes } from '../src/heroes';
import { latticeSkill,rallySkill } from '../src/skills';
import { resolvePlaceAction,resolveSkillAction } from '../src/runtime/action-resolution';
import { scoreCpuAction } from '../src/runtime/cpu-action-evaluator';
import { cpuActionCandidates } from '../src/runtime/cpu-runtime';

describe('Architect formation economy',()=>{
 it('defines setup/control identity with a conditional economy',()=>{expect(heroes.architect.signaturePassive).toBe('formation');expect(heroes.architect.abilityEconomy).toEqual({kind:'conditional'});expect(heroes.architect.defaultLoadout.skillIds).toEqual(['rally','lattice']);expect(createLoadout('architect',['blink','rally']).skillIds).toEqual(['blink','rally']);});
 it('Formation triggers when a placement connects at least two friendly stones without generating Mana',()=>{const board=createBoard();board[4][3]=1;board[3][4]=1;const result=resolvePlaceAction(createCombatState(board),'architect',1,{row:4,col:4});expect(result.ok).toBe(true);expect(result.passiveTriggered).toBe(true);expect(result.passiveMana).toBe(0);expect(result.manaGained).toBe(0);expect(getMana(result.state,1)).toBe(0);});
 it('does not trigger on an unsupported placement',()=>{const result=resolvePlaceAction(createCombatState(createBoard()),'architect',1,{row:4,col:4});expect(result.ok).toBe(true);expect(result.passiveTriggered).toBe(false);expect(getMana(result.state,1)).toBe(0);});
});

describe('Architect conditional abilities',()=>{
 it('Rally opens only when a movable stone can enter a cell supported by two other stones',()=>{const board=createBoard();board[0][0]=1;board[4][3]=1;board[3][4]=1;const source={row:0,col:0},target={row:4,col:4};const state=createCombatState(board,5);expect(rallySkill.legalTargets({state,player:1},source)).toContainEqual(target);const result=resolveSkillAction(state,'architect',1,'rally',target,source);expect(result.ok).toBe(true);expect(result.state.board[0][0]).toBe(0);expect(result.state.board[4][4]).toBe(1);expect(getMana(result.state,1)).toBe(5);expect(result.skillCost).toBe(0);});
 it('rejects Rally when no formation opportunity exists even with stored legacy Mana',()=>{const board=createBoard();board[0][0]=1;const result=resolveSkillAction(createCombatState(board,5),'architect',1,'rally',{row:1,col:1},{row:0,col:0});expect(result.ok).toBe(false);expect(result.error).toBe('ability-unavailable');});
 it('Lattice only targets a supported formation anchor and spends no Mana',()=>{const board=createBoard();board[4][4]=1;board[4][3]=1;board[3][4]=1;board[7][7]=1;const state=createCombatState(board,5);expect(latticeSkill.legalTargets({state,player:1})).toContainEqual({row:4,col:4});expect(latticeSkill.legalTargets({state,player:1})).not.toContainEqual({row:7,col:7});const result=resolveSkillAction(state,'architect',1,'lattice',{row:4,col:4});expect(result.ok).toBe(true);for(const pos of [{row:5,col:4},{row:4,col:5}])expect(isSealed(result.state,pos)).toBe(true);expect(getMana(result.state,1)).toBe(5);expect(result.skillCost).toBe(0);});
 it('closes the Lattice activation window immediately when the formation is broken',()=>{const board=createBoard();board[4][4]=1;board[4][3]=1;board[3][4]=1;let result=resolveSkillAction(createCombatState(board),'architect',1,'lattice',{row:4,col:4});expect(result.ok).toBe(true);board[3][4]=0;result=resolveSkillAction(createCombatState(board),'architect',1,'lattice',{row:4,col:4});expect(result.ok).toBe(false);expect(result.error).toBe('ability-unavailable');});
 it('exposes Architect skills to CPU only when their live formation conditions are satisfied',()=>{const ready=createBoard();ready[4][4]=2;ready[4][3]=2;ready[3][4]=2;ready[0][0]=2;const loadout=createLoadout('architect',['rally','lattice']);const candidates=cpuActionCandidates(createCombatState(ready),'architect',loadout,true);expect(candidates.some(a=>a.kind==='skill'&&a.skillId==='rally')).toBe(true);expect(candidates.some(a=>a.kind==='skill'&&a.skillId==='lattice')).toBe(true);expect(scoreCpuAction(createCombatState(ready),{kind:'skill',skillId:'lattice',target:{row:4,col:4}})).toBeGreaterThan(0);const emptyCandidates=cpuActionCandidates(createCombatState(createBoard()),'architect',loadout,true);expect(emptyCandidates.some(a=>a.kind==='skill')).toBe(false);});
});
