import { describe,expect,it } from 'vitest';
import { createBoard } from '../src/game';
import { createCombatState,getMana,isEcho,setMana } from '../src/combat';
import { cpuActionCandidates,resolveCpuTurn } from '../src/runtime/cpu-runtime';

describe('CPU Arcanist Phase Shift compatibility',()=>{
 it('only generates Phase candidates for Arcanist with at least 3 Mana',()=>{const board=createBoard();board[4][4]=2;const state=setMana(createCombatState(board),2,3);expect(cpuActionCandidates(state,'arcanist').some((a)=>a.kind==='skill'&&a.skillId==='phase')).toBe(true);expect(cpuActionCandidates(state,'vanguard').some((a)=>a.kind==='skill'&&a.skillId==='phase')).toBe(false);expect(cpuActionCandidates(state,'shade').some((a)=>a.kind==='skill')).toBe(false);});
 it('does not generate Phase below its redesigned Mana cost',()=>{const board=createBoard();board[4][4]=2;const state=setMana(createCombatState(board),2,2);expect(cpuActionCandidates(state,'arcanist').some((a)=>a.kind==='skill')).toBe(false);});
 it('can use Phase Shift to project a new threat while leaving an Echo',()=>{const board=createBoard();board[4][1]=2;board[4][2]=2;board[4][3]=2;board[5][4]=2;const state=setMana(createCombatState(board),2,3);const result=resolveCpuTurn(state,'arcanist');expect(result.action?.kind).toBe('skill');if(result.action?.kind==='skill'){expect(result.action.skillId).toBe('phase');const {source,target}=result.action;expect(source).toBeDefined();if(!source)throw new Error('Phase action requires a source');expect(state.board[source.row][source.col]).toBe(2);expect(state.board[target.row][target.col]).toBe(0);expect(result.state.board[source.row][source.col]).toBe(2);expect(result.state.board[target.row][target.col]).toBe(2);expect(isEcho(result.state,source)).toBe(true);expect(Math.max(Math.abs(source.row-target.row),Math.abs(source.col-target.col))).toBeLessThanOrEqual(2);}expect(result.passiveTriggered).toBe(true);expect(getMana(result.state,2)).toBe(1);});
 it('keeps Phase hero-specific instead of exposing it to Vanguard',()=>{const board=createBoard();board[4][1]=2;board[4][2]=2;board[4][3]=2;board[5][4]=2;const state=setMana(createCombatState(board),2,3);const result=resolveCpuTurn(state,'vanguard');if(result.action?.kind==='skill')expect(result.action.skillId).not.toBe('phase');});
});
