import { describe,expect,it } from 'vitest';
import { createBoard } from '../src/game';
import { createCombatState } from '../src/combat';
import { chooseCpuAction } from '../src/runtime/cpu-action-evaluator';
import { CPU_BASELINE_LEVEL,CPU_LEVEL_MAX,cpuDifficulty } from '../src/runtime/cpu-difficulty';

describe('M7 CPU difficulty foundation',()=>{
 it('keeps level 3 as the compatibility baseline',()=>{const p=cpuDifficulty();expect(p.level).toBe(CPU_BASELINE_LEVEL);expect(p.tier).toBe(1);expect(p.candidateWidth).toBeGreaterThanOrEqual(3);});
 it('supports and clamps the public level 1-100 range',()=>{expect(CPU_LEVEL_MAX).toBe(100);expect(cpuDifficulty(-5).level).toBe(1);expect(cpuDifficulty(999).level).toBe(100);expect(cpuDifficulty(100).tier).toBe(20);});
 it('advances five-level tiers deterministically',()=>{expect(cpuDifficulty(5).tier).toBe(1);expect(cpuDifficulty(6).tier).toBe(2);expect(cpuDifficulty(10).tier).toBe(2);expect(cpuDifficulty(11).tier).toBe(3);expect(cpuDifficulty(96).tier).toBe(20);});
 it('unlocks qualitative capabilities at ten-level milestones',()=>{expect(cpuDifficulty(9).capabilities).not.toContain('immediate-tactics');expect(cpuDifficulty(10).capabilities).toContain('immediate-tactics');expect(cpuDifficulty(20).capabilities).toContain('pattern-recognition');expect(cpuDifficulty(50).capabilities).toContain('skill-aware-search');expect(cpuDifficulty(80).capabilities).toContain('opponent-modeling');expect(cpuDifficulty(100).capabilities).toContain('boss-policy');});
 it('keeps core quality dimensions monotonic across all 100 levels',()=>{let previous=cpuDifficulty(1);for(let level=2;level<=100;level++){const current=cpuDifficulty(level);expect(current.candidateWidth).toBeGreaterThanOrEqual(previous.candidateWidth);expect(current.tacticalAccuracy).toBeGreaterThanOrEqual(previous.tacticalAccuracy);expect(current.evaluationQuality).toBeGreaterThanOrEqual(previous.evaluationQuality);expect(current.optimalMoveRate).toBeGreaterThanOrEqual(previous.optimalMoveRate);expect(current.blunderTolerance).toBeLessThanOrEqual(previous.blunderTolerance);expect(current.decisionNoise).toBeLessThanOrEqual(previous.decisionNoise);previous=current;}});
 it('exposes materially different milestone configurations',()=>{const l1=cpuDifficulty(1),l20=cpuDifficulty(20),l50=cpuDifficulty(50),l100=cpuDifficulty(100);expect(l20.candidateWidth).toBeGreaterThan(l1.candidateWidth);expect(l50.skillPlanningDepth).toBeGreaterThan(l20.skillPlanningDepth);expect(l100.searchDepth).toBeGreaterThan(l50.searchDepth);expect(l100.opponentModeling).toBeGreaterThan(l50.opponentModeling);expect(l100.optimalMoveRate).toBe(1);expect(l100.decisionNoise).toBe(0);});
 it('never randomizes away an immediate win through the blunder gate',()=>{const board=createBoard();board[4][1]=2;board[4][2]=2;board[4][3]=2;board[4][4]=2;const state=createCombatState(board),win={kind:'place',at:{row:4,col:5}} as const,quiet={kind:'place',at:{row:0,col:0}} as const;const picked=chooseCpuAction(state,[quiet,win],cpuDifficulty(1),()=>.99);expect(picked?.action).toEqual(win);expect(picked?.regret).toBe(0);});
 it('reports decision regret as telemetry-ready metadata',()=>{const state=createCombatState(createBoard()),center={kind:'place',at:{row:4,col:4}} as const,corner={kind:'place',at:{row:0,col:0}} as const;const profile={...cpuDifficulty(1),optimalMoveRate:0,blunderTolerance:1,candidateWidth:2};const picked=chooseCpuAction(state,[center,corner],profile,()=>.99);expect(picked?.bestScore).toBeGreaterThanOrEqual(picked?.score??0);expect(picked?.regret).toBe((picked?.bestScore??0)-(picked?.score??0));});
});
