import { Container, Graphics, Text } from 'pixi.js';
import { CameraController } from './CameraController';
import { createAttackState, HIT_STOP, isAttackActive, overlaps, playerAttackHitbox, startAttack, stepAttack } from './combat';
import { ControlDeck } from './ControlDeck';
import { Encounter } from './Encounter';
import { InputState } from './InputState';
import { GAMEPLAY_HEIGHT, LOGICAL_WIDTH } from './layout';
import { createPlayerMotion, stepPlayer, type Rect } from './movement';
import { createPlayerCombatState, damagePlayer, PLAYER_HURT_KNOCKBACK, playerHurtbox, resetPlayerCombat, stepPlayerCombat } from './PlayerCombat';
const WORLD_WIDTH=1380,WORLD_HEIGHT=760,HIT_SHAKE_DURATION=.075,HIT_SHAKE_STRENGTH=2;const PLATFORMS:Rect[]=[{x:0,y:500,width:330,height:80},{x:330,y:472,width:130,height:108},{x:485,y:430,width:150,height:150},{x:675,y:500,width:235,height:80},{x:940,y:455,width:145,height:125},{x:1120,y:405,width:260,height:175}];
export class GameShell extends Container{
readonly input=new InputState();private readonly world=new Container();private readonly player=new Container();private readonly attackFx=new Graphics();private readonly impactLayer=new Container();private readonly trailLayer=new Container();private readonly camera=new CameraController();private encounter=new Encounter();private motion=createPlayerMotion();private readonly attack=createAttackState();private readonly playerCombat=createPlayerCombatState();private dashWasPressed=false;private attackWasPressed=false;private trailTimer=0;private hitStop=0;private shakeTime=0;private readonly hpText=new Text({text:'',style:{fill:0x3e3c35,fontSize:14,letterSpacing:2}});private readonly status=new Text({text:'',style:{fill:0x3e3c35,fontSize:13,align:'center'}});private readonly bossBar=new Graphics();private readonly bossName=new Text({text:'墨守',style:{fill:0x3e3c35,fontSize:12}});
constructor(){super();const mask=new Graphics().rect(0,0,LOGICAL_WIDTH,GAMEPLAY_HEIGHT).fill(0xffffff);this.addChild(this.world,mask);this.world.mask=mask;this.drawWorld();this.world.addChild(this.trailLayer,this.encounter);this.drawPlayer();this.world.addChild(this.attackFx,this.impactLayer);this.drawHud();this.addChild(new ControlDeck(this.input));}
update(deltaSeconds:number){const dt=Math.min(deltaSeconds,1/30);this.updateImpactFx(dt);stepPlayerCombat(this.playerCombat,dt);this.player.alpha=this.playerCombat.invulnerability>0&&Math.floor(this.playerCombat.invulnerability*16)%2===0?.35:1;const input=this.input.snapshot(),dashPressed=input.dash&&!this.dashWasPressed,attackPressed=input.attack&&!this.attackWasPressed;this.dashWasPressed=input.dash;this.attackWasPressed=input.attack;if(this.playerCombat.dead){this.status.text='墨散於地\n按「斬」重新凝聚';if(attackPressed)this.restart();this.applyCameraPosition();return;}if(this.hitStop>0){this.hitStop=Math.max(0,this.hitStop-dt);this.applyCameraPosition();return;}if(attackPressed)startAttack(this.attack);stepAttack(this.attack,dt);stepPlayer(this.motion,input.moveX,dashPressed,dt,PLATFORMS);this.encounter.update(this.motion.x,this.motion.y,dt);this.resolveAttack();this.resolvePlayerDamage();this.camera.update(this.motion.x,this.motion.y,this.motion.facing,dt);this.player.position.set(this.motion.x,this.motion.y-25);this.player.scale.x=this.motion.facing;this.applyCameraPosition();this.drawAttackFx();this.hpText.text=Array.from({length:5},(_,i)=>i<this.playerCombat.hp?'●':'○').join(' ');this.status.text=this.encounter.cleared?'墨守已破':'';this.drawBossHud();if(this.motion.dashTime>0){this.trailTimer-=dt;if(this.trailTimer<=0){this.spawnInkTrail();this.trailTimer=.035;}}else this.trailTimer=0;for(const child of[...this.trailLayer.children]){child.alpha-=dt*2.8;child.scale.x+=dt*.45;if(child.alpha<=0)child.destroy();}}
private resolvePlayerDamage(){if(this.motion.dashTime>0)return;const source=this.encounter.damageSource(playerHurtbox(this.motion.x,this.motion.y));if(!source||!damagePlayer(this.playerCombat))return;this.motion.vx=(this.motion.x<source.x?-1:1)*PLAYER_HURT_KNOCKBACK;this.motion.vy=-145;this.motion.grounded=false;this.hitStop=.04;}
private resolveAttack(){if(!isAttackActive(this.attack))return;const hitbox=playerAttackHitbox(this.motion.x,this.motion.y,this.motion.facing);for(const enemy of this.encounter.combatants){if(enemy.hp<=0||this.attack.hitIds.has(enemy.enemyId)||!overlaps(hitbox,enemy.hurtbox()))continue;this.attack.hitIds.add(enemy.enemyId);enemy.hit(this.motion.facing);this.hitStop=HIT_STOP;this.shakeTime=HIT_SHAKE_DURATION;const p=enemy.impactPoint();this.spawnImpact(p.x,p.y);}}
private drawBossHud(){this.bossBar.clear();this.bossName.visible=this.encounter.bossStarted&&!this.encounter.cleared;if(!this.bossName.visible)return;const ratio=this.encounter.bossHp/this.encounter.bossMaxHp;this.bossBar.rect(88,62,244,7).fill({color:0xaaa69b,alpha:.45});this.bossBar.rect(88,62,244*ratio,7).fill({color:0x302f2a,alpha:.9});}
private restart(){this.world.removeChild(this.encounter);this.encounter.destroy({children:true});this.encounter=new Encounter();this.world.addChildAt(this.encounter,this.world.getChildIndex(this.player));this.motion=createPlayerMotion();resetPlayerCombat(this.playerCombat);this.status.text='';this.hpText.text='● ● ● ● ●';this.drawBossHud();}
private applyCameraPosition(){const s=this.shakeTime>0?HIT_SHAKE_STRENGTH*(this.shakeTime/HIT_SHAKE_DURATION):0;this.world.position.set(-this.camera.x+(s?(Math.random()*2-1)*s:0),-this.camera.y+(s?(Math.random()*2-1)*s*.4:0));}
private spawnImpact(x:number,y:number){const b=new Graphics().circle(0,0,7).stroke({color:0x171714,width:5,alpha:.9});for(let i=0;i<6;i++){const a=Math.PI*2*i/6;b.moveTo(Math.cos(a)*8,Math.sin(a)*8).lineTo(Math.cos(a)*25,Math.sin(a)*25).stroke({color:0x171714,width:3,alpha:.75});}b.position.set(x,y);this.impactLayer.addChild(b);}
private updateImpactFx(dt:number){this.shakeTime=Math.max(0,this.shakeTime-dt);for(const c of[...this.impactLayer.children]){c.alpha-=dt*5.5;c.scale.set(c.scale.x+dt*2.2);if(c.alpha<=0)c.destroy();}}
private drawAttackFx(){this.attackFx.clear();if(!isAttackActive(this.attack))return;const x=this.motion.x+this.motion.facing*34,y=this.motion.y-27;this.attackFx.arc(x,y,38,this.motion.facing>0?-1.05:2.1,this.motion.facing>0?1.05:4.18).stroke({color:0x171714,width:8,alpha:.82});}
private drawWorld(){this.world.addChild(new Graphics().rect(0,0,WORLD_WIDTH,WORLD_HEIGHT).fill(0xe9e4d8));const m=new Graphics();for(let x=-100;x<WORLD_WIDTH+200;x+=280)m.moveTo(x,390).bezierCurveTo(x+80,300,x+135,335,x+210,265).bezierCurveTo(x+270,340,x+320,330,x+380,395).lineTo(x+380,560).lineTo(x,560).fill({color:0x77756c,alpha:.10});this.world.addChild(m);for(let i=0;i<29;i++){const x=28+i*49;this.world.addChild(new Graphics().moveTo(x,75+i%4*19).lineTo(x-18,525).stroke({color:0x65645b,width:i%3===0?4:2,alpha:.17}));}for(const p of PLATFORMS){const r=new Graphics().moveTo(p.x,p.y).lineTo(p.x+p.width,p.y).lineTo(p.x+p.width-18,p.y+p.height).lineTo(p.x+12,p.y+p.height).closePath().fill({color:0x36362f,alpha:.76});r.moveTo(p.x,p.y).lineTo(p.x+p.width,p.y).stroke({color:0x171714,width:4,alpha:.75});this.world.addChild(r);}}
private drawHud(){this.hpText.text='● ● ● ● ●';this.hpText.position.set(14,14);const ink=new Text({text:'墨  ◐ ◐ ◐',style:{fill:0x3e3c35,fontSize:14}});ink.position.set(286,14);this.status.anchor.set(.5,0);this.status.position.set(LOGICAL_WIDTH/2,42);this.bossName.position.set(48,57);this.addChild(this.hpText,ink,this.status,this.bossName,this.bossBar);this.drawBossHud();}
private drawPlayer(){const shadow=new Graphics().ellipse(0,27,19,5).fill({color:0x111111,alpha:.18}),body=new Graphics().moveTo(-11,24).quadraticCurveTo(-15,-10,0,-28).quadraticCurveTo(15,-10,11,24).closePath().fill(0x24231f),scarf=new Graphics().moveTo(-4,-14).bezierCurveTo(-29,-24,-29,-2,-45,2).stroke({color:0x444139,width:4,alpha:.8});this.player.addChild(shadow,scarf,body);this.world.addChild(this.player);}
private spawnInkTrail(){const mark=new Graphics().ellipse(0,0,15,24).fill({color:0x24231f,alpha:.28});mark.position.set(this.motion.x-this.motion.facing*12,this.motion.y-25);mark.scale.x=this.motion.facing;this.trailLayer.addChild(mark);}}
