import { Graphics } from 'pixi.js';
import { BOARD_SIZE, Pos } from '../game';
import { CombatState, isEcho, isFlamed, isGuarded, isSealed, samePos } from '../combat';
import { TargetingHighlights } from '../runtime/targeting';
import { ViewContext, card, diamond, edge, gold, line, violet } from './theme';
import { BOARD_PAD, BOARD_SPAN, BOARD_X, BOARD_Y, BoardFeedback, cellX, cellY } from './board-layout';
export type { BoardFeedback } from './board-layout';export { BOARD_PAD, BOARD_SPAN, BOARD_X, BOARD_Y, cellX, cellY } from './board-layout';
export interface BoardViewProps{state:CombatState;highlights:TargetingHighlights;feedback:BoardFeedback;onCell:(pos:Pos)=>void}
const marks=(list:Pos[],pos:Pos)=>list.some((p)=>samePos(p,pos));
export function crystalArmor(x:number,y:number,active=false){const g=new Graphics();const outer=active?23:20,inner=active?15:14;diamond(g,x,y,outer,gold,false);diamond(g,x,y,inner,gold,false);const shard=(cx:number,cy:number,dx:number,dy:number)=>{g.moveTo(cx,cy).lineTo(cx+dx*7,cy+dy*7).lineTo(cx+dx*3-dy*4,cy+dy*3+dx*4).closePath().fill({color:gold,alpha:active?.72:.42});};shard(x,y-outer+2,0,-1);shard(x+outer-2,y,1,0);shard(x,y+outer-2,0,1);shard(x-outer+2,y,-1,0);g.circle(x,y,outer+3).stroke({color:gold,width:1,alpha:active?.38:.16});return g;}
function renderGrid({root}:ViewContext){root.addChild(new Graphics().roundRect(BOARD_X,BOARD_Y,BOARD_SPAN,BOARD_SPAN,8).fill(card).stroke({color:edge,width:1}));const grid=new Graphics();for(let i=0;i<BOARD_SIZE;i++){const x=cellX(i);grid.moveTo(x,BOARD_Y+BOARD_PAD).lineTo(x,BOARD_Y+BOARD_SPAN-BOARD_PAD);const y=cellY(i);grid.moveTo(BOARD_X+BOARD_PAD,y).lineTo(BOARD_X+BOARD_SPAN-BOARD_PAD,y);}grid.stroke({color:line,width:1});root.addChild(grid);}
function renderSkillTrail(ctx:ViewContext,feedback:BoardFeedback){if(!feedback.skillTrail)return;const {source,target}=feedback.skillTrail,sx=cellX(source.col),sy=cellY(source.row),tx=cellX(target.col),ty=cellY(target.row);const g=new Graphics();g.moveTo(sx,sy).lineTo(tx,ty).stroke({color:violet,width:4,alpha:.7});const angle=Math.atan2(ty-sy,tx-sx),size=9;g.moveTo(tx,ty).lineTo(tx-Math.cos(angle-.55)*size,ty-Math.sin(angle-.55)*size).lineTo(tx-Math.cos(angle+.55)*size,ty-Math.sin(angle+.55)*size).closePath().fill({color:violet,alpha:.85});ctx.root.addChild(g);}
function renderEcho(x:number,y:number,cell:1|2){const g=new Graphics();g.circle(x,y,14).fill({color:cell===1?0xfbf9f4:0x29282c,alpha:.18}).stroke({color:violet,width:2,alpha:.9});g.circle(x,y,9).stroke({color:violet,width:1,alpha:.45});diamond(g,x,y,4,violet,false);return g;}
function renderFlame(x:number,y:number){const g=new Graphics();g.circle(x,y,15).fill({color:0xff6a2a,alpha:.16}).stroke({color:0xff6a2a,width:2,alpha:.8});g.moveTo(x,y+8).bezierCurveTo(x-10,y+1,x-3,y-9,x+1,y-14).bezierCurveTo(x+2,y-7,x+10,y-4,x+6,y+5).bezierCurveTo(x+4,y+10,x-2,y+12,x,y+8).fill({color:0xff8a32,alpha:.8});return g;}
export function renderBoard(ctx:ViewContext,{state,highlights,feedback,onCell}:BoardViewProps){const {root}=ctx;renderGrid(ctx);state.board.forEach((row,r)=>row.forEach((cell,c)=>{const x=cellX(c),y=cellY(r),pos={row:r,col:c};if(marks(feedback.winCells,pos))root.addChild(new Graphics().circle(x,y,18).fill({color:gold,alpha:.22}).stroke({color:gold,width:2}));if(isFlamed(state,pos))root.addChild(renderFlame(x,y));else if(isSealed(state,pos)){const g=new Graphics();diamond(g,x,y,11,violet,false);g.moveTo(x-7,y).lineTo(x+7,y).stroke({color:violet,width:2});root.addChild(g);}if(marks(highlights.sources,pos)||marks(highlights.targets,pos))root.addChild(new Graphics().circle(x,y,16).fill({color:gold,alpha:.16}).stroke({color:gold,width:1}));if(cell){if(isEcho(state,pos))root.addChild(renderEcho(x,y,cell));else{if(isGuarded(state,pos))root.addChild(crystalArmor(x,y,!!feedback.passivePulse&&samePos(feedback.passivePulse,pos)));const stone=new Graphics().circle(x,y,12).fill(cell===1?0xfbf9f4:0x29282c).stroke({color:cell===1?0xd8d1c7:0x111116,width:1});diamond(stone,x,y,3,gold);root.addChild(stone);}}if(feedback.lastMove&&samePos(feedback.lastMove,pos))root.addChild(new Graphics().circle(x,y,15).stroke({color:cell===1?gold:violet,width:1,alpha:.75}));if(feedback.actionPulse&&samePos(feedback.actionPulse,pos))root.addChild(new Graphics().circle(x,y,21).stroke({color:gold,width:2,alpha:.8}));if(feedback.passivePulse&&samePos(feedback.passivePulse,pos))root.addChild(new Graphics().circle(x,y,29).stroke({color:gold,width:2,alpha:.55}));if(feedback.flash&&samePos(feedback.flash,pos))root.addChild(new Graphics().circle(x,y,19).stroke({color:violet,width:2}));const hit=new Graphics().circle(x,y,17).fill({color:0xffffff,alpha:.001});hit.eventMode='static';hit.cursor='pointer';hit.on('pointertap',()=>onCell(pos));root.addChild(hit);}));renderSkillTrail(ctx,feedback);}
