import { Container,Graphics,Text } from 'pixi.js';
import { HeroId,HeroLoadout,heroes,heroIds } from '../heroes';
import { getMessages } from '../i18n';
import { ViewContext } from './theme';

const ink=0x252431,paper=0xf8f4ec,purple=0x7650b6,gold=0xc9a354,line=0xd7ccba,muted=0x77716b;
const passiveName={fortified:'Guard / Fortified',flow:'Flow',pressure:'Pressure'} as const;
const skillName:Record<string,string>={blink:'Blink',charge:'Charge',phase:'Flame',corrupt:'Corrupt'};
const roleName={defense:'防禦',control:'控制',disruption:'干擾'} as const;
function text(value:string,size:number,color=ink){return new Text({text:value,style:{fontFamily:'Georgia, serif',fontSize:size,fill:color,fontWeight:'600'}})}
function tap(parent:Container,x:number,y:number,w:number,h:number,onTap:()=>void,active=false){const g=new Graphics().roundRect(x,y,w,h,7).fill(active?0xeee5fa:paper).stroke({color:active?purple:line,width:active?2:1});g.eventMode='static';g.cursor='pointer';g.on('pointertap',onTap);parent.addChild(g);return g;}
function header(ctx:ViewContext,title:string,onBack:()=>void){const back=text('‹',32);back.position.set(24,55);back.eventMode='static';back.cursor='pointer';back.on('pointertap',onBack);ctx.root.addChild(back);const heading=text(title,24);heading.position.set(62,62);ctx.root.addChild(heading);}

export function renderHeroCollection(ctx:ViewContext,opts:{onBack:()=>void;onHero:(id:HeroId)=>void}){const {root}=ctx,w=window.innerWidth,m=getMessages(ctx.locale);header(ctx,ctx.locale==='en'?'Heroes':'英雄',opts.onBack);const intro=text(ctx.locale==='en'?'Manage owned heroes, passives and battle loadouts.':'查看與管理目前持有英雄、被動與技能編組。',12,muted);intro.position.set(24,105);root.addChild(intro);heroIds.forEach((id,i)=>{const hero=heroes[id],y=145+i*126;tap(root,24,y,w-48,108,()=>opts.onHero(id));const badge=new Graphics().circle(62,y+54,27).fill(id==='vanguard'?0xc9a354:id==='arcanist'?purple:0x4e5567);root.addChild(badge);const initial=text(m[hero.nameKey].slice(0,1),18,0xffffff);initial.anchor.set(.5);initial.position.set(62,y+54);root.addChild(initial);const name=text(m[hero.nameKey],19);name.position.set(104,y+18);root.addChild(name);const meta=text(`${ctx.locale==='en'?hero.role:roleName[hero.role]} · Tier ${hero.tier}`,11,muted);meta.position.set(104,y+47);root.addChild(meta);const kit=text(`${passiveName[hero.innatePassive]}  •  ${hero.defaultLoadout.skills.map(s=>skillName[s]??s).join(' / ')}`,11,purple);kit.position.set(104,y+72);root.addChild(kit);const arrow=text('›',25,gold);arrow.anchor.set(1,.5);arrow.position.set(w-42,y+54);root.addChild(arrow);});}

export function renderHeroDetail(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;onBack:()=>void;onManageLoadout:()=>void}){const {root}=ctx,w=window.innerWidth,m=getMessages(ctx.locale),hero=heroes[opts.heroId];header(ctx,m[hero.nameKey],opts.onBack);const emblem=new Graphics().poly([w/2,126,w/2+43,184,w/2,242,w/2-43,184]).fill({color:purple,alpha:.88}).stroke({color:gold,width:2});root.addChild(emblem);const tier=text(`TIER ${hero.tier} · ${ctx.locale==='en'?hero.role:roleName[hero.role]}`,12,gold);tier.anchor.set(.5);tier.position.set(w/2,266);root.addChild(tier);const section=(title:string,y:number)=>{const t=text(title,14,muted);t.position.set(28,y);root.addChild(t);};section(ctx.locale==='en'?'PASSIVE':'被動',310);tap(root,28,338,w-56,66,()=>{});const p=text(passiveName[opts.loadout.passive],16);p.position.set(46,360);root.addChild(p);section(ctx.locale==='en'?'EQUIPPED SKILLS':'已裝備技能',430);opts.loadout.skills.forEach((skill,i)=>{tap(root,28+i*((w-68)/2),458,(w-76)/2,72,()=>{});const s=text(skillName[skill]??skill,15);s.anchor.set(.5);s.position.set(28+i*((w-68)/2)+(w-76)/4,494);root.addChild(s);});tap(root,28,560,w-56,58,opts.onManageLoadout,true);const manage=text(ctx.locale==='en'?'MANAGE LOADOUT':'管理技能編組',16,purple);manage.anchor.set(.5);manage.position.set(w/2,589);root.addChild(manage);const future=text(ctx.locale==='en'?'Advanced classes will branch from this hero in a future progression slice.':'衍生職業將於後續成長系統從此英雄向下分支。',11,muted);future.anchor.set(.5);future.position.set(w/2,654);root.addChild(future);}

export function renderLoadoutManagement(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;onBack:()=>void}){const {root}=ctx,w=window.innerWidth,m=getMessages(ctx.locale),hero=heroes[opts.heroId];header(ctx,ctx.locale==='en'?'Loadout':'技能編組',opts.onBack);const title=text(m[hero.nameKey],20);title.position.set(28,116);root.addChild(title);const note=text(ctx.locale==='en'?'M6.2 establishes the loadout domain. Slots are read-only until the skill-pool/equipment rules are expanded.':'M6.2 先建立獨立編組模型；技能池與裝備規則擴充前，欄位先以檢視為主。',11,muted);note.style.wordWrap=true;note.style.wordWrapWidth=w-56;note.position.set(28,150);root.addChild(note);[['被動',passiveName[opts.loadout.passive]],['共通技能',opts.loadout.commonSkill?skillName[opts.loadout.commonSkill]:'—'],['職業技能',opts.loadout.heroSkills.map(s=>skillName[s]??s).join(' / ')]].forEach(([label,value],i)=>{const y=220+i*96;const l=text(label,12,muted);l.position.set(28,y);root.addChild(l);tap(root,28,y+26,w-56,56,()=>{});const v=text(value,16);v.position.set(46,y+44);root.addChild(v);});const pool=text(`Skill Pool  ·  ${hero.skillPool.map(s=>skillName[s]??s).join(' / ')}`,12,purple);pool.position.set(28,532);root.addChild(pool);}
