import { Graphics } from 'pixi.js';
import { HeroId,HeroLoadout,heroes,heroIds } from '../heroes';
import { SkillId,skills } from '../skills';
import { getMessages } from '../i18n';
import { ViewContext } from './theme';
import { actionButton,pageHeader,surface,uiText } from './design/components';
import { canvas,color,layout,type } from './design/tokens';

const passiveName={fortified:'Guard / Fortified',flow:'Flow',pressure:'Pressure'} as const;
const skillName:Record<SkillId,string>={blink:'Blink',guard:'Guard',seal:'Seal',corrupt:'Corrupt',bulwark:'Bulwark',charge:'Charge',phase:'Flame'};
const roleName={defense:'防禦',control:'控制',disruption:'干擾'} as const;
const heroColor:Record<HeroId,number>={vanguard:color.gold,arcanist:color.violet,shade:color.panelSoft};
function centered(ctx:ViewContext,value:string,y:number,size:number=type.body,fill:number=color.ink,weight='600'){const t=uiText(ctx.root,ctx.locale,value,0,y,size,fill,weight);t.anchor.set(.5,0);t.x=canvas.centerX;return t;}
function tappableCard(ctx:ViewContext,x:number,y:number,w:number,h:number,onTap:()=>void){const g=surface(ctx.root,x,y,w,h,true);g.eventMode='static';g.cursor='pointer';g.on('pointertap',onTap);return g;}
function emblem(ctx:ViewContext,id:HeroId,x:number,y:number,r:number){const g=new Graphics().poly([x,y-r,x+r,y,x,y+r,x-r,y]).fill({color:heroColor[id],alpha:.92}).stroke({color:color.goldSoft,width:1});ctx.root.addChild(g);return g;}
function skillLabel(skillId:SkillId){return skillName[skillId]??skillId;}

export function renderHeroCollection(ctx:ViewContext,opts:{onBack:()=>void;onHero:(id:HeroId)=>void}){const {root}=ctx,m=getMessages(ctx.locale);pageHeader(root,ctx.locale,ctx.locale==='en'?'Heroes':'英雄',opts.onBack);centered(ctx,ctx.locale==='en'?'HERO ARCHIVE':'英雄檔案',82,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'Manage your roster and battle kits':'管理持有英雄、被動與出戰技能組',105,12,color.inkSoft);heroIds.forEach((id,i)=>{const hero=heroes[id],y=150+i*154;tappableCard(ctx,layout.pagePad,y,canvas.width-layout.pagePad*2,132,()=>opts.onHero(id));emblem(ctx,id,67,y+52,28);uiText(root,ctx.locale,m[hero.nameKey],108,y+20,19,color.ink,'700');uiText(root,ctx.locale,`${ctx.locale==='en'?hero.role:roleName[hero.role]} · TIER ${hero.tier}`,108,y+48,type.caption,color.gold,'700');uiText(root,ctx.locale,passiveName[hero.signaturePassive],108,y+76,12,color.violet,'700');uiText(root,ctx.locale,hero.defaultLoadout.skillIds.map(skillLabel).join('  ·  '),108,y+98,type.caption,color.inkSoft);const arrow=uiText(root,ctx.locale,'›',0,y+47,28,color.gold);arrow.anchor.set(1,0);arrow.x=canvas.width-38;});centered(ctx,ctx.locale==='en'?'Advanced paths will branch from base heroes':'未來衍生職業將由基礎英雄向下分支',650,type.caption,color.muted);}

export function renderHeroDetail(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;onBack:()=>void;onManageLoadout:()=>void}){const {root}=ctx,m=getMessages(ctx.locale),hero=heroes[opts.heroId];pageHeader(root,ctx.locale,m[hero.nameKey],opts.onBack);emblem(ctx,opts.heroId,canvas.centerX,155,48);centered(ctx,`TIER ${hero.tier} · ${ctx.locale==='en'?hero.role.toUpperCase():roleName[hero.role]}`,220,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'CURRENT BATTLE KIT':'目前出戰編組',258,type.caption,color.muted,'700');surface(root,layout.pagePad,286,canvas.width-layout.pagePad*2,88,true);uiText(root,ctx.locale,ctx.locale==='en'?'SIGNATURE PASSIVE':'英雄被動',40,302,type.caption,color.muted,'700');uiText(root,ctx.locale,passiveName[hero.signaturePassive],40,329,18,color.ink,'700');surface(root,layout.pagePad,390,canvas.width-layout.pagePad*2,138,true);uiText(root,ctx.locale,ctx.locale==='en'?'EQUIPPED SKILLS':'已裝備技能',40,406,type.caption,color.muted,'700');opts.loadout.skillIds.forEach((skill,i)=>{const x=40+i*158;const g=new Graphics().roundRect(x,443,146,62,8).fill(color.paper).stroke({color:color.edge,width:1});root.addChild(g);const t=uiText(root,ctx.locale,skillLabel(skill),0,462,type.label,color.violet,'700');t.anchor.set(.5,0);t.x=x+73;});actionButton(root,ctx.locale,layout.pagePad,556,canvas.width-layout.pagePad*2,58,ctx.locale==='en'?'MANAGE LOADOUT':'管理技能編組',opts.onManageLoadout,true);centered(ctx,ctx.locale==='en'?'CLASS PATH':'職業分支',652,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'Advanced classes reserved for a future progression slice':'二～三階衍生職業將於後續成長系統開放',678,type.caption,color.muted);}

export function renderLoadoutManagement(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;editingSlot:0|1;onSlot:(slot:0|1)=>void;onSkill:(skillId:SkillId)=>void;onReset:()=>void;onBack:()=>void}){const {root}=ctx,m=getMessages(ctx.locale),hero=heroes[opts.heroId];pageHeader(root,ctx.locale,ctx.locale==='en'?'Loadout':'技能編組',opts.onBack);centered(ctx,m[hero.nameKey],82,20,color.ink,'700');centered(ctx,ctx.locale==='en'?'SELECT A SLOT, THEN CHOOSE A SKILL':'先選擇欄位，再選擇技能',112,type.caption,color.gold,'700');uiText(root,ctx.locale,ctx.locale==='en'?'SIGNATURE PASSIVE':'英雄被動',layout.pagePad,153,type.caption,color.muted,'700');surface(root,layout.pagePad,174,canvas.width-layout.pagePad*2,66,true);uiText(root,ctx.locale,passiveName[hero.signaturePassive],40,196,type.label,color.ink,'700');uiText(root,ctx.locale,ctx.locale==='en'?'ACTIVE SKILLS':'主動技能',layout.pagePad,270,type.caption,color.muted,'700');opts.loadout.skillIds.forEach((skillId,i)=>{const slot=i as 0|1,x=layout.pagePad+i*174,y=294,w=164,h=78;const selected=opts.editingSlot===slot;const card=new Graphics().roundRect(x,y,w,h,10).fill({color:selected?color.paper:color.panel,alpha:1}).stroke({color:selected?color.gold:color.edge,width:selected?2:1});card.eventMode='static';card.cursor='pointer';card.on('pointertap',()=>opts.onSlot(slot));root.addChild(card);uiText(root,ctx.locale,`${ctx.locale==='en'?'SLOT':'欄位'} ${i+1}`,x+12,y+10,type.caption,selected?color.gold:color.muted,'700');uiText(root,ctx.locale,skillLabel(skillId),x+12,y+38,type.label,color.violet,'700');});uiText(root,ctx.locale,ctx.locale==='en'?'SKILL POOL':'可用技能池',layout.pagePad,408,type.caption,color.gold,'700');hero.skillPool.forEach((skillId,i)=>{const x=layout.pagePad+(i%2)*174,y=434+Math.floor(i/2)*72,w=164,h=58,equipped=opts.loadout.skillIds.includes(skillId);const card=new Graphics().roundRect(x,y,w,h,9).fill({color:equipped?color.paper:color.panel,alpha:1}).stroke({color:equipped?color.violet:color.edge,width:equipped?2:1});card.eventMode='static';card.cursor='pointer';card.on('pointertap',()=>opts.onSkill(skillId));root.addChild(card);uiText(root,ctx.locale,skillLabel(skillId),x+12,y+10,type.label,equipped?color.violet:color.ink,'700');uiText(root,ctx.locale,`${skills[skillId].cost} MP · ${ctx.locale==='en'?skills[skillId].category.toUpperCase():skills[skillId].category}`,x+12,y+34,type.caption,color.muted,'600');});actionButton(root,ctx.locale,layout.pagePad,676,canvas.width-layout.pagePad*2,48,ctx.locale==='en'?'RESET TO DEFAULT':'恢復預設配置',opts.onReset,false);centered(ctx,ctx.locale==='en'?'Two unique skills required · Blink is optional':'需裝備兩個不同技能 · Blink 非必選',742,type.caption,color.muted);}
