import { Graphics } from 'pixi.js';
import { HeroId,HeroLoadout,heroes,heroIds } from '../heroes';
import { getMessages } from '../i18n';
import { ViewContext } from './theme';
import { actionButton,pageHeader,surface,uiText } from './design/components';
import { canvas,color,layout,type } from './design/tokens';

const passiveName={fortified:'Guard / Fortified',flow:'Flow',pressure:'Pressure'} as const;
const skillName:Record<string,string>={blink:'Blink',charge:'Charge',phase:'Flame',corrupt:'Corrupt'};
const roleName={defense:'防禦',control:'控制',disruption:'干擾'} as const;
const heroColor:Record<HeroId,number>={vanguard:color.gold,arcanist:color.violet,shade:color.panelSoft};
function centered(ctx:ViewContext,value:string,y:number,size=type.body,fill=color.ink,weight='600'){const t=uiText(ctx.root,ctx.locale,value,0,y,size,fill,weight);t.anchor.set(.5,0);t.x=canvas.centerX;return t;}
function tappableCard(ctx:ViewContext,x:number,y:number,w:number,h:number,onTap:()=>void){const g=surface(ctx.root,x,y,w,h,true);g.eventMode='static';g.cursor='pointer';g.on('pointertap',onTap);return g;}
function emblem(ctx:ViewContext,id:HeroId,x:number,y:number,r:number){const g=new Graphics().poly([x,y-r,x+r,y,x,y+r,x-r,y]).fill({color:heroColor[id],alpha:.92}).stroke({color:color.goldSoft,width:1});ctx.root.addChild(g);return g;}

export function renderHeroCollection(ctx:ViewContext,opts:{onBack:()=>void;onHero:(id:HeroId)=>void}){const {root}=ctx,m=getMessages(ctx.locale);pageHeader(root,ctx.locale,ctx.locale==='en'?'Heroes':'英雄',opts.onBack);centered(ctx,ctx.locale==='en'?'HERO ARCHIVE':'英雄檔案',82,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'Manage your roster and battle kits':'管理持有英雄、被動與出戰技能組',105,12,color.inkSoft);heroIds.forEach((id,i)=>{const hero=heroes[id],y=150+i*154;tappableCard(ctx,layout.pagePad,y,canvas.width-layout.pagePad*2,132,()=>opts.onHero(id));emblem(ctx,id,67,y+52,28);uiText(root,ctx.locale,m[hero.nameKey],108,y+20,19,color.ink,'700');uiText(root,ctx.locale,`${ctx.locale==='en'?hero.role:roleName[hero.role]} · TIER ${hero.tier}`,108,y+48,type.caption,color.gold,'700');uiText(root,ctx.locale,passiveName[hero.innatePassive],108,y+76,12,color.violet,'700');uiText(root,ctx.locale,hero.defaultLoadout.skills.map(s=>skillName[s]??s).join('  ·  '),108,y+98,type.caption,color.inkSoft);const arrow=uiText(root,ctx.locale,'›',0,y+47,28,color.gold);arrow.anchor.set(1,0);arrow.x=canvas.width-38;});centered(ctx,ctx.locale==='en'?'Advanced paths will branch from base heroes':'未來衍生職業將由基礎英雄向下分支',650,type.caption,color.muted);}

export function renderHeroDetail(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;onBack:()=>void;onManageLoadout:()=>void}){const {root}=ctx,m=getMessages(ctx.locale),hero=heroes[opts.heroId];pageHeader(root,ctx.locale,m[hero.nameKey],opts.onBack);emblem(ctx,opts.heroId,canvas.centerX,155,48);centered(ctx,`TIER ${hero.tier} · ${ctx.locale==='en'?hero.role.toUpperCase():roleName[hero.role]}`,220,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'CURRENT BATTLE KIT':'目前出戰編組',258,type.caption,color.muted,'700');surface(root,layout.pagePad,286,canvas.width-layout.pagePad*2,88,true);uiText(root,ctx.locale,ctx.locale==='en'?'PASSIVE':'被動',40,302,type.caption,color.muted,'700');uiText(root,ctx.locale,passiveName[opts.loadout.passive],40,329,18,color.ink,'700');surface(root,layout.pagePad,390,canvas.width-layout.pagePad*2,138,true);uiText(root,ctx.locale,ctx.locale==='en'?'EQUIPPED SKILLS':'已裝備技能',40,406,type.caption,color.muted,'700');opts.loadout.skills.forEach((skill,i)=>{const x=40+i*158;const g=new Graphics().roundRect(x,443,146,62,8).fill(color.paper).stroke({color:color.edge,width:1});root.addChild(g);const t=uiText(root,ctx.locale,skillName[skill]??skill,0,462,type.label,color.violet,'700');t.anchor.set(.5,0);t.x=x+73;});actionButton(root,ctx.locale,layout.pagePad,556,canvas.width-layout.pagePad*2,58,ctx.locale==='en'?'MANAGE LOADOUT':'管理技能編組',opts.onManageLoadout,true);centered(ctx,ctx.locale==='en'?'CLASS PATH':'職業分支',652,type.caption,color.gold,'700');centered(ctx,ctx.locale==='en'?'Advanced classes reserved for a future progression slice':'二～三階衍生職業將於後續成長系統開放',678,type.caption,color.muted);}

export function renderLoadoutManagement(ctx:ViewContext,opts:{heroId:HeroId;loadout:HeroLoadout;onBack:()=>void}){const {root}=ctx,m=getMessages(ctx.locale),hero=heroes[opts.heroId];pageHeader(root,ctx.locale,ctx.locale==='en'?'Loadout':'技能編組',opts.onBack);centered(ctx,m[hero.nameKey],88,20,color.ink,'700');centered(ctx,ctx.locale==='en'?'BATTLE KIT':'出戰配置',118,type.caption,color.gold,'700');const rows:[string,string][]=[[ctx.locale==='en'?'PASSIVE':'被動',passiveName[opts.loadout.passive]],[ctx.locale==='en'?'COMMON SKILL':'共通技能',opts.loadout.commonSkill?skillName[opts.loadout.commonSkill]:'—'],[ctx.locale==='en'?'CLASS SKILLS':'職業技能',opts.loadout.heroSkills.map(s=>skillName[s]??s).join(' / ')]];rows.forEach(([label,value],i)=>{const y=170+i*112;surface(root,layout.pagePad,y,canvas.width-layout.pagePad*2,88,true);uiText(root,ctx.locale,label,40,y+14,type.caption,color.muted,'700');uiText(root,ctx.locale,value,40,y+43,type.label,color.ink,'700');});uiText(root,ctx.locale,'SKILL POOL',layout.pagePad,522,type.caption,color.gold,'700');const pool=hero.skillPool.map(s=>skillName[s]??s);pool.forEach((skill,i)=>{const x=layout.pagePad+(i%2)*174,y=550+Math.floor(i/2)*62;surface(root,x,y,164,48,false);const t=uiText(root,ctx.locale,skill,0,y+15,type.body,color.violet,'700');t.anchor.set(.5,0);t.x=x+82;});centered(ctx,ctx.locale==='en'?'Equipment editing unlocks with expanded skill rules':'技能池與裝備規則擴充後開放編輯',706,type.caption,color.muted);}
