import { Graphics } from 'pixi.js';
import { HeroId,heroes } from '../heroes';
import { getMessages } from '../i18n';
import { ViewContext,CANVAS_CENTER,button,centeredLabel,diamond,edge,gold,ink,label,muted,violet } from './theme';

export type BattleMode='cpu'|'local'|'online';

function header(ctx:ViewContext,title:string,onBack:()=>void){button(ctx,18,24,46,40,onBack);centeredLabel(ctx,'‹',41,28,30,ink,'700');label(ctx,title,78,31,22,ink,'700');}
function action(ctx:ViewContext,text:string,y:number,onTap:()=>void,active=false,sub?:string){button(ctx,34,y,322,92,onTap,active);centeredLabel(ctx,text,CANVAS_CENTER,y+23,20,active?0xf3e6c9:ink,'700');if(sub)centeredLabel(ctx,sub,CANVAS_CENTER,y+54,11,active?0xd8c8a7:muted);}

export function renderModeSelect(ctx:ViewContext,opts:{onBack:()=>void;onMode:(mode:BattleMode)=>void}){header(ctx,ctx.locale==='en'?'Battle':'對戰模式',opts.onBack);centeredLabel(ctx,ctx.locale==='en'?'CHOOSE YOUR BATTLE': '選擇對戰方式',CANVAS_CENTER,105,13,gold,'700');action(ctx,'VS CPU',150,()=>opts.onMode('cpu'),true,ctx.locale==='en'?'Battle a computer hero':'與電腦英雄進行對戰');action(ctx,ctx.locale==='en'?'LOCAL PLAYER':'本機雙人',258,()=>opts.onMode('local'),false,ctx.locale==='en'?'Take turns on this device':'同裝置輪流操作');action(ctx,ctx.locale==='en'?'ONLINE PLAYER':'線上對戰',366,()=>opts.onMode('online'),false,ctx.locale==='en'?'Create or join a room':'建立或加入房間');centeredLabel(ctx,ctx.locale==='en'?'Online multiplayer is reserved for a future slice.':'線上多人模式將於後續版本開放。',CANVAS_CENTER,493,11,muted);}

export function renderBattlePreview(ctx:ViewContext,opts:{heroId:HeroId;cpuHeroId:HeroId;randomOpponent?:boolean;onBack:()=>void;onStart:()=>void}){header(ctx,ctx.locale==='en'?'Battle Preview':'對戰確認',opts.onBack);const hero=heroes[opts.heroId],cpu=heroes[opts.cpuHeroId],m=getMessages(ctx.locale);centeredLabel(ctx,ctx.locale==='en'?'READY':'準備對戰',CANVAS_CENTER,105,13,gold,'700');const g=new Graphics();diamond(g,92,230,42,violet,false);diamond(g,298,230,42,gold,false);ctx.root.addChild(g);centeredLabel(ctx,m[hero.nameKey],92,290,19,ink,'700');centeredLabel(ctx,'VS',CANVAS_CENTER,221,22,gold,'700');centeredLabel(ctx,opts.randomOpponent?'???':m[cpu.nameKey],298,290,19,ink,'700');centeredLabel(ctx,ctx.locale==='en'?'You':'你',92,322,11,muted);centeredLabel(ctx,opts.randomOpponent?(ctx.locale==='en'?'Random CPU':'隨機 CPU'):'CPU',298,322,11,muted);if(opts.randomOpponent)centeredLabel(ctx,ctx.locale==='en'?'Opponent revealed when battle starts':'進入對局後揭曉對手',CANVAS_CENTER,365,11,gold,'700');button(ctx,42,430,306,70,opts.onStart,true);centeredLabel(ctx,ctx.locale==='en'?'START BATTLE':'開始對戰',CANVAS_CENTER,452,18,0xf3e6c9,'700');button(ctx,42,516,306,56,opts.onBack);centeredLabel(ctx,ctx.locale==='en'?'Change Hero':'更換英雄',CANVAS_CENTER,534,15,ink,'700');}

export function renderPauseOverlay(ctx:ViewContext,opts:{onResume:()=>void;onRestart:()=>void;onQuit:()=>void}){const shade=new Graphics().rect(0,0,390,844).fill({color:0x15141b,alpha:.72});ctx.root.addChild(shade);const card=new Graphics().roundRect(36,206,318,380,12).fill(0xf8f5ef).stroke({color:edge,width:1});ctx.root.addChild(card);centeredLabel(ctx,ctx.locale==='en'?'PAUSED':'暫停',CANVAS_CENTER,242,25,ink,'700');action(ctx,ctx.locale==='en'?'Resume':'繼續對戰',302,opts.onResume,true);action(ctx,ctx.locale==='en'?'Restart':'重新開始',408,opts.onRestart);button(ctx,70,520,250,48,opts.onQuit);centeredLabel(ctx,ctx.locale==='en'?'Surrender / Main Menu':'放棄對局 / 返回主選單',CANVAS_CENTER,535,13,0xa4473d,'700');}

export function renderResultOverlay(ctx:ViewContext,opts:{result:string;turns:number;onRematch:()=>void;onChangeHero:()=>void;onHome:()=>void}){const shade=new Graphics().rect(0,0,390,844).fill({color:0x15141b,alpha:.76});ctx.root.addChild(shade);const card=new Graphics().roundRect(28,158,334,500,12).fill(0xf8f5ef).stroke({color:gold,width:1});ctx.root.addChild(card);const victory=opts.result==='player-won';centeredLabel(ctx,victory?'VICTORY':opts.result==='draw'?'DRAW':'DEFEAT',CANVAS_CENTER,205,28,victory?violet:0xa4473d,'700');centeredLabel(ctx,ctx.locale==='en'?`${opts.turns} turns`:`${opts.turns} 回合`,CANVAS_CENTER,259,13,muted);button(ctx,54,334,282,66,opts.onRematch,true);centeredLabel(ctx,ctx.locale==='en'?'REMATCH':'再戰一場',CANVAS_CENTER,355,18,0xf3e6c9,'700');button(ctx,54,418,282,58,opts.onChangeHero);centeredLabel(ctx,ctx.locale==='en'?'Change Hero':'更換英雄',CANVAS_CENTER,436,15,ink,'700');button(ctx,54,492,282,58,opts.onHome);centeredLabel(ctx,ctx.locale==='en'?'Main Menu':'返回主選單',CANVAS_CENTER,510,15,ink,'700');}
