import { Container, Graphics, Text } from 'pixi.js';
import { MatchRecord } from '../match-records';
import { clampReplayIndex, projectReplay } from '../replay';
import { ViewContext } from './theme';

export type MenuScreen='home'|'history'|'stats'|'settings';
export interface MenuShellProps{screen:MenuScreen;records:readonly MatchRecord[];selectedRecordId?:string|null;replayIndex?:number;onReplayIndex?:(index:number)=>void;onNavigate:(screen:MenuScreen)=>void;onStart:()=>void;onSelectRecord?:(id:string|null)=>void;}
const ink=0x252431,paper=0xf3efe7,purple=0x7650b6,gold=0xc9a354,line=0xd7ccba;const heroName={arcanist:'奧術師',vanguard:'先鋒',shade:'影刃'} as const;
const labels:{id:MenuScreen;icon:string;label:string}[]=[{id:'home',icon:'▶',label:'對戰'},{id:'history',icon:'▣',label:'對局記錄'},{id:'stats',icon:'▥',label:'統計'},{id:'settings',icon:'⚙',label:'設定'}];
function text(value:string,size:number,color=ink){return new Text({text:value,style:{fontFamily:'Georgia, serif',fontSize:size,fill:color,fontWeight:'600'}})}
function button(parent:Container,x:number,y:number,w:number,h:number,label:string,active=false,onTap?:()=>void){const g=new Graphics().roundRect(x,y,w,h,5).fill(active?ink:paper).stroke({color:active?gold:line,width:1});g.eventMode='static';g.cursor='pointer';if(onTap)g.on('pointertap',onTap);parent.addChild(g);const t=text(label,Math.max(13,Math.min(18,h*.3)),active?0xf6ead0:ink);t.anchor.set(.5);t.position.set(x+w/2,y+h/2);parent.addChild(t);}
export function renderMenuShell(ctx:ViewContext,props:MenuShellProps){const {root}=ctx,w=window.innerWidth,h=window.innerHeight,pad=Math.max(20,w*.07),bottom=76,selected=props.records.find(r=>r.id===props.selectedRecordId);const title=text('GOMOKU',Math.min(42,w*.105));title.anchor.set(.5);title.position.set(w/2,Math.max(105,h*.16));root.addChild(title);const sub=text('R P G',16);sub.anchor.set(.5);sub.position.set(w/2,title.y+38);root.addChild(sub);
 if(props.screen==='home'){const crystal=new Graphics().poly([w/2,62,w/2+18,94,w/2,126,w/2-18,94]).fill({color:purple,alpha:.85});root.addChild(crystal);const cards=[['對戰','與 CPU 或其他玩家對戰'],['英雄','選擇你的英雄與技能'],['對局記錄',`${props.records.length} 場已保存對局`]];cards.forEach((c,i)=>{const y=h*.29+i*96;button(root,pad,y,w-pad*2,78,c[0],i===1,()=>i===0?props.onStart():i===2?props.onNavigate('history'):undefined);const d=text(c[1],11,i===1?0xd8ccb7:0x77716b);d.position.set(pad+82,y+48);root.addChild(d);});button(root,pad,h*.29+3*96,w*.4,58,'統計',false,()=>props.onNavigate('stats'));button(root,w-pad-w*.4,h*.29+3*96,w*.4,58,'設定',false,()=>props.onNavigate('settings'));}
 else {const y=62,back=text('‹',32);back.position.set(pad,y);back.eventMode='static';back.cursor='pointer';back.on('pointertap',()=>selected&&props.screen==='history'?props.onSelectRecord?.(null):props.onNavigate('home'));root.addChild(back);const heading=text(selected&&props.screen==='history'?'對局詳情':props.screen==='history'?'對局記錄':props.screen==='stats'?'數據摘要':'設定',24);heading.position.set(pad+36,y+6);root.addChild(heading);const panel=new Graphics().roundRect(pad,120,w-pad*2,h-120-bottom-20,7).fill({color:0xf8f4ec,alpha:.72}).stroke({color:line,width:1});root.addChild(panel);if(props.screen==='history')selected?renderMatchDetail(root,pad+18,142,w-pad*2-36,selected,props.replayIndex??0,props.onReplayIndex):renderHistory(root,pad+16,142,w-pad*2-32,props.records,props.onSelectRecord);if(props.screen==='stats')renderStats(root,pad+18,146,w-pad*2-36,props.records);if(props.screen==='settings')renderSettings(root,pad+18,146,w-pad*2-36);}
 const nav=new Graphics().rect(0,h-bottom,w,bottom).fill(ink);root.addChild(nav);labels.forEach((item,i)=>{const x=(i+.5)*w/4,active=props.screen===item.id,a=text(item.icon,20,active?0xe7d6ff:0xd4c7ae);a.anchor.set(.5);a.position.set(x,h-bottom+22);root.addChild(a);const l=text(item.label,11,active?0xe7d6ff:0xd4c7ae);l.anchor.set(.5);l.position.set(x,h-bottom+50);l.eventMode='static';l.cursor='pointer';l.on('pointertap',()=>props.onNavigate(item.id));root.addChild(l);});}
function renderHistory(root:Container,x:number,y:number,w:number,records:readonly MatchRecord[],onSelect?:((id:string|null)=>void)){const filters=['全部英雄⌄','全部結果⌄','最新先⌄'];filters.forEach((f,i)=>button(root,x+i*(w/3+4),y,w/3-5,40,f));if(!records.length){const empty=text('尚無對局記錄\n完成一場對戰後會自動保存。',15,0x77716b);empty.anchor.set(.5);empty.position.set(x+w/2,y+160);root.addChild(empty);return;}records.slice(0,5).forEach((record,i)=>{const yy=y+54+i*82,g=new Graphics().roundRect(x,yy,w,70,5).fill(0xf7f2e9).stroke({color:line,width:1});g.eventMode='static';g.cursor='pointer';g.on('pointertap',()=>onSelect?.(record.id));root.addChild(g);const hero=text(heroName[record.heroId],16);hero.position.set(x+52,yy+12);root.addChild(hero);const result=text(record.result.toUpperCase(),12,record.result==='victory'?purple:record.result==='defeat'?0xa5483f:0x77716b);result.position.set(x+52,yy+37);root.addChild(result);const turns=text(`${record.turns} 回合  ›`,13);turns.anchor.set(1,.5);turns.position.set(x+w-14,yy+25);root.addChild(turns);const time=text(new Date(record.finishedAt).toLocaleString(),9,0x77716b);time.anchor.set(1,.5);time.position.set(x+w-14,yy+49);root.addChild(time);const gem=new Graphics().poly([x+26,yy+15,x+40,yy+35,x+26,yy+55,x+12,yy+35]).fill(record.heroId==='vanguard'?gold:purple);root.addChild(gem);});}
function renderMatchDetail(root:Container,x:number,y:number,w:number,record:MatchRecord,replayIndex:number,onReplay?:((index:number)=>void)){const frames=projectReplay(record.actions),index=clampReplayIndex(replayIndex,frames.length),frame=frames[index];const result=text(record.result.toUpperCase(),15,record.result==='victory'?purple:record.result==='defeat'?0xa5483f:0x77716b);result.position.set(x,y);root.addChild(result);const matchup=text(`${heroName[record.heroId]}  VS  ${heroName[record.cpuHeroId]}`,18);matchup.position.set(x,y+27);root.addChild(matchup);const boardSize=Math.min(w,250),cell=boardSize/9,bx=x+(w-boardSize)/2,by=y+62;const board=new Graphics().roundRect(bx-8,by-8,boardSize+16,boardSize+16,4).fill(0xf2eadb).stroke({color:line,width:1});for(let i=0;i<9;i++){const p=i*cell+cell/2;board.moveTo(bx+cell/2,by+p).lineTo(bx+boardSize-cell/2,by+p).moveTo(bx+p,by+cell/2).lineTo(bx+p,by+boardSize-cell/2);}board.stroke({color:0xb8aa95,width:1});root.addChild(board);frame.board.forEach((row,r)=>row.forEach((stone,c)=>{if(!stone)return;const s=new Graphics().circle(bx+c*cell+cell/2,by+r*cell+cell/2,cell*.32).fill(stone===1?0xf5f0e8:ink).stroke({color:stone===1?0x8d8377:0x111118,width:1});root.addChild(s);}));if(frame.action){const marker=new Graphics().circle(bx+frame.action.at.col*cell+cell/2,by+frame.action.at.row*cell+cell/2,cell*.42).stroke({color:purple,width:2});root.addChild(marker);}const cy=by+boardSize+16;button(root,x,cy,52,34,'‹',false,()=>onReplay?.(index-1));button(root,x+w-52,cy,52,34,'›',false,()=>onReplay?.(index+1));const step=text(index===0?`起始 · 0 / ${frames.length-1}`:`#${frame.sequence} · ${index} / ${frames.length-1}`,13);step.anchor.set(.5);step.position.set(x+w/2,cy+17);root.addChild(step);const actionY=cy+48;if(frame.action){const actor=frame.action.actor==='player'?'YOU':'CPU',kind=frame.action.kind==='skill'?`技能 ${frame.action.skillId??''}`:'落子',at=`${String.fromCharCode(65+frame.action.at.col)}${frame.action.at.row+1}`,detail=text(`${actor} · ${kind} · ${at}`,12,frame.action.actor==='player'?purple:0xa5483f);detail.anchor.set(.5);detail.position.set(x+w/2,actionY);root.addChild(detail);}else{const detail=text('對局開始',12,0x77716b);detail.anchor.set(.5);detail.position.set(x+w/2,actionY);root.addChild(detail);}}
function renderStats(root:Container,x:number,y:number,w:number,records:readonly MatchRecord[]){const total=records.length,wins=records.filter(r=>r.result==='victory').length,avgTurns=total?records.reduce((s,r)=>s+r.turns,0)/total:0,avgSeconds=total?records.reduce((s,r)=>s+Math.max(0,(Date.parse(r.finishedAt)-Date.parse(r.startedAt))/1000),0)/total:0;[['勝率',total?`${Math.round(wins/total*100)}%`:'—'],['平均回合',total?avgTurns.toFixed(1):'—'],['平均對局時間',total?`${Math.floor(avgSeconds/60)}:${String(Math.round(avgSeconds%60)).padStart(2,'0')}`:'—'],['總對局',String(total)]].forEach((r,i)=>{const a=text(r[0],13,0x6f6962);a.position.set(x,y+i*38);root.addChild(a);const b=text(r[1],18);b.anchor.set(1,0);b.position.set(x+w,y+i*38);root.addChild(b);});const sep=new Graphics().moveTo(x,y+170).lineTo(x+w,y+170).stroke({color:line,width:1});root.addChild(sep);const heading=text('常用英雄',17);heading.position.set(x,y+194);root.addChild(heading);(['arcanist','vanguard','shade'] as const).forEach((id,i)=>{const heroRecords=records.filter(r=>r.heroId===id),heroWins=heroRecords.filter(r=>r.result==='victory').length,yy=y+235+i*58;const gem=new Graphics().circle(x+18,yy+12,13).fill(id==='vanguard'?gold:purple);root.addChild(gem);const n=text(heroName[id],15);n.position.set(x+45,yy);root.addChild(n);const p=text(heroRecords.length?`${Math.round(heroWins/heroRecords.length*100)}% · ${heroRecords.length}`:'—',15);p.anchor.set(1,0);p.position.set(x+w,yy);root.addChild(p);});}
function renderSettings(root:Container,x:number,y:number,w:number){const tabs=['一般','音效','畫面','關於'];tabs.forEach((t,i)=>button(root,x+i*w/4,y,w/4-4,38,t,i===0));[['語言 / Language','繁體中文⌄'],['主題 / Theme','明亮⌄']].forEach((r,i)=>{const yy=y+66+i*56,a=text(r[0],14);a.position.set(x,yy);root.addChild(a);button(root,x+w-128,yy-8,128,38,r[1]);});['顯示座標','顯示可落子點','動畫效果','震動回饋'].forEach((s,i)=>{const yy=y+190+i*52,a=text(s,14);a.position.set(x,yy);root.addChild(a);const toggle=new Graphics().roundRect(x+w-48,yy-4,48,26,13).fill(purple);toggle.circle(x+w-14,yy+9,9).fill(0xffffff);root.addChild(toggle);});}
