import { Container, Graphics } from 'pixi.js';

export const Palette = { background: 0x0d2428, backgroundDeep: 0x08181b, distant: 0x17363a, mid: 0x1d4144, foreground: 0x0a1719, teal: 0x78c9bf, tealSoft: 0xcce9e3, cream: 0xf0eadf, magenta: 0xb74468, magentaDeep: 0x692744, hazard: 0x26393b, gold: 0xf2d28b } as const;
export type EnvironmentLayers = { sky: Graphics; far: Container; mid: Container; foreground: Container; motes: Array<{ view: Graphics; baseY: number; drift: number }> };
export function createEnvironment(width: number, height: number): EnvironmentLayers { const sky = new Graphics(); sky.rect(0, 0, width, height).fill(Palette.background); sky.rect(0, 0, width, height * 0.28).fill({ color: 0x18383b, alpha: 0.22 }); sky.rect(0, height * 0.45, width, height * 0.55).fill({ color: Palette.backgroundDeep, alpha: 0.26 }); const far = new Container(); const mid = new Container(); const foreground = new Container(); for (let i = 0; i < 10; i += 1) { const tower = new Graphics(); const w = 24 + (i % 3) * 12; const h = 120 + (i % 4) * 55; tower.rect(-w / 2, -h, w, h).fill({ color: Palette.distant, alpha: 0.3 }); tower.poly([-w / 2, -h, 0, -h - 28 - (i % 2) * 18, w / 2, -h]).fill({ color: Palette.distant, alpha: 0.3 }); tower.position.set(18 + i * 42, height - 80 + (i % 2) * 18); far.addChild(tower); } for (let i = 0; i < 7; i += 1) { const ruin = new Graphics(); const w = 40 + (i % 3) * 18; const h = 150 + (i % 4) * 70; ruin.rect(-w / 2, -h, w, h).fill({ color: Palette.mid, alpha: 0.44 }); ruin.position.set(30 + i * 58, height - 12 + (i % 2) * 22); mid.addChild(ruin); } const leftFrame = new Graphics(); leftFrame.poly([0, 0, 26, 0, 26, 110, 48, 138, 48, 248, 31, 274, 31, height, 0, height]).fill({ color: Palette.foreground, alpha: 0.92 }); const rightFrame = new Graphics(); rightFrame.poly([width, 0, width - 28, 0, width - 28, 150, width - 52, 180, width - 52, 310, width - 30, 336, width - 30, height, width, height]).fill({ color: Palette.foreground, alpha: 0.92 }); foreground.addChild(leftFrame, rightFrame); const motes: Array<{ view: Graphics; baseY: number; drift: number }> = []; for (let i = 0; i < 11; i += 1) { const mote = new Graphics(); mote.circle(0, 0, 1 + (i % 3) * 0.6).fill({ color: i % 5 === 0 ? Palette.gold : Palette.tealSoft, alpha: 0.12 + (i % 4) * 0.035 }); const baseY = 70 + ((i * 83) % (height - 140)); mote.position.set(40 + ((i * 71) % (width - 80)), baseY); foreground.addChild(mote); motes.push({ view: mote, baseY, drift: 4 + (i % 5) * 1.4 }); } return { sky, far, mid, foreground, motes }; }
export function updateEnvironment(layers: EnvironmentLayers, worldOffset: number, elapsed: number, height: number) { layers.far.y = (worldOffset * 0.08) % 80; layers.mid.y = (worldOffset * 0.18) % 110; layers.motes.forEach((mote, index) => { mote.view.y = mote.baseY + Math.sin(elapsed * 0.7 + index) * mote.drift; mote.view.x += Math.sin(elapsed * 0.25 + index * 0.9) * 0.015; if (mote.view.y > height - 20) mote.view.y = 20; }); }
export function createPlatformVisual(width: number): Graphics { const g = new Graphics(); g.poly([-width / 2 - 7, -7, width / 2 + 7, -7, width / 2, 4, -width / 2 + 3, 4]).fill({ color: 0x173437, alpha: 0.98 }); g.rect(-width / 2, -7, width, 3).fill(Palette.teal); g.rect(-width / 2 + 8, -3, Math.max(12, width - 18), 2).fill({ color: Palette.tealSoft, alpha: 0.3 }); return g; }
export function createWallVisual(height: number, side: -1 | 1): Graphics { const g = new Graphics(); const x = side === -1 ? 0 : -16; g.rect(x, -height / 2, 16, height).fill({ color: 0x173437, alpha: 0.96 }); const edgeX = side === -1 ? 15 : 1; g.rect(edgeX, -height / 2 + 5, 2, height - 10).fill({ color: Palette.teal, alpha: 0.85 }); for (let y = -height / 2 + 18; y < height / 2 - 10; y += 24) g.rect(side === -1 ? 5 : -9, y, 6, 2).fill({ color: Palette.tealSoft, alpha: 0.22 }); return g; }
export function createHazardVisual(): Graphics { const g = new Graphics(); g.circle(0, 0, 11).fill(Palette.hazard); g.circle(0, 0, 14).stroke({ width: 1.5, color: Palette.magentaDeep, alpha: 0.45 }); for (let i = 0; i < 8; i += 1) { const a = (Math.PI * 2 * i) / 8; g.moveTo(Math.cos(a) * 13, Math.sin(a) * 13).lineTo(Math.cos(a) * (i % 2 === 0 ? 20 : 18), Math.sin(a) * (i % 2 === 0 ? 20 : 18)).stroke({ width: 3.5, color: Palette.magentaDeep, alpha: 0.72 }); } g.circle(0, 0, 4).fill({ color: 0xf16c78, alpha: 0.88 }); return g; }
export function setHazardDanger(view: Graphics, danger: number) { const clamped = Math.max(0, Math.min(1, danger)); view.scale.set(0.92 + clamped * 0.12); view.alpha = 0.68 + clamped * 0.32; }
export function createCrystalVisual(): Graphics { const g = new Graphics(); g.circle(0, 0, 20).fill({ color: Palette.tealSoft, alpha: 0.035 }); g.poly([0, -16, 11, 0, 0, 16, -11, 0]).fill(Palette.teal); g.poly([0, -10, 6, 0, 0, 10, -6, 0]).fill(Palette.tealSoft); return g; }
export function createDroneVisual(): Graphics { const g = new Graphics(); g.circle(0, 0, 20).fill({ color: Palette.gold, alpha: 0.035 }); g.poly([-16, 0, -7, -9, 7, -9, 16, 0, 7, 9, -7, 9]).fill({ color: 0x1f3436, alpha: 0.98 }); g.poly([-16, 0, -24, -5, -20, 4]).fill({ color: Palette.teal, alpha: 0.7 }); g.poly([16, 0, 24, -5, 20, 4]).fill({ color: Palette.teal, alpha: 0.7 }); g.circle(0, 0, 5).fill(Palette.gold); g.circle(0, 0, 2).fill(Palette.cream); return g; }
export function redrawPlayer(view: Graphics, x: number, y: number, elapsed: number, dashing: number) { view.clear(); const sway = Math.sin(elapsed * 8) * 2; const lean = dashing === 0 ? 0 : dashing * 5; if (dashing !== 0) view.poly([-28 * dashing, 2, -12 * dashing, -8, -8 * dashing, 6]).fill({ color: Palette.teal, alpha: 0.16 }); view.poly([-17 + lean, 8, -7 + lean, -24, 10 + lean, -22, 19 + lean, 7, 5 + lean, 14]).fill(Palette.cream); view.poly([-7 + lean, -24, 10 + lean, -22, 4 + lean, -9]).fill(0x172b2d); view.circle(lean, -10, 2.3).fill(Palette.backgroundDeep); view.roundRect(-7 + lean, 9, 15, 14, 5).fill(0x243d3f); view.poly([-7 + lean, 12, -23 - sway + lean, 18, -9 + lean, 7]).fill({ color: Palette.teal, alpha: 0.78 }); view.position.set(x, y); }
export function redrawAbyss(view: Graphics, width: number, height: number, elapsed: number) { view.clear(); const baseY = height - 70; const waveA = Math.sin(elapsed * 2.7) * 7; const waveB = Math.sin(elapsed * 4.1 + 1.2) * 5; view.poly([0, baseY + waveA, width * 0.16, baseY - 10 + waveB, width * 0.34, baseY + 3 - waveA, width * 0.52, baseY - 13 + waveB, width * 0.7, baseY + 1 + waveA, width * 0.86, baseY - 8 - waveB, width, baseY + waveA, width, height, 0, height]).fill({ color: Palette.magentaDeep, alpha: 0.78 }); view.poly([0, baseY + 18, width * 0.2, baseY + 3 + waveB, width * 0.45, baseY + 12 - waveA, width * 0.72, baseY - 3 + waveA, width, baseY + 12, width, height, 0, height]).fill({ color: Palette.magenta, alpha: 0.2 }); }
