import { Container, Graphics, Text, TextStyle } from 'pixi.js';
import { createApplication } from './bootstrap';
import { LANDING_DELAY, MIN_DASH_STRENGTH, PLAYER_FEET_OFFSET, applyAirNudge, applyCrystalPickup, applyDash, applyDroneKill, applyHit, applyLanding, applyWallContact, applyWallJump, clearWallContact, createInitialState, tickState, type GameState } from './domain/gameState';
import { Palette, createCrystalVisual, createDroneVisual, createEnvironment, createHazardVisual, createPlatformVisual, createWallVisual, redrawAbyss, redrawPlayer, setHazardDanger, updateEnvironment } from './presentation/visuals';
const LOGICAL_W=360, LOGICAL_H=720, START_PLATFORM_Y=602, CAMERA_DEAD_ZONE_Y=330, CAMERA_SPRING=42, CAMERA_DAMPING=11, REGULAR_GAP_MIN=72, REGULAR_GAP_MAX=90, REST_GAP_MIN=88, REST_GAP_MAX=104, MIN_SWIPE_DISTANCE=24, DASH_SWIPE_THRESHOLD=52, MAX_SWIPE_DISTANCE=120, LANDING_EDGE_ASSIST=12;
async function bootstrap(){
 const app=await createApplication(LOGICAL_W,LOGICAL_H); document.querySelector('#app')!.appendChild(app.canvas); const root=new Container(); app.stage.addChild(root); const environment=createEnvironment(LOGICAL_W,LOGICAL_H); root.addChild(environment.sky,environment.far,environment.mid); const world=new Container(); root.addChild(world); const particles=new Container(); root.addChild(particles); const abyss=new Graphics(); root.addChild(abyss); root.addChild(environment.foreground); const hud=new Container(); root.addChild(hud); const player=new Graphics(); world.addChild(player);
 const platforms:Array<{view:Graphics;x:number;y:number;w:number}>=[], hazards:Array<{view:Graphics;x:number;y:number;hit:boolean}>=[], crystals:Array<{view:Graphics;x:number;y:number;taken:boolean}>=[], drones:Array<{view:Graphics;x:number;y:number;destroyed:boolean;phase:number}>=[], walls:Array<{view:Graphics;x:number;y:number;h:number;side:-1|1}>=[];
 const title=new Text({text:'VERTEX',style:new TextStyle({fill:'#f3efe7',fontSize:16,fontWeight:'600',letterSpacing:6})}); title.position.set(22,20); hud.addChild(title); const flowText=new Text({text:'',style:new TextStyle({fill:'#f0eadf',fontSize:19,fontWeight:'600'})}); flowText.position.set(22,61); hud.addChild(flowText); const scoreText=new Text({text:'',style:new TextStyle({fill:'#789b99',fontSize:10})}); scoreText.position.set(22,88); hud.addChild(scoreText); const hpText=new Text({text:'',style:new TextStyle({fill:'#d8e7e2',fontSize:13,letterSpacing:4})}); hpText.anchor.set(1,0); hpText.position.set(LOGICAL_W-22,22); hud.addChild(hpText); const dashText=new Text({text:'',style:new TextStyle({fill:'#a9c8c4',fontSize:9,fontWeight:'600',letterSpacing:1.8})}); dashText.anchor.set(1,0); dashText.position.set(LOGICAL_W-22,50); hud.addChild(dashText); const helpText=new Text({text:'SHORT · NUDGE   LONG · DASH   WALL · SWIPE AWAY',style:new TextStyle({fill:'#95b4b1',fontSize:7.5,letterSpacing:0.8})}); helpText.anchor.set(.5); helpText.position.set(LOGICAL_W/2,LOGICAL_H-22); hud.addChild(helpText); const overText=new Text({text:'',style:new TextStyle({fill:'#fff7ee',fontSize:21,fontWeight:'600',align:'center'})}); overText.anchor.set(.5); overText.position.set(LOGICAL_W/2,LOGICAL_H/2-20); hud.addChild(overText);
 let state:GameState=createInitialState(),cameraOffset=0,cameraVelocity=0,lastSpawnY=START_PLATFORM_Y,pointerStartX=0,pointerStartY=0,invulnerable=0,dashDirection:-1|0|1=0,dashVisualTime=0,cameraShake=0,bandIndex=0;
 const makePlatform=(x:number,y:number,w:number)=>{const view=createPlatformVisual(w);view.position.set(x,y);world.addChild(view);platforms.push({view,x,y,w})}; const makeHazard=(x:number,y:number)=>{const view=createHazardVisual();view.position.set(x,y);world.addChild(view);hazards.push({view,x,y,hit:false})}; const makeCrystal=(x:number,y:number)=>{const view=createCrystalVisual();view.position.set(x,y);world.addChild(view);crystals.push({view,x,y,taken:false})}; const makeDrone=(x:number,y:number)=>{const view=createDroneVisual();view.position.set(x,y);world.addChild(view);drones.push({view,x,y,destroyed:false,phase:Math.random()*Math.PI*2})}; const makeWall=(side:-1|1,y:number,h=116)=>{const x=side===-1?52:308,view=createWallVisual(h,side);view.position.set(x,y);world.addChild(view);walls.push({view,x,y,h,side})}; const randomGap=(a:number,b:number)=>a+Math.random()*(b-a);
 function spawnBand(){bandIndex++;const rest=bandIndex%4===0;lastSpawnY-=rest?randomGap(REST_GAP_MIN,REST_GAP_MAX):randomGap(REGULAR_GAP_MIN,REGULAR_GAP_MAX);const lanes=[82,180,278] as const,lane=lanes[Math.floor(Math.random()*3)];makePlatform(lane,lastSpawnY,rest?68+Math.random()*20:74+Math.random()*38);if(rest){if(Math.random()<.42)makeCrystal(lane,lastSpawnY-46);return}const others=lanes.filter(x=>x!==lane),route=others[Math.floor(Math.random()*others.length)];if(bandIndex%5===0)makeWall(route<180?-1:1,lastSpawnY-42);else if(Math.random()<.34)makeDrone(route,lastSpawnY-38);else if(Math.random()<.48)makeHazard(route,lastSpawnY-30);if(Math.random()<.48)makeCrystal(lane,lastSpawnY-46)}
 function seedWorld(){makePlatform(180,START_PLATFORM_Y,122);lastSpawnY=START_PLATFORM_Y;bandIndex=0;for(let i=0;i<12;i++)spawnBand()} function reset(){state=createInitialState();cameraOffset=cameraVelocity=0;lastSpawnY=START_PLATFORM_Y;invulnerable=dashVisualTime=cameraShake=0;dashDirection=0;for(const item of [...platforms,...hazards,...crystals,...drones,...walls])item.view.destroy();platforms.length=hazards.length=crystals.length=drones.length=walls.length=0;seedWorld();overText.text=''}
 function burst(x:number,y:number,color:number){for(let i=0;i<7;i++){const s=new Graphics(),a=Math.PI*2*i/7;s.poly([0,-4,3,2,-2,2]).fill({color,alpha:.7});s.position.set(x+Math.cos(a)*10,y+Math.sin(a)*10);particles.addChild(s);setTimeout(()=>s.destroy(),180+i*12)}}
 function dash(direction:-1|1,strength=1){if(!state.dashReady||state.gameOver)return;state=applyDash(state,direction,strength);dashDirection=direction;dashVisualTime=.15;const screenY=state.playerY+cameraOffset,trailLength=38+strength*28;for(let i=0;i<6;i++){const trail=new Graphics(),t=i/6;trail.poly([-9,7,0,-12,9,7]).fill({color:Palette.cream,alpha:(.08+strength*.04)*(1-t)});trail.position.set(state.playerX-direction*(12+t*trailLength),screenY);particles.addChild(trail);setTimeout(()=>trail.destroy(),90+i*18)}}
 function nudge(direction:-1|1,strength:number){if(state.gameOver)return;state=applyAirNudge(state,direction,strength);dashDirection=direction;dashVisualTime=.07} const dashStrength=(d:number)=>MIN_DASH_STRENGTH+Math.max(0,Math.min(1,(d-DASH_SWIPE_THRESHOLD)/(MAX_SWIPE_DISTANCE-DASH_SWIPE_THRESHOLD)))*(1-MIN_DASH_STRENGTH); const nudgeStrength=(d:number)=>Math.max(.45,Math.min(1,(d-MIN_SWIPE_DISTANCE)/(DASH_SWIPE_THRESHOLD-MIN_SWIPE_DISTANCE)));
 function handleSwipe(dx:number,dy:number){const d=Math.abs(dx);if(d<MIN_SWIPE_DISTANCE||d<=Math.abs(dy))return;const dir:-1|1=dx<0?-1:1;if(state.wallSide!==0&&dir===-state.wallSide){state=applyWallJump(state);dashDirection=dir;dashVisualTime=.11;cameraShake=2.8;return}if(d<DASH_SWIPE_THRESHOLD)nudge(dir,nudgeStrength(d));else dash(dir,dashStrength(d))}
 window.addEventListener('keydown',e=>{if(e.key==='a'||e.key==='ArrowLeft')handleSwipe(-90,0);if(e.key==='d'||e.key==='ArrowRight')handleSwipe(90,0);if(e.key==='r'&&state.gameOver)reset()});app.canvas.addEventListener('pointerdown',e=>{pointerStartX=e.clientX;pointerStartY=e.clientY;if(state.gameOver)reset()});app.canvas.addEventListener('pointerup',e=>handleSwipe(e.clientX-pointerStartX,e.clientY-pointerStartY));function resize(){const scale=Math.min(innerWidth/LOGICAL_W,innerHeight/LOGICAL_H);app.canvas.style.width=`${LOGICAL_W*scale}px`;app.canvas.style.height=`${LOGICAL_H*scale}px`}window.addEventListener('resize',resize);resize();seedWorld();
 app.ticker.add(t=>{const dt=Math.min(.033,t.deltaMS/1000);if(!state.gameOver){const previousFeet=state.playerY+PLAYER_FEET_OFFSET;state=tickState(state,dt);invulnerable=Math.max(0,invulnerable-dt);dashVisualTime=Math.max(0,dashVisualTime-dt);cameraShake=Math.max(0,cameraShake-dt*28);if(dashVisualTime<=0)dashDirection=0;if(state.velocityY>=0&&state.landingTime<=0){const nextFeet=state.playerY+PLAYER_FEET_OFFSET;for(const p of platforms)if(Math.abs(state.playerX-p.x)<=p.w/2+LANDING_EDGE_ASSIST&&previousFeet<=p.y+4&&nextFeet>=p.y-2){state=applyLanding(state,p.y);cameraShake=2.2;break}}
  let touchingWall=false;if(state.wallJumpLock<=0)for(const w of walls){if(Math.abs(state.playerY-w.y)<=w.h/2+20&&Math.abs(state.playerX-w.x)<=18){state=applyWallContact(state,w.side,w.x);touchingWall=true;break}}if(!touchingWall)state=clearWallContact(state);
  const before=state.playerY+cameraOffset,target=before<CAMERA_DEAD_ZONE_Y?CAMERA_DEAD_ZONE_Y-state.playerY:cameraOffset,acc=(target-cameraOffset)*CAMERA_SPRING-cameraVelocity*CAMERA_DAMPING;cameraVelocity+=acc*dt;cameraOffset=Math.max(cameraOffset,cameraOffset+cameraVelocity*dt);if(cameraVelocity<0)cameraVelocity=0;updateEnvironment(environment,cameraOffset,state.elapsed,LOGICAL_H);for(const p of platforms)p.view.y=p.y+cameraOffset;for(const w of walls)w.view.y=w.y+cameraOffset;for(const h of hazards){h.view.y=h.y+cameraOffset;h.view.rotation+=dt*.36;setHazardDanger(h.view,1-Math.min(1,Math.hypot(state.playerX-h.x,state.playerY-h.y)/150))}for(const c of crystals){c.view.y=c.y+cameraOffset+Math.sin(state.elapsed*2.4+c.x)*3;c.view.rotation=Math.sin(state.elapsed*1.3+c.x)*.04}for(const d of drones)if(!d.destroyed){d.view.y=d.y+cameraOffset+Math.sin(state.elapsed*3+d.phase)*5;d.view.rotation=Math.sin(state.elapsed*2+d.phase)*.06}while(lastSpawnY+cameraOffset>-150)spawnBand();for(const c of crystals)if(!c.taken&&Math.abs(state.playerX-c.x)<24&&Math.abs(state.playerY-c.y)<32){c.taken=true;c.view.visible=false;state=applyCrystalPickup(state);burst(c.x,c.y+cameraOffset,Palette.tealSoft)}for(const d of drones){if(d.destroyed||Math.hypot(state.playerX-d.x,state.playerY-d.y)>=28)continue;if(state.dashTime>0&&!state.dashReady){d.destroyed=true;d.view.visible=false;state=applyDroneKill(state);burst(d.x,d.y+cameraOffset,Palette.gold)}else if(invulnerable<=0){invulnerable=.9;state=applyHit(state)}}if(invulnerable<=0)for(const h of hazards)if(!h.hit&&Math.hypot(state.playerX-h.x,state.playerY-h.y)<25){h.hit=true;invulnerable=.9;state=applyHit(state);break}if(state.playerY+cameraOffset>LOGICAL_H+55)state={...state,gameOver:true,hp:0}}
  const sx=cameraShake>0?Math.sin(state.elapsed*68)*cameraShake:0,sy=cameraShake>0?Math.cos(state.elapsed*57)*cameraShake*.55:0;world.position.set(sx,sy);particles.position.set(sx,sy);redrawPlayer(player,state.playerX,state.playerY+cameraOffset,state.elapsed,dashDirection);if(state.landingTime>0){const pulse=Math.sin((1-state.landingTime/LANDING_DELAY)*Math.PI);player.scale.set(1+pulse*.16,1-pulse*.14)}else player.scale.set(1);player.alpha=invulnerable>0&&Math.floor(invulnerable*12)%2===0?.35:1;redrawAbyss(abyss,LOGICAL_W,LOGICAL_H,state.elapsed);flowText.text=`×${state.flow.toFixed(1)}`;scoreText.text=`${Math.floor(state.score).toLocaleString()} · ${state.elapsed.toFixed(1)}s`;hpText.text='◇'.repeat(state.hp);dashText.text=state.wallSide!==0?'WALL  ↗':state.dashReady?'DASH  ◆':'DASH  ·';dashText.alpha=state.dashReady||state.wallSide!==0?1:.45;if(state.gameOver)overText.text=`THE ABYSS CAUGHT YOU\n\n${Math.floor(state.score).toLocaleString()}\n\nTAP TO RETURN`});
}
void bootstrap();
