import { BOARD_SIZE, Player, Pos, isWin, longestLine } from '../game';
import { CombatState, isFlamed, isSealed } from '../combat';
import { SkillId, skills } from '../skills';
import { CPU_BASELINE_LEVEL, CpuDifficultyProfile, cpuDifficulty } from './cpu-difficulty';
import { patternMoveScore } from './cpu-pattern-recognition';
import { candidateSearchBonus } from './cpu-candidate-search';

export type CpuPlaceAction={kind:'place';at:Pos};
export type CpuSkillAction={kind:'skill';skillId:SkillId;target:Pos;source?:Pos};
export type CpuAction=CpuPlaceAction|CpuSkillAction;
export interface CpuScoreBreakdown{attack:number;defense:number;position:number;search:number;skill:number;total:number;}
export interface CpuDecisionCandidate{action:CpuAction;score:number;breakdown:CpuScoreBreakdown;reasons:string[];}
export interface ScoredCpuAction extends CpuDecisionCandidate{bestScore?:number;regret?:number;decisionReason?:string;topCandidates?:CpuDecisionCandidate[];}
const CPU:Player=2,PLAYER:Player=1;const dirs=[[1,0],[0,1],[1,1],[1,-1]] as const;
function inBoard(row:number,col:number){return row>=0&&row<BOARD_SIZE&&col>=0&&col<BOARD_SIZE;}
function centerScore(p:Pos){const center=(BOARD_SIZE-1)/2;return 40-(Math.abs(p.row-center)+Math.abs(p.col-center))*4;}
function linePotential(state:CombatState,p:Pos,player:Player){const board=state.board;if(board[p.row]?.[p.col]!==0)return -Infinity;board[p.row][p.col]=player;const length=longestLine(board,p,player);let open=0;for(const [dr,dc] of dirs)for(const sign of [-1,1]){const r=p.row+dr*sign,c=p.col+dc*sign;if(inBoard(r,c)&&board[r][c]===0)open++;}board[p.row][p.col]=0;if(length>=5)return 100000;if(length===4)return 18000+open*100;if(length===3)return 3200+open*40;if(length===2)return 280+open*10;return 12;}
function boardThreat(state:CombatState,player:Player){let best=0;state.board.forEach((row,r)=>row.forEach((cell,c)=>{if(cell===0)best=Math.max(best,linePotential(state,{row:r,col:c},player));}));return best;}
function stoneStructureValue(state:CombatState,p:Pos,player:Player){if(state.board[p.row]?.[p.col]!==player)return 0;let value=0,lines=0;for(const [dr,dc] of dirs){let length=1,open=0;for(const sign of [-1,1]){let r=p.row+dr*sign,c=p.col+dc*sign;while(inBoard(r,c)&&state.board[r][c]===player){length++;r+=dr*sign;c+=dc*sign;}if(inBoard(r,c)&&state.board[r][c]===0)open++;}if(length>=2)lines++;if(length>=4)value+=12000+open*1000;else if(length===3)value+=2800+open*500;else if(length===2)value+=350+open*80;}return value+Math.max(0,lines-1)*1800;}
function chargeScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='charge'||!action.source)return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU);const next=skills.charge.execute({state,player:CPU},action.target,action.source);if(isWin(next.board,action.target,CPU))return 1_000_000;const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const disrupted=Math.max(0,beforePlayer-afterPlayer),improved=Math.max(0,afterCpu-beforeCpu);const pushedEnemy=state.board[action.target.row]?.[action.target.col]===PLAYER;return disrupted*1.25+improved*1.05+(pushedEnemy?240:0)-180;}
function phaseScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='phase')return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU);const next=skills.phase.execute({state,player:CPU},action.target);if(isWin(next.board,action.target,CPU))return 1_000_000;const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const denied=next.flames.filter((f)=>isFlamed(next,f.pos)).reduce((score,f)=>score+Math.max(0,linePotential(state,f.pos,PLAYER)),0);const disrupted=Math.max(0,beforePlayer-afterPlayer),improved=Math.max(0,afterCpu-beforeCpu);return 900+disrupted*1.2+improved*.8+Math.min(denied,7000)*.55+centerScore(action.target);}
function corruptScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='corrupt'||state.board[action.target.row]?.[action.target.col]!==PLAYER)return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU),structure=stoneStructureValue(state,action.target,PLAYER);const next=skills.corrupt.execute({state,player:CPU},action.target);const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const disrupted=Math.max(0,beforePlayer-afterPlayer),opened=Math.max(0,afterCpu-beforeCpu);return 250+structure*1.15+disrupted*1.35+opened*.35+centerScore(action.target);}
function rallyScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='rally'||!action.source)return 0;const beforeCpu=boardThreat(state,CPU),beforePlayer=boardThreat(state,PLAYER);const next=skills.rally.execute({state,player:CPU},action.target,action.source);if(isWin(next.board,action.target,CPU))return 1_000_000;const improved=Math.max(0,boardThreat(next,CPU)-beforeCpu),exposed=Math.max(0,boardThreat(next,PLAYER)-beforePlayer);return 220+improved*.9-exposed*.35+stoneStructureValue(next,action.target,CPU)*.25+centerScore(action.target);}
function latticeScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='lattice')return 0;const next=skills.lattice.execute({state,player:CPU},action.target);let denied=0,sealed=0;for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]] as const){const pos={row:action.target.row+dr,col:action.target.col+dc};if(inBoard(pos.row,pos.col)&&state.board[pos.row][pos.col]===0&&isSealed(next,pos)){sealed++;denied+=Math.max(0,linePotential(state,pos,PLAYER));}}return sealed?180+Math.min(denied,9000)*.65+stoneStructureValue(state,action.target,CPU)*.15+sealed*35:0;}
function skillScore(state:CombatState,action:CpuSkillAction){if(action.skillId==='charge')return chargeScore(state,action);if(action.skillId==='phase')return phaseScore(state,action);if(action.skillId==='corrupt')return corruptScore(state,action);if(action.skillId==='rally')return rallyScore(state,action);if(action.skillId==='lattice')return latticeScore(state,action);return 0;}
function placementPotential(state:CombatState,p:Pos,player:Player,profile:CpuDifficultyProfile){return profile.level>=4?patternMoveScore(state,p,player,profile.patternDepth):linePotential(state,p,player);}
function evaluateCpuAction(state:CombatState,action:CpuAction,profile:CpuDifficultyProfile):CpuDecisionCandidate{if(action.kind==='place'){const attack=placementPotential(state,action.at,CPU,profile),defense=placementPotential(state,action.at,PLAYER,profile),position=centerScore(action.at),search=candidateSearchBonus(state,action.at,profile);let total:number,reasons:string[]=[];if(attack>=100000){total=1_000_000;reasons=['IMMEDIATE_WIN'];}else if(defense>=100000){total=900_000;reasons=['FORCED_BLOCK'];}else{total=attack*(.65+.4*profile.threatAwareness)+defense*(.55+.6*profile.defenseAwareness)+position+search;if(attack>=3200)reasons.push('ATTACK_PATTERN');if(defense>=3200)reasons.push('DEFEND_PATTERN');if(search>0)reasons.push('SEARCH_BONUS');if(position>=32)reasons.push('CENTER_CONTROL');if(!reasons.length)reasons.push('POSITIONAL');}return {action,score:total,breakdown:{attack,defense,position,search,skill:0,total},reasons};}const raw=skillScore(state,action),skillScale=profile.level<CPU_BASELINE_LEVEL?.7:1+(profile.skillPlanningDepth-Math.max(1,cpuDifficulty(CPU_BASELINE_LEVEL).skillPlanningDepth))*.05,total=raw*skillScale;return {action,score:total,breakdown:{attack:0,defense:0,position:0,search:0,skill:total,total},reasons:[`SKILL_${action.skillId.toUpperCase()}`]};}
export function scoreCpuAction(state:CombatState,action:CpuAction,profile:CpuDifficultyProfile=cpuDifficulty()):number{return evaluateCpuAction(state,action,profile).score;}
export function rankCpuActions(state:CombatState,candidates:readonly CpuAction[],profile:CpuDifficultyProfile=cpuDifficulty()):ScoredCpuAction[]{return candidates.map(action=>evaluateCpuAction(state,action,profile)).sort((a,b)=>b.score-a.score);}
function immediateTacticalAction(state:CombatState,ranked:readonly ScoredCpuAction[]):ScoredCpuAction|undefined{const placements=ranked.filter((candidate):candidate is ScoredCpuAction&{action:CpuPlaceAction}=>candidate.action.kind==='place');const wins=placements.filter(({action})=>linePotential(state,action.at,CPU)>=100000);if(wins.length)return wins[0];const blocks=placements.filter(({action})=>linePotential(state,action.at,PLAYER)>=100000);return blocks[0];}
export function chooseCpuAction(state:CombatState,candidates:readonly CpuAction[],profile:CpuDifficultyProfile=cpuDifficulty(CPU_BASELINE_LEVEL),random:()=>number=Math.random):ScoredCpuAction|null{const ranked=rankCpuActions(state,candidates,profile);if(!ranked.length)return null;const best=ranked[0],forced=immediateTacticalAction(state,ranked),topCandidates=ranked.slice(0,5).map(({action,score,breakdown,reasons})=>({action,score,breakdown,reasons}));if(forced)return {...forced,bestScore:best.score,regret:Math.max(0,best.score-forced.score),decisionReason:forced.reasons[0]??'FORCED_TACTICAL',topCandidates};const width=Math.max(1,Math.min(profile.candidateWidth,ranked.length));let selected=best,decisionReason='BEST_SCORE';if(random()>profile.optimalMoveRate&&width>1){const floor=best.score*(1-profile.blunderTolerance),pool=ranked.slice(1,width).filter(candidate=>candidate.score>=floor);if(pool.length){selected=pool[Math.floor(random()*pool.length)];decisionReason='DIFFICULTY_VARIANCE';}}return {...selected,bestScore:best.score,regret:Math.max(0,best.score-selected.score),decisionReason,topCandidates};}
