import { BOARD_SIZE, Player, Pos, isWin, longestLine } from '../game';
import { CombatState, isFlamed } from '../combat';
import { SkillId, skills } from '../skills';
import { CPU_BASELINE_LEVEL, CpuDifficultyProfile, cpuDifficulty } from './cpu-difficulty';

export type CpuPlaceAction={kind:'place';at:Pos};
export type CpuSkillAction={kind:'skill';skillId:SkillId;target:Pos;source?:Pos};
export type CpuAction=CpuPlaceAction|CpuSkillAction;
export interface ScoredCpuAction{action:CpuAction;score:number;bestScore?:number;regret?:number;}
const CPU:Player=2,PLAYER:Player=1;const dirs=[[1,0],[0,1],[1,1],[1,-1]] as const;
function inBoard(row:number,col:number){return row>=0&&row<BOARD_SIZE&&col>=0&&col<BOARD_SIZE;}
function centerScore(p:Pos){const center=(BOARD_SIZE-1)/2;return 40-(Math.abs(p.row-center)+Math.abs(p.col-center))*4;}
function linePotential(state:CombatState,p:Pos,player:Player){const board=state.board;if(board[p.row]?.[p.col]!==0)return -Infinity;board[p.row][p.col]=player;const length=longestLine(board,p,player);let open=0;for(const [dr,dc] of dirs)for(const sign of [-1,1]){const r=p.row+dr*sign,c=p.col+dc*sign;if(inBoard(r,c)&&board[r][c]===0)open++;}board[p.row][p.col]=0;if(length>=5)return 100000;if(length===4)return 18000+open*100;if(length===3)return 3200+open*40;if(length===2)return 280+open*10;return 12;}
function boardThreat(state:CombatState,player:Player){let best=0;state.board.forEach((row,r)=>row.forEach((cell,c)=>{if(cell===0)best=Math.max(best,linePotential(state,{row:r,col:c},player));}));return best;}
function stoneStructureValue(state:CombatState,p:Pos,player:Player){if(state.board[p.row]?.[p.col]!==player)return 0;let value=0,lines=0;for(const [dr,dc] of dirs){let length=1,open=0;for(const sign of [-1,1]){let r=p.row+dr*sign,c=p.col+dc*sign;while(inBoard(r,c)&&state.board[r][c]===player){length++;r+=dr*sign;c+=dc*sign;}if(inBoard(r,c)&&state.board[r][c]===0)open++;}if(length>=2)lines++;if(length>=4)value+=12000+open*1000;else if(length===3)value+=2800+open*500;else if(length===2)value+=350+open*80;}return value+Math.max(0,lines-1)*1800;}
function chargeScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='charge'||!action.source)return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU);const next=skills.charge.execute({state,player:CPU},action.target,action.source);if(isWin(next.board,action.target,CPU))return 1_000_000;const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const disrupted=Math.max(0,beforePlayer-afterPlayer),improved=Math.max(0,afterCpu-beforeCpu);const pushedEnemy=state.board[action.target.row]?.[action.target.col]===PLAYER;return disrupted*1.25+improved*1.05+(pushedEnemy?240:0)-180;}
function phaseScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='phase')return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU);const next=skills.phase.execute({state,player:CPU},action.target);if(isWin(next.board,action.target,CPU))return 1_000_000;const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const denied=next.flames.filter((f)=>isFlamed(next,f.pos)).reduce((score,f)=>score+Math.max(0,linePotential(state,f.pos,PLAYER)),0);const disrupted=Math.max(0,beforePlayer-afterPlayer),improved=Math.max(0,afterCpu-beforeCpu);return 900+disrupted*1.2+improved*.8+Math.min(denied,7000)*.55+centerScore(action.target);}
function corruptScore(state:CombatState,action:CpuSkillAction){if(action.skillId!=='corrupt'||state.board[action.target.row]?.[action.target.col]!==PLAYER)return 0;const beforePlayer=boardThreat(state,PLAYER),beforeCpu=boardThreat(state,CPU),structure=stoneStructureValue(state,action.target,PLAYER);const next=skills.corrupt.execute({state,player:CPU},action.target);const afterPlayer=boardThreat(next,PLAYER),afterCpu=boardThreat(next,CPU);const disrupted=Math.max(0,beforePlayer-afterPlayer),opened=Math.max(0,afterCpu-beforeCpu);return 250+structure*1.15+disrupted*1.35+opened*.35+centerScore(action.target);}
function skillScore(state:CombatState,action:CpuSkillAction){if(action.skillId==='charge')return chargeScore(state,action);if(action.skillId==='phase')return phaseScore(state,action);if(action.skillId==='corrupt')return corruptScore(state,action);return 0;}
export function scoreCpuAction(state:CombatState,action:CpuAction,profile:CpuDifficultyProfile=cpuDifficulty()):number{if(action.kind==='place'){const attack=linePotential(state,action.at,CPU),defense=linePotential(state,action.at,PLAYER);if(attack>=100000)return 1_000_000;if(defense>=100000)return 900_000;return attack*(.65+.4*profile.threatAwareness)+defense*(.55+.6*profile.defenseAwareness)+centerScore(action.at);}const raw=skillScore(state,action);return profile.skillPlanningDepth===0?raw*.7:raw*(1+profile.skillPlanningDepth*.05);}
export function rankCpuActions(state:CombatState,candidates:readonly CpuAction[],profile:CpuDifficultyProfile=cpuDifficulty()):ScoredCpuAction[]{return candidates.map(action=>({action,score:scoreCpuAction(state,action,profile)})).sort((a,b)=>b.score-a.score);}
export function chooseCpuAction(state:CombatState,candidates:readonly CpuAction[],profile:CpuDifficultyProfile=cpuDifficulty(CPU_BASELINE_LEVEL),random:()=>number=Math.random):ScoredCpuAction|null{const ranked=rankCpuActions(state,candidates,profile);if(!ranked.length)return null;const best=ranked[0],width=Math.max(1,Math.min(profile.candidateWidth,ranked.length));let selected=best;if(random()>profile.optimalMoveRate&&width>1){const floor=best.score*(1-profile.blunderTolerance),pool=ranked.slice(1,width).filter(candidate=>candidate.score>=floor);if(pool.length)selected=pool[Math.floor(random()*pool.length)];}return {...selected,bestScore:best.score,regret:Math.max(0,best.score-selected.score)};}
