import { Player, Pos, createBoard, winningLine } from '../game';
import { CombatState, createCombatState, getMana } from '../combat';
import { SkillId, skills } from '../skills';
import { HeroDefinition, HeroId, Loadout, createLoadout, heroes, tryCreateLoadout } from '../heroes';
import { PlaytestMetrics, createPlaytestMetrics, finishMetrics, recordMana, recordManaWaste, recordPlacement, recordSkill, recordSkillOpportunities, recordTurnStart } from '../telemetry';
import { ActionResolution, resolvePlaceAction, resolveSkillAction } from './action-resolution';
import { ActionFeedback, ActionHistoryEntry, appendActionHistory } from './action-feedback';
import { CpuResolution, resolveCpuTurn } from './cpu-runtime';
import { CPU_BASELINE_LEVEL, CPU_LEVEL_MAX, CPU_LEVEL_MIN } from './cpu-difficulty';
import { CPU_DEFAULT_DIFFICULTY,CpuDifficultyId,closestDifficultyForProfileLevel,cpuProfileLevelForDifficulty } from './cpu-difficulty-tier';
import { IDLE_TARGETING, SkillTargetingState, TargetingHighlights, selectTargetingCell, targetingHighlights, toggleTargeting } from './targeting';
import { SkillBarItem, StatusKey, describeSkillBar, statusKey } from './presentation';
import { MatchStatus, TurnState, completeCpuTurn, completePlayerTurn, continuePlayerTurn, createTurnState, endMatch, isPlayerInput } from './turn-runtime';
export const PLAYER:Player=1;const CPU_DELAY=500,CPU_DELAY_AFTER_PASSIVE=900,FULL_HISTORY_LIMIT=200;const heroIds=Object.keys(heroes) as HeroId[];export function randomCpuHero(random:()=>number=Math.random):HeroId{return heroIds[Math.floor(random()*heroIds.length)]??'vanguard';}
export type MatchEvent=|{kind:'reset'}|{kind:'move';at:Pos}|{kind:'mana-gain';amount:number;fromSkill:boolean}|{kind:'passive';at:Pos}|{kind:'action';at:Pos}|{kind:'action-feedback';feedback:ActionFeedback}|{kind:'invalid';at:Pos}|{kind:'winning-line';cells:Pos[]};
export interface MatchRuntimePolicy{playerSkillsEnabled:boolean;cpuSkillsEnabled:boolean;}
export const FULL_MATCH_RUNTIME_POLICY:MatchRuntimePolicy={playerSkillsEnabled:true,cpuSkillsEnabled:true};
export type Timer=ReturnType<typeof setTimeout>;export interface MatchRuntimeOptions{heroId:HeroId;schedule:(callback:()=>void,delay:number)=>Timer;cancel:(timer:Timer)=>void;onChange:()=>void;onEvent:(event:MatchEvent)=>void;initialState?:()=>CombatState;cpuHeroId?:HeroId;cpuDifficulty?:CpuDifficultyId;/** @deprecated internal profile override for compatibility tests. */cpuLevel?:number;random?:()=>number;}
export interface MatchSnapshot{state:CombatState;turn:TurnState;hero:HeroDefinition;cpuHero:HeroDefinition;cpuDifficulty:CpuDifficultyId;cpuProfileLevel:number;/** @deprecated internal compatibility alias. */cpuLevel:number;loadout:Loadout;cpuLoadout:Loadout;mana:number;cpuMana:number;status:StatusKey;highlights:TargetingHighlights;skillBar:SkillBarItem[];acceptsInput:boolean;actionHistory:ActionHistoryEntry[];}
export interface MatchRuntime{snapshot():MatchSnapshot;metrics():PlaytestMetrics;heroId():HeroId;cpuHeroId():HeroId;cpuDifficulty():CpuDifficultyId;cpuProfileLevel():number;/** @deprecated use cpuDifficulty/cpuProfileLevel. */cpuLevel():number;selectHero(heroId:HeroId):void;setLoadout(skillIds:readonly SkillId[]):boolean;selectCpuHero(heroId:HeroId):void;selectCpuDifficulty(difficulty:CpuDifficultyId):void;/** @deprecated internal compatibility hook. */selectCpuLevel(level:number):void;setPolicy(policy:MatchRuntimePolicy):void;randomizeCpuHero():HeroId;reset():void;selectSkill(skillId:SkillId):void;tapCell(pos:Pos):void;dispose():void;}
export function createMatchRuntime({heroId,schedule,cancel,onChange,onEvent,initialState=()=>createCombatState(createBoard()),cpuHeroId,cpuDifficulty=CPU_DEFAULT_DIFFICULTY,cpuLevel,random=Math.random}:MatchRuntimeOptions):MatchRuntime{
 const initialProfileLevel=cpuLevel===undefined?cpuProfileLevelForDifficulty(cpuDifficulty):Math.max(CPU_LEVEL_MIN,Math.min(CPU_LEVEL_MAX,Math.round(cpuLevel)));
 let hero=heroId,cpuHero=cpuHeroId??randomCpuHero(random),selectedCpuDifficulty=cpuLevel===undefined?cpuDifficulty:closestDifficultyForProfileLevel(initialProfileLevel),selectedCpuProfileLevel=initialProfileLevel,loadout=createLoadout(hero),cpuLoadout=createLoadout(cpuHero),combat=initialState(),metrics=createPlaytestMetrics(hero,getMana(combat,PLAYER)),turn=createTurnState(),targeting:SkillTargetingState=IDLE_TARGETING,cpuTimer:Timer|null=null,turnStartRecorded=false,actionHistory:ActionHistoryEntry[]=[],runtimePolicy:MatchRuntimePolicy={...FULL_MATCH_RUNTIME_POLICY};
 const clearCpuTimer=()=>{if(cpuTimer!==null){cancel(cpuTimer);cpuTimer=null;}};const decide=(status:Exclude<MatchStatus,'playing'>)=>{turn=endMatch(turn,status);finishMetrics(metrics,status,getMana(combat,PLAYER));onChange();};
 const setCpuHero=(next:HeroId)=>{cpuHero=next;cpuLoadout=createLoadout(next);};
 const recordFeedback=(feedback:ActionFeedback)=>{actionHistory=appendActionHistory(actionHistory,feedback,FULL_HISTORY_LIMIT);onEvent({kind:'action-feedback',feedback});};
 function reset(){clearCpuTimer();combat=initialState();metrics=createPlaytestMetrics(hero,getMana(combat,PLAYER));turn=createTurnState();targeting=IDLE_TARGETING;turnStartRecorded=false;actionHistory=[];onEvent({kind:'reset'});}
 function finishPlayerTurn(delay:number){recordMana(metrics,getMana(combat,PLAYER));turnStartRecorded=false;const done=completePlayerTurn(combat,turn);combat=done.state;turn=done.turn;onChange();cpuTimer=schedule(runCpuTurn,delay);}function keepPlayerTurn(){turn=continuePlayerTurn(turn);onChange();}function recordCurrentTurnStart(){if(!turnStartRecorded){recordTurnStart(metrics,getMana(combat,PLAYER));turnStartRecorded=true;}}
 function hasLegalOpportunity(skillId:SkillId){if(!runtimePolicy.playerSkillsEnabled)return false;const skill=skills[skillId];if(getMana(combat,PLAYER)<skill.cost)return false;const context={state:combat,player:PLAYER};if(skill.legalSources)return skill.legalSources(context).some((source)=>skill.legalTargets(context,source).length>0);return skill.legalTargets(context).length>0;}function currentSkillOpportunities(){return runtimePolicy.playerSkillsEnabled?loadout.skillIds.filter(hasLegalOpportunity):[];}
 function applyResolution(resolution:ActionResolution,opportunities:readonly SkillId[]){const manaBefore=getMana(combat,PLAYER);recordSkillOpportunities(metrics,opportunities);combat=resolution.state;const mana=getMana(combat,PLAYER),generated=resolution.skillId?resolution.passiveMana:resolution.manaGained+resolution.passiveMana;recordManaWaste(metrics,generated,manaBefore-(resolution.skillId?resolution.skillCost:0),mana);resolution.skillId?recordSkill(metrics,resolution.skillId,resolution.skillCost,resolution.passiveTriggered,resolution.passiveMana,mana,manaBefore):recordPlacement(metrics,resolution.manaGained,resolution.passiveTriggered,resolution.passiveMana,mana);targeting=IDLE_TARGETING;onEvent({kind:'move',at:resolution.at});recordFeedback({actor:'player',player:1,heroId:hero,kind:resolution.skillId?'skill':'place',at:resolution.at,source:resolution.source,skillId:resolution.skillId});onEvent({kind:'mana-gain',amount:resolution.skillId?resolution.passiveMana:resolution.manaGained,fromSkill:!!resolution.skillId});if(resolution.passiveTriggered)onEvent({kind:'passive',at:resolution.at});if(resolution.won){onEvent({kind:'winning-line',cells:winningLine(combat.board,resolution.at,PLAYER)});decide('victory');return;}onEvent({kind:'action',at:resolution.at});if(!resolution.consumedTurn){keepPlayerTurn();return;}finishPlayerTurn(resolution.passiveTriggered?CPU_DELAY_AFTER_PASSIVE:CPU_DELAY);}
 function runCpuTurn(){cpuTimer=null;const cpu:CpuResolution=resolveCpuTurn(combat,cpuHero,selectedCpuProfileLevel,{skillsEnabled:runtimePolicy.cpuSkillsEnabled});if(cpu.outcome==='draw'){decide('draw');return;}if(cpu.outcome==='blocked'){keepPlayerTurn();return;}combat=cpu.state;onEvent({kind:'move',at:cpu.at!});const action=cpu.action!;recordFeedback({actor:'cpu',player:2,heroId:cpuHero,kind:action.kind,at:cpu.at!,source:action.kind==='skill'?action.source:undefined,skillId:action.kind==='skill'?action.skillId:undefined,decision:{cpuDifficulty:selectedCpuDifficulty,profileLevel:selectedCpuProfileLevel,cpuLevel:cpu.cpuLevel,selectedScore:cpu.decisionScore,bestScore:cpu.decisionBestScore,regret:cpu.decisionRegret,reason:cpu.decisionReason,topCandidates:cpu.topCandidates,manaBefore:cpu.manaBefore}});if(cpu.passiveTriggered)onEvent({kind:'passive',at:cpu.at!});if(cpu.outcome==='won'){onEvent({kind:'winning-line',cells:winningLine(combat.board,cpu.at!,2)});decide('defeat');return;}const done=completeCpuTurn(combat,turn);combat=done.state;turn=done.turn;turnStartRecorded=false;onEvent({kind:'action',at:cpu.at!});}
 return {snapshot:()=>({state:combat,turn,hero:heroes[hero],cpuHero:heroes[cpuHero],cpuDifficulty:selectedCpuDifficulty,cpuProfileLevel:selectedCpuProfileLevel,cpuLevel:selectedCpuProfileLevel,loadout,cpuLoadout,mana:getMana(combat,PLAYER),cpuMana:getMana(combat,2),status:statusKey(turn,targeting),highlights:runtimePolicy.playerSkillsEnabled?targetingHighlights(combat,PLAYER,targeting):{sources:[],targets:[]},skillBar:runtimePolicy.playerSkillsEnabled?describeSkillBar(combat,PLAYER,loadout,turn,targeting):[],acceptsInput:isPlayerInput(turn),actionHistory}),metrics:()=>metrics,heroId:()=>hero,cpuHeroId:()=>cpuHero,cpuDifficulty:()=>selectedCpuDifficulty,cpuProfileLevel:()=>selectedCpuProfileLevel,cpuLevel:()=>selectedCpuProfileLevel,selectHero(next){hero=next;loadout=createLoadout(next);targeting=IDLE_TARGETING;},setLoadout(skillIds){const next=tryCreateLoadout(hero,skillIds);if(!next)return false;loadout=next;targeting=IDLE_TARGETING;onChange();return true;},selectCpuHero(next){setCpuHero(next);},selectCpuDifficulty(next){selectedCpuDifficulty=next;selectedCpuProfileLevel=cpuProfileLevelForDifficulty(next);},selectCpuLevel(next){selectedCpuProfileLevel=Math.max(CPU_LEVEL_MIN,Math.min(CPU_LEVEL_MAX,Math.round(next)));selectedCpuDifficulty=closestDifficultyForProfileLevel(selectedCpuProfileLevel);},setPolicy(next){runtimePolicy={...next};if(!runtimePolicy.playerSkillsEnabled)targeting=IDLE_TARGETING;},randomizeCpuHero(){const next=randomCpuHero(random);setCpuHero(next);return next;},reset,selectSkill(skillId){if(!runtimePolicy.playerSkillsEnabled||!isPlayerInput(turn)||!loadout.skillIds.includes(skillId)||getMana(combat,PLAYER)<skills[skillId].cost)return;recordCurrentTurnStart();targeting=toggleTargeting(targeting,skillId);onChange();},tapCell(pos){if(!isPlayerInput(turn))return;recordCurrentTurnStart();const opportunities=currentSkillOpportunities();if(targeting.mode!=='idle'){if(!runtimePolicy.playerSkillsEnabled){targeting=IDLE_TARGETING;onChange();return;}const intent=selectTargetingCell(combat,PLAYER,targeting,pos);if(intent.kind==='invalid'){onEvent({kind:'invalid',at:pos});return;}if(intent.kind==='source'){targeting=intent.targeting;onChange();return;}const cast=resolveSkillAction(combat,hero,PLAYER,intent.skillId,intent.target,intent.source);cast.ok?applyResolution(cast,opportunities):onEvent({kind:'invalid',at:pos});return;}const placement=resolvePlaceAction(combat,hero,PLAYER,pos);placement.ok?applyResolution(placement,opportunities):onEvent({kind:'invalid',at:pos});},dispose:clearCpuTimer};
}
