import { Player, Pos, createBoard, winningLine } from '../game';
import { CombatState, createCombatState, getMana } from '../combat';
import { SkillId, skills } from '../skills';
import { HeroDefinition, HeroId, Loadout, createLoadout, heroes } from '../heroes';
import { PlaytestMetrics, createPlaytestMetrics, finishMetrics, recordMana, recordManaWaste, recordPlacement, recordSkill, recordSkillOpportunities, recordTurnStart } from '../telemetry';
import { ActionResolution, resolvePlaceAction, resolveSkillAction } from './action-resolution';
import { ActionFeedback, ActionHistoryEntry, appendActionHistory } from './action-feedback';
import { CpuResolution, resolveCpuTurn } from './cpu-runtime';
import { CPU_BASELINE_LEVEL, CPU_LEVEL_MAX, CPU_LEVEL_MIN } from './cpu-difficulty';
import { IDLE_TARGETING, SkillTargetingState, TargetingHighlights, selectTargetingCell, targetingHighlights, toggleTargeting } from './targeting';
import { SkillBarItem, StatusKey, describeSkillBar, statusKey } from './presentation';
import { MatchStatus, TurnState, completeCpuTurn, completePlayerTurn, continuePlayerTurn, createTurnState, endMatch, isPlayerInput } from './turn-runtime';
export const PLAYER:Player=1;const CPU_DELAY=500,CPU_DELAY_AFTER_PASSIVE=900,FULL_HISTORY_LIMIT=200;const heroIds=Object.keys(heroes) as HeroId[];export function randomCpuHero(random:()=>number=Math.random):HeroId{return heroIds[Math.floor(random()*heroIds.length)]??'vanguard';}
export type MatchEvent=|{kind:'reset'}|{kind:'move';at:Pos}|{kind:'mana-gain';amount:number;fromSkill:boolean}|{kind:'passive';at:Pos}|{kind:'action';at:Pos}|{kind:'action-feedback';feedback:ActionFeedback}|{kind:'invalid';at:Pos}|{kind:'winning-line';cells:Pos[]};
export type Timer=ReturnType<typeof setTimeout>;export interface MatchRuntimeOptions{heroId:HeroId;schedule:(callback:()=>void,delay:number)=>Timer;cancel:(timer:Timer)=>void;onChange:()=>void;onEvent:(event:MatchEvent)=>void;initialState?:()=>CombatState;cpuHeroId?:HeroId;cpuLevel?:number;random?:()=>number;}
export interface MatchSnapshot{state:CombatState;turn:TurnState;hero:HeroDefinition;cpuHero:HeroDefinition;cpuLevel:number;loadout:Loadout;cpuLoadout:Loadout;mana:number;cpuMana:number;status:StatusKey;highlights:TargetingHighlights;skillBar:SkillBarItem[];acceptsInput:boolean;actionHistory:ActionHistoryEntry[];}
export interface MatchRuntime{snapshot():MatchSnapshot;metrics():PlaytestMetrics;heroId():HeroId;cpuHeroId():HeroId;cpuLevel():number;selectHero(heroId:HeroId):void;selectCpuHero(heroId:HeroId):void;selectCpuLevel(level:number):void;randomizeCpuHero():HeroId;reset():void;selectSkill(skillId:SkillId):void;tapCell(pos:Pos):void;dispose():void;}
export function createMatchRuntime({heroId,schedule,cancel,onChange,onEvent,initialState=()=>createCombatState(createBoard()),cpuHeroId,cpuLevel=CPU_BASELINE_LEVEL,random=Math.random}:MatchRuntimeOptions):MatchRuntime{
 let hero=heroId,cpuHero=cpuHeroId??randomCpuHero(random),selectedCpuLevel=Math.max(CPU_LEVEL_MIN,Math.min(CPU_LEVEL_MAX,Math.round(cpuLevel))),loadout=createLoadout(hero),cpuLoadout=createLoadout(cpuHero),combat=initialState(),metrics=createPlaytestMetrics(hero,getMana(combat,PLAYER)),turn=createTurnState(),targeting:SkillTargetingState=IDLE_TARGETING,cpuTimer:Timer|null=null,turnStartRecorded=false,actionHistory:ActionHistoryEntry[]=[];
 const clearCpuTimer=()=>{if(cpuTimer!==null){cancel(cpuTimer);cpuTimer=null;}};const decide=(status:Exclude<MatchStatus,'playing'>)=>{turn=endMatch(turn,status);finishMetrics(metrics,status,getMana(combat,PLAYER));onChange();};
 const setCpuHero=(next:HeroId)=>{cpuHero=next;cpuLoadout=createLoadout(next);};
 const recordFeedback=(feedback:ActionFeedback)=>{actionHistory=appendActionHistory(actionHistory,feedback,FULL_HISTORY_LIMIT);onEvent({kind:'action-feedback',feedback});};
 function reset(){clearCpuTimer();combat=initialState();metrics=createPlaytestMetrics(hero,getMana(combat,PLAYER));turn=createTurnState();targeting=IDLE_TARGETING;turnStartRecorded=false;actionHistory=[];onEvent({kind:'reset'});}
 function finishPlayerTurn(delay:number){recordMana(metrics,getMana(combat,PLAYER));turnStartRecorded=false;const done=completePlayerTurn(combat,turn);combat=done.state;turn=done.turn;onChange();cpuTimer=schedule(runCpuTurn,delay);}function keepPlayerTurn(){turn=continuePlayerTurn(turn);onChange();}function recordCurrentTurnStart(){if(!turnStartRecorded){recordTurnStart(metrics,getMana(combat,PLAYER));turnStartRecorded=true;}}
 function hasLegalOpportunity(skillId:SkillId){const skill=skills[skillId];if(getMana(combat,PLAYER)<skill.cost)return false;const context={state:combat,player:PLAYER};if(skill.legalSources)return skill.legalSources(context).some((source)=>skill.legalTargets(context,source).length>0);return skill.legalTargets(context).length>0;}function currentSkillOpportunities(){return loadout.skills.filter(hasLegalOpportunity);}
 function applyResolution(resolution:ActionResolution,opportunities:readonly SkillId[]){const manaBefore=getMana(combat,PLAYER);recordSkillOpportunities(metrics,opportunities);combat=resolution.state;const mana=getMana(combat,PLAYER),generated=resolution.skillId?resolution.passiveMana:resolution.manaGained+resolution.passiveMana;recordManaWaste(metrics,generated,manaBefore-(resolution.skillId?resolution.skillCost:0),mana);resolution.skillId?recordSkill(metrics,resolution.skillId,resolution.skillCost,resolution.passiveTriggered,resolution.passiveMana,mana,manaBefore):recordPlacement(metrics,resolution.manaGained,resolution.passiveTriggered,resolution.passiveMana,mana);targeting=IDLE_TARGETING;onEvent({kind:'move',at:resolution.at});recordFeedback({actor:'player',player:1,heroId:hero,kind:resolution.skillId?'skill':'place',at:resolution.at,source:resolution.source,skillId:resolution.skillId});onEvent({kind:'mana-gain',amount:resolution.skillId?resolution.passiveMana:resolution.manaGained,fromSkill:!!resolution.skillId});if(resolution.passiveTriggered)onEvent({kind:'passive',at:resolution.at});if(resolution.won){onEvent({kind:'winning-line',cells:winningLine(combat.board,resolution.at,PLAYER)});decide('victory');return;}onEvent({kind:'action',at:resolution.at});if(!resolution.consumedTurn){keepPlayerTurn();return;}finishPlayerTurn(resolution.passiveTriggered?CPU_DELAY_AFTER_PASSIVE:CPU_DELAY);}
 function runCpuTurn(){cpuTimer=null;const cpu:CpuResolution=resolveCpuTurn(combat,cpuHero,selectedCpuLevel);if(cpu.outcome==='draw'){decide('draw');return;}if(cpu.outcome==='blocked'){keepPlayerTurn();return;}combat=cpu.state;onEvent({kind:'move',at:cpu.at!});const action=cpu.action!;recordFeedback({actor:'cpu',player:2,heroId:cpuHero,kind:action.kind,at:cpu.at!,source:action.kind==='skill'?action.source:undefined,skillId:action.kind==='skill'?action.skillId:undefined});if(cpu.passiveTriggered)onEvent({kind:'passive',at:cpu.at!});if(cpu.outcome==='won'){onEvent({kind:'winning-line',cells:winningLine(combat.board,cpu.at!,2)});decide('defeat');return;}const done=completeCpuTurn(combat,turn);combat=done.state;turn=done.turn;turnStartRecorded=false;onEvent({kind:'action',at:cpu.at!});}
 return {snapshot:()=>({state:combat,turn,hero:heroes[hero],cpuHero:heroes[cpuHero],cpuLevel:selectedCpuLevel,loadout,cpuLoadout,mana:getMana(combat,PLAYER),cpuMana:getMana(combat,2),status:statusKey(turn,targeting),highlights:targetingHighlights(combat,PLAYER,targeting),skillBar:describeSkillBar(combat,PLAYER,loadout,turn,targeting),acceptsInput:isPlayerInput(turn),actionHistory}),metrics:()=>metrics,heroId:()=>hero,cpuHeroId:()=>cpuHero,cpuLevel:()=>selectedCpuLevel,selectHero(next){hero=next;loadout=createLoadout(next);},selectCpuHero(next){setCpuHero(next);},selectCpuLevel(next){selectedCpuLevel=Math.max(CPU_LEVEL_MIN,Math.min(CPU_LEVEL_MAX,Math.round(next)));},randomizeCpuHero(){const next=randomCpuHero(random);setCpuHero(next);return next;},reset,selectSkill(skillId){if(!isPlayerInput(turn)||!loadout.skills.includes(skillId)||getMana(combat,PLAYER)<skills[skillId].cost)return;recordCurrentTurnStart();targeting=toggleTargeting(targeting,skillId);onChange();},tapCell(pos){if(!isPlayerInput(turn))return;recordCurrentTurnStart();const opportunities=currentSkillOpportunities();if(targeting.mode!=='idle'){const intent=selectTargetingCell(combat,PLAYER,targeting,pos);if(intent.kind==='invalid'){onEvent({kind:'invalid',at:pos});return;}if(intent.kind==='source'){targeting=intent.targeting;onChange();return;}const cast=resolveSkillAction(combat,hero,PLAYER,intent.skillId,intent.target,intent.source);cast.ok?applyResolution(cast,opportunities):onEvent({kind:'invalid',at:pos});return;}const placement=resolvePlaceAction(combat,hero,PLAYER,pos);placement.ok?applyResolution(placement,opportunities):onEvent({kind:'invalid',at:pos});},dispose:clearCpuTimer};
}
