import { describe, expect, it } from 'vitest';
import { AIR_NUDGE_SPEED, AUTO_JUMP_VELOCITY, CRYSTAL_LIFT_VELOCITY, DASH_SPEED, DASH_UPGRADE_SPEED_MULTIPLIER, DRONE_BOUNCE_VELOCITY, FLOW_OVERDRIVE_HIT_FLOOR, FLOW_RUSH_HIT_FLOOR, LANDING_DELAY, MAX_AUTO_JUMP_RISE, MAX_DASH_SPEED, MIN_DASH_SPEED, PLAYER_FEET_OFFSET, WALL_JUMP_VELOCITY_X, WALL_JUMP_VELOCITY_Y, WALL_SLIDE_SPEED, applyAirNudge, applyCrystalPickup, applyDash, applyDroneKill, applyHit, applyLanding, applyUpgrade, applyWallContact, applyWallJump, clearWallContact, createInitialState, tickState } from '../src/domain/gameState';

describe('game state', () => {
  it('integrates vertical velocity with gravity', () => { const initial = createInitialState(); const next = tickState(initial, 0.1); expect(next.elapsed).toBeCloseTo(0.1); expect(next.velocityY).toBeGreaterThan(initial.velocityY); expect(next.playerY).toBeLessThan(initial.playerY); });
  it('keeps the auto-jump rise above generated gaps', () => { expect(MAX_AUTO_JUMP_RISE).toBeGreaterThan(104); });
  it('compresses before auto-jump and restores dash on landing', () => { let state = applyDash(createInitialState(), 1); state = applyLanding({ ...state, playerY: 500, velocityY: 300 }, 540); expect(state.playerY).toBe(540 - PLAYER_FEET_OFFSET); expect(state.landingTime).toBe(LANDING_DELAY); expect(state.dashReady).toBe(true); state = tickState(state, LANDING_DELAY + 0.001); expect(state.velocityY).toBe(AUTO_JUMP_VELOCITY); });
  it('allows repeated air nudges without consuming dash', () => { const nudged = applyAirNudge(createInitialState(), 1, 1); expect(nudged.velocityX).toBe(AIR_NUDGE_SPEED); expect(nudged.dashReady).toBe(true); expect(applyAirNudge(nudged, -1, 0.5).dashReady).toBe(true); });
  it('slows a fall while touching a wall and restores dash', () => { const spent = applyDash({ ...createInitialState(), velocityY: 500 }, 1); const wall = applyWallContact({ ...spent, velocityY: 500 }, 1, 300); expect(wall.wallSide).toBe(1); expect(wall.velocityY).toBe(WALL_SLIDE_SPEED); expect(wall.dashReady).toBe(true); });
  it('wall-jumps away from the contacted wall without consuming dash', () => { const wall = applyWallContact({ ...createInitialState(), velocityY: 300 }, -1, 60); const jumped = applyWallJump(wall); expect(jumped.wallSide).toBe(0); expect(jumped.velocityX).toBe(WALL_JUMP_VELOCITY_X); expect(jumped.velocityY).toBe(WALL_JUMP_VELOCITY_Y); expect(jumped.dashReady).toBe(true); expect(jumped.wallJumpLock).toBeGreaterThan(0); });
  it('clears wall contact when leaving the wall', () => { const wall = applyWallContact(createInitialState(), 1, 300); expect(clearWallContact(wall).wallSide).toBe(0); });
  it('keeps dash as a single traversal resource with explicit reset sources', () => { const firstDash = applyDash(createInitialState(), 1); expect(firstDash.dashReady).toBe(false); expect(applyDash(firstDash, -1).velocityX).toBe(firstDash.velocityX); const crystalReset = applyCrystalPickup(firstDash); expect(crystalReset.dashReady).toBe(true); expect(crystalReset.velocityY).toBeLessThanOrEqual(CRYSTAL_LIFT_VELOCITY); const droneBounce = applyDroneKill(firstDash); expect(droneBounce.dashReady).toBe(false); expect(droneBounce.velocityY).toBeLessThanOrEqual(DRONE_BOUNCE_VELOCITY); });
  it('uses horizontal velocity for dash instead of teleporting', () => { const initial = { ...createInitialState(), velocityY: 300 }; const dashed = applyDash(initial, 1); expect(dashed.playerX).toBe(initial.playerX); expect(dashed.velocityX).toBe(DASH_SPEED); expect(tickState(dashed, 0.05).playerX).toBeGreaterThan(initial.playerX); });
  it('scales dash velocity with strength', () => { const initial = createInitialState(); const shortDash = applyDash(initial, 1, 0.35); const mediumDash = applyDash(initial, 1, 0.65); const fullDash = applyDash(initial, 1, 1); expect(shortDash.velocityX).toBeGreaterThan(MIN_DASH_SPEED); expect(shortDash.velocityX).toBeLessThan(mediumDash.velocityX); expect(mediumDash.velocityX).toBeLessThan(fullDash.velocityX); expect(fullDash.velocityX).toBe(MAX_DASH_SPEED); });
  it('makes the Dash route immediately strengthen Dash', () => { const upgraded = applyUpgrade(createInitialState(), 'dash'); const dashed = applyDash(upgraded, 1, 1); expect(upgraded.dashUpgradeLevel).toBe(1); expect(dashed.velocityX).toBeCloseTo(MAX_DASH_SPEED * DASH_UPGRADE_SPEED_MULTIPLIER); });
  it('tracks Flow route upgrades independently', () => { const upgraded = applyUpgrade(createInitialState(), 'flow'); expect(upgraded.flowUpgradeLevel).toBe(1); expect(upgraded.dashUpgradeLevel).toBe(0); });
  it('clamps horizontal movement inside portrait playfield', () => { expect(tickState({ ...createInitialState(), playerX: 307, velocityX: DASH_SPEED, dashTime: 1 }, 0.1).playerX).toBe(308); });
  it('preserves partial flow when a high-tier chain takes a hit', () => { expect(applyHit({ ...createInitialState(), flow: 5.9 }).flow).toBe(1); expect(applyHit({ ...createInitialState(), flow: 6 }).flow).toBe(FLOW_RUSH_HIT_FLOOR); expect(applyHit({ ...createInitialState(), flow: 9 }).flow).toBe(FLOW_OVERDRIVE_HIT_FLOOR); });
  it('still reduces hp and ends the run after three hits', () => { let state = { ...createInitialState(), flow: 10 }; state = applyHit(applyHit(applyHit(state))); expect(state.gameOver).toBe(true); expect(state.hp).toBe(0); });
});
