import { describe, expect, it } from 'vitest';
import { REGULAR_GAP_MAX, REGULAR_GAP_MIN, REST_GAP_MAX, REST_GAP_MIN, START_PLATFORM_Y, WorldGenerator, type WorldBand } from '../src/world/WorldGenerator';

function generate(seed: number, count: number) { const generator = new WorldGenerator(seed); return Array.from({ length: count }, () => generator.nextBand()); }
function encounters(bands: WorldBand[]) { const groups: WorldBand[][] = []; for (let index = 0; index < bands.length; index += 4) groups.push(bands.slice(index, index + 4)); return groups; }
function threatCount(group: WorldBand[]) { return group.flatMap((band) => band.spawns).filter((spawn) => spawn.type === 'drone' || spawn.type === 'hazard' || spawn.type === 'spike' || spawn.type === 'pulse-gate' || spawn.type === 'interceptor').length; }

describe('WorldGenerator', () => {
  it('replays the same encounter sequence for the same seed', () => { expect(generate(12345, 24)).toEqual(generate(12345, 24)); });
  it('builds encounters as four-band authored sequences with a final rest beat', () => { for (const group of encounters(generate(7, 40))) { expect(group).toHaveLength(4); expect(group.map((band) => band.encounterStep)).toEqual([0, 1, 2, 3]); expect(new Set(group.map((band) => band.encounter)).size).toBe(1); expect(group.map((band) => band.rest)).toEqual([false, false, false, true]); } });
  it('preserves regular and rest gap ranges', () => { const bands = generate(99, 80); let previousY = START_PLATFORM_Y; for (const band of bands) { const gap = previousY - band.y; expect(gap).toBeGreaterThanOrEqual(band.rest ? REST_GAP_MIN : REGULAR_GAP_MIN); expect(gap).toBeLessThanOrEqual(band.rest ? REST_GAP_MAX : REGULAR_GAP_MAX); previousY = band.y; } });
  it('always keeps at least one static safe landing platform per band', () => { for (const band of generate(123, 240)) expect(band.spawns.filter((spawn) => spawn.type === 'platform' && !spawn.motion).length).toBeGreaterThanOrEqual(1); });
  it('includes both skill and content route choices in a long deterministic run', () => { const types = new Set(generate(20260815, 800).map((band) => band.encounter)); expect(types.has('upgrade-choice')).toBe(true); expect(types.has('route-choice')).toBe(true); });
  it('authors skill choice as two distinct skills that rejoin safely', () => { const groups = encounters(generate(77, 240)).filter((group) => group[0].encounter === 'upgrade-choice'); expect(groups.length).toBeGreaterThan(0); for (const group of groups) { const upgrades = group[1].spawns.filter((spawn) => spawn.type === 'upgrade'); expect(upgrades).toHaveLength(2); const ids = upgrades.flatMap((spawn) => spawn.type === 'upgrade' && spawn.skillId ? [spawn.skillId] : []); expect(new Set(ids).size).toBe(2); expect(group[3].rest).toBe(true); } });
  it('authors route choice as two distinct content routes', () => { const groups = encounters(generate(1234, 400)).filter((group) => group[0].encounter === 'route-choice'); expect(groups.length).toBeGreaterThan(0); for (const group of groups) { const routes = group[1].spawns.filter((spawn) => spawn.type === 'route'); expect(routes).toHaveLength(2); const kinds = routes.flatMap((spawn) => spawn.type === 'route' ? [spawn.kind] : []); expect(new Set(kinds).size).toBe(2); } });
  it('queues the selected route as the next encounter', () => { const generator = new WorldGenerator(99); generator.queueRoute('elite'); const group = Array.from({ length: 4 }, () => generator.nextBand()); expect(group.every((band) => band.encounter === 'elite')).toBe(true); expect(group.some((band) => band.spawns.some((spawn) => spawn.type === 'drone' || spawn.type === 'hazard' || spawn.type === 'pulse-gate' || spawn.type === 'interceptor'))).toBe(true); });
  it('maps skill route into a skill choice encounter', () => { const generator = new WorldGenerator(99); generator.queueRoute('skill'); const group = Array.from({ length: 4 }, () => generator.nextBand()); expect(group.every((band) => band.encounter === 'upgrade-choice')).toBe(true); expect(group.some((band) => band.spawns.some((spawn) => spawn.type === 'upgrade'))).toBe(true); });
  it('keeps recovery encounters resource-positive', () => { for (const group of encounters(generate(42, 400)).filter((group) => group[0].encounter === 'recovery')) expect(group.some((band) => band.spawns.some((spawn) => spawn.type === 'crystal'))).toBe(true); });
  it('authors moving-window as an optional moving shortcut with a static fallback', () => { for (const group of encounters(generate(1618033, 800)).filter((group) => group[0].encounter === 'moving-window')) { expect(group[1].spawns.filter((spawn) => spawn.type === 'platform' && spawn.motion)).toHaveLength(1); expect(group[1].spawns.filter((spawn) => spawn.type === 'platform' && !spawn.motion)).toHaveLength(1); } });
  it('escalates core encounter threat density deeper into a deterministic run', () => { const groups = encounters(generate(20260815, 320)).filter((group) => !['upgrade-choice', 'route-choice', 'treasure', 'elite', 'rest-route', 'climax'].includes(group[0].encounter)); const early = groups.slice(0, 4); const late = groups.slice(-10); expect(late.reduce((sum, group) => sum + threatCount(group), 0) / late.length).toBeGreaterThan(early.reduce((sum, group) => sum + threatCount(group), 0) / early.length); });
  it('keeps pressure moving-window readable with a static landing fallback', () => { const groups = encounters(generate(1618033, 1200)); const lateMoving = groups.slice(20).filter((group) => group[0].encounter === 'moving-window'); expect(lateMoving.length).toBeGreaterThan(0); for (const group of lateMoving) expect(group[1].spawns.some((spawn) => spawn.type === 'platform' && !spawn.motion)).toBe(true); });
  it('inserts recurring climax packets only after pressure pacing is established', () => { const groups = encounters(generate(20260815, 1200)); const climaxIndexes = groups.flatMap((group, index) => group[0].encounter === 'climax' ? [index] : []); expect(climaxIndexes.length).toBeGreaterThanOrEqual(2); expect(climaxIndexes[0]).toBeGreaterThan(10); });
  it('authors climax as a readable mixed-mechanic peak with recovery exit', () => { const climaxes = encounters(generate(20260815, 1200)).filter((group) => group[0].encounter === 'climax'); expect(climaxes.length).toBeGreaterThan(0); for (const group of climaxes) { const spawns = group.flatMap((band) => band.spawns); expect(spawns.some((spawn) => spawn.type === 'drone')).toBe(true); expect(spawns.some((spawn) => spawn.type === 'pulse-gate')).toBe(true); expect(spawns.some((spawn) => spawn.type === 'interceptor')).toBe(true); expect(spawns.some((spawn) => spawn.type === 'wall')).toBe(true); expect(spawns.some((spawn) => spawn.type === 'platform' && Boolean(spawn.motion))).toBe(true); expect(group[3].rest).toBe(true); expect(group[3].spawns.some((spawn) => spawn.type === 'crystal')).toBe(true); } });
});
