import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import './style.css';

await RAPIER.init();
const host=document.querySelector<HTMLDivElement>('#game')!, movesEl=document.querySelector<HTMLElement>('#moves')!, directionEl=document.querySelector<HTMLElement>('#direction')!, gravityDot=document.querySelector<HTMLElement>('#gravity-dot')!;
const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x34228c,.035);
const camera=new THREE.PerspectiveCamera(38,1,.1,100); camera.position.set(0,1.5,18); camera.lookAt(0,.8,0);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.outputColorSpace=THREE.SRGBColorSpace; host.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xbad9ff,0x30105f,3.2)); const key=new THREE.DirectionalLight(0xffffff,5); key.position.set(-4,8,8); key.castShadow=true; scene.add(key); const rim=new THREE.PointLight(0x8f5cff,25,25); rim.position.set(5,2,5); scene.add(rim);
const world=new RAPIER.World({x:0,y:-18,z:0});
type Piece={mesh:THREE.Mesh;body:RAPIER.RigidBody;color:number;removing?:boolean}; const pieces:Piece[]=[]; const container=new THREE.Group(); scene.add(container);
const glassMat=new THREE.MeshPhysicalMaterial({color:0xa99cff,transparent:true,opacity:.16,roughness:.08,transmission:.25,side:THREE.DoubleSide});
function wall(x:number,y:number,z:number,hx:number,hy:number,hz:number){const b=world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,y,z));world.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setFriction(.45).setRestitution(.1),b)}
wall(0,-5,0,4.4,.18,2);wall(0,5,0,4.4,.18,2);wall(-4.55,0,0,.18,5,2);wall(4.55,0,0,.18,5,2);wall(0,0,-1.35,4.5,5,.12);wall(0,0,1.35,4.5,5,.12);
const floor=new THREE.Mesh(new THREE.BoxGeometry(9.3,.35,2.9),glassMat);floor.position.y=-5;container.add(floor);for(const x of [-4.55,4.55]){const m=new THREE.Mesh(new THREE.BoxGeometry(.28,10,2.9),glassMat);m.position.x=x;container.add(m)}const back=new THREE.Mesh(new THREE.BoxGeometry(9.2,10,.12),glassMat);back.position.z=-1.35;container.add(back);
const palette=[0xff3f43,0x21b8ff,0xffca28,0x67dc32,0xb84cff]; const geometries=[new THREE.BoxGeometry(1.35,1.35,1.35,4,4,4),new THREE.SphereGeometry(.73,24,16),new THREE.IcosahedronGeometry(.78,1)];
function spawn(){pieces.splice(0).forEach(p=>{scene.remove(p.mesh);world.removeRigidBody(p.body)});for(let i=0;i<30;i++){const kind=i%3,color=palette[Math.floor(Math.random()*palette.length)],mesh=new THREE.Mesh(geometries[kind],new THREE.MeshPhysicalMaterial({color,roughness:.22,clearcoat:1,clearcoatRoughness:.15}));mesh.castShadow=true;const x=-3.4+(i%6)*1.35+(Math.random()-.5)*.15,y=-3.9+Math.floor(i/6)*1.45,z=(Math.random()-.5)*.35;const body=world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,y,z));const col=kind===1?RAPIER.ColliderDesc.ball(.73):RAPIER.ColliderDesc.cuboid(.65,.65,.65);world.createCollider(col.setDensity(1).setFriction(.5).setRestitution(.12),body);scene.add(mesh);pieces.push({mesh,body,color})}}
spawn(); let shifts=0,tiltTarget=0,settleTimer:number|undefined,busy=false;
function updateHud(){movesEl.textContent='∞'} updateHud();
function shift(dx:number,dy:number){if(busy)return;busy=true;shifts++;world.gravity={x:dx*20,y:dy*20,z:0};tiltTarget=dx*-.09;directionEl.textContent=dx<0?'GRAVITY ←':dx>0?'GRAVITY →':dy>0?'GRAVITY ↑':'GRAVITY ↓';gravityDot.style.transform=`translateX(${dx*72}px)`;clearTimeout(settleTimer);settleTimer=window.setTimeout(resolveMatches,850)}
function groups(){const alive=pieces.filter(p=>!p.removing),seen=new Set<Piece>(),out:Piece[][]=[];for(const root of alive){if(seen.has(root))continue;const group:Piece[]=[],q=[root];seen.add(root);while(q.length){const a=q.pop()!;group.push(a);const ap=a.body.translation();for(const b of alive){if(seen.has(b)||b.color!==a.color)continue;const bp=b.body.translation(),dx=ap.x-bp.x,dy=ap.y-bp.y,dz=ap.z-bp.z;if(dx*dx+dy*dy+dz*dz<2.65){seen.add(b);q.push(b)}}}if(group.length>=3)out.push(group)}return out}
function resolveMatches(){const matched=groups();if(!matched.length){busy=false;return}for(const group of matched)for(const p of group){p.removing=true;p.body.setEnabled(false);const start=performance.now(),base=p.mesh.scale.clone();const pop=(now:number)=>{const t=Math.min((now-start)/260,1),s=t<.35?1+t*.5:1.18*(1-(t-.35)/.65);p.mesh.scale.copy(base).multiplyScalar(Math.max(0,s));p.mesh.rotation.z+=.08;if(t<1)requestAnimationFrame(pop);else{scene.remove(p.mesh);world.removeRigidBody(p.body);const idx=pieces.indexOf(p);if(idx>=0)pieces.splice(idx,1)}};requestAnimationFrame(pop)}window.setTimeout(()=>{if(pieces.length===0){spawn()}busy=false;settleTimer=window.setTimeout(resolveMatches,700)},420)}
let sx=0,sy=0;renderer.domElement.addEventListener('pointerdown',e=>{sx=e.clientX;sy=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointerup',e=>{const dx=e.clientX-sx,dy=e.clientY-sy;if(Math.max(Math.abs(dx),Math.abs(dy))<38)return;if(Math.abs(dx)>Math.abs(dy))shift(dx>0?1:-1,0);else shift(0,dy<0?1:-1)});
document.querySelector('#reset')!.addEventListener('click',()=>{busy=false;shifts=0;world.gravity={x:0,y:-18,z:0};tiltTarget=0;directionEl.textContent='GRAVITY ↓';gravityDot.style.transform='translateX(0)';spawn()});
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);resize();let last=performance.now();function loop(now:number){world.timestep=Math.min((now-last)/1000,.033);last=now;world.step();for(const p of pieces){if(p.removing)continue;const v=p.body.translation(),q=p.body.rotation();p.mesh.position.set(v.x,v.y,v.z);p.mesh.quaternion.set(q.x,q.y,q.z,q.w)}container.rotation.z+=(tiltTarget-container.rotation.z)*.08;renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
