import { applySelectedCharacter } from './characters';

export type UpgradeDomain='PLAYER'|'WEAPON'|'TOWER'|'SYSTEM';
export interface RunModifiers{playerDamage:number;fireRate:number;moveSpeed:number;maxHp:number;contactResist:number;killHeal:number;airDamage:number;weaponPierce:number;weaponKnock:number;ballistic:number;energy:number;towerDamage:number;towerRate:number;towerRange:number;towerHp:number;repairPower:number;autoRepair:number;buildDiscount:number;killCredits:number;coreShield:number;extraPads:number;laneTransfer:number;}
export const defaultModifiers=():RunModifiers=>applySelectedCharacter({playerDamage:1,fireRate:1,moveSpeed:1,maxHp:100,contactResist:0,killHeal:0,airDamage:1,weaponPierce:0,weaponKnock:1,ballistic:1,energy:1,towerDamage:1,towerRate:1,towerRange:1,towerHp:1,repairPower:1,autoRepair:0,buildDiscount:0,killCredits:0,coreShield:0,extraPads:0,laneTransfer:1});
export interface Upgrade{id:string;name:string;domain:UpgradeDomain;description:string;apply:(m:RunModifiers)=>void;}
const u=(id:string,name:string,domain:UpgradeDomain,description:string,apply:(m:RunModifiers)=>void):Upgrade=>({id,name,domain,description,apply});
export const UPGRADES:readonly Upgrade[]=[
u('p-dmg','KINETIC REFLEX','PLAYER','Player damage +18%',m=>m.playerDamage*=1.18),u('p-speed','GHOST LEGS','PLAYER','Move speed +15%',m=>m.moveSpeed*=1.15),u('p-hp','SUBDERMAL PLATE','PLAYER','Max HP +25',m=>m.maxHp+=25),u('p-resist','PAIN EDITOR','PLAYER','Contact damage -18%',m=>m.contactResist=Math.min(.65,m.contactResist+.18)),u('p-heal','VAMP LINK','PLAYER','Kills restore 3 HP',m=>m.killHeal+=3),u('p-air','AERIAL PREDATOR','PLAYER','Airborne damage +35%',m=>m.airDamage*=1.35),u('p-rate','SYNAPSE CLOCK','PLAYER','Fire cadence +12%',m=>m.fireRate*=1.12),u('p-knock','MUSCLE DRIVER','PLAYER','Weapon knockback +25%',m=>m.weaponKnock*=1.25),u('p-lane','VERTICAL INSTINCT','PLAYER','Lane transfer speed +30%',m=>m.laneTransfer*=1.3),
u('w-pierce','SMART AMMO','WEAPON','All rounds +1 pierce',m=>m.weaponPierce+=1),u('w-ballistic','TUNGSTEN LOGIC','WEAPON','Ballistic damage +22%',m=>m.ballistic*=1.22),u('w-energy','ION LENS','WEAPON','Energy damage +25%',m=>m.energy*=1.25),u('w-rate','TRIGGER DAEMON','WEAPON','Fire cadence +15%',m=>m.fireRate*=1.15),u('w-dmg','HOT LOAD','WEAPON','Player damage +20%',m=>m.playerDamage*=1.2),u('w-knock','BREACH COIL','WEAPON','Knockback +35%',m=>m.weaponKnock*=1.35),u('w-air','SKYLINE AMMO','WEAPON','Airborne damage +25%',m=>m.airDamage*=1.25),u('w-pierce2','PHASE JACKET','WEAPON','Rounds +2 pierce, fire rate -8%',m=>{m.weaponPierce+=2;m.fireRate*=.92}),u('w-hybrid','DUAL CORE ROUND','WEAPON','Ballistic +12%, Energy +12%',m=>{m.ballistic*=1.12;m.energy*=1.12}),
u('t-dmg','OVERCLOCK','TOWER','Tower damage +20%',m=>m.towerDamage*=1.2),u('t-rate','SERVO BURST','TOWER','Tower cadence +18%',m=>m.towerRate*=1.18),u('t-range','TARGET MESH','TOWER','Tower range +20%',m=>m.towerRange*=1.2),u('t-hp','HARDENED GRID','TOWER','Tower HP +30%',m=>m.towerHp*=1.3),u('t-repair','NANO PATCH','TOWER','Manual repair +50%',m=>m.repairPower*=1.5),u('t-auto','AUTO REPAIR','TOWER','Structures regenerate 3 HP/s',m=>m.autoRepair+=3),u('t-shock','CHAIN TESLA','TOWER','Energy tower damage +25%',m=>m.energy*=1.25),u('t-fast','DUAL BARREL','TOWER','Tower cadence +25%, damage -8%',m=>{m.towerRate*=1.25;m.towerDamage*=.92}),u('t-fort','FORTRESS BUS','TOWER','Tower HP +20%, repair +25%',m=>{m.towerHp*=1.2;m.repairPower*=1.25}),
u('s-cost','BLACK MARKET','SYSTEM','Build cost -15%',m=>m.buildDiscount=Math.min(.5,m.buildDiscount+.15)),u('s-credit','BOUNTY DAEMON','SYSTEM','Kills grant +8 credits',m=>m.killCredits+=8),u('s-core','CORE SHIELD','SYSTEM','CORE gains 20% damage shield',m=>m.coreShield=Math.min(.6,m.coreShield+.2)),u('s-pad','GRID EXPANSION','SYSTEM','Extra build node per lane',m=>m.extraPads+=1),u('s-auto','MAINTENANCE SWARM','SYSTEM','Auto repair +2 HP/s',m=>m.autoRepair+=2),u('s-lane','TRANSIT ROOT','SYSTEM','Lane transfer speed +35%',m=>m.laneTransfer*=1.35),u('s-econ','SALVAGE RIGHTS','SYSTEM','Kills +5 credits; build -5%',m=>{m.killCredits+=5;m.buildDiscount+=.05}),u('s-def','REDUNDANT CORE','SYSTEM','CORE shield +15%; tower HP +12%',m=>{m.coreShield+=.15;m.towerHp*=1.12}),u('s-cross','SHOCK ECONOMY','SYSTEM','Energy +15%; tower damage +10%',m=>{m.energy*=1.15;m.towerDamage*=1.1}),
];
export function upgradeChoices(owned:Set<string>,count=3){const pool=UPGRADES.filter(x=>!owned.has(x.id));const shuffled=[...pool].sort(()=>Math.random()-.5);return shuffled.slice(0,Math.min(count,shuffled.length));}
