import * as THREE from 'three';
import * as CANNON from 'cannon-es';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import './style.css';
import {DOMINO_PHYSICS,configureDominoWorld,createGround,createPivotedDomino,releaseFallenDominoes,startDomino,type PivotedDomino} from './dominoPhysics';

type Point=[number,number];
type Level={name:string;goal:string;path:Point[];count:number;accent:number;prop?:'ball'|'bell'|'cat'|'chicken'|'balloon'};
const levels:Level[]=[
{name:'第一推',goal:'推倒整條骨牌',path:[[-4.2,0],[4.2,0]],count:25,accent:0xf08a72},{name:'轉個彎',goal:'讓連鎖反應繞過轉角',path:[[-4,-1.8],[-.5,-1.8],[-.5,2.4]],count:23,accent:0x77bfa3},{name:'蛇蛇走',goal:'沿 S 彎完成連鎖',path:[[-4,-1.2],[-2.4,1.1],[-.7,1.1],[1,-1.1],[2.6,-1.1],[4,1]],count:34,accent:0x7aa7d9},{name:'滾球球',goal:'把球撞下終點',path:[[-4,0],[3.7,0]],count:23,accent:0xe8b75b,prop:'ball'},{name:'叫醒貓',goal:'最後一張骨牌要碰到貓',path:[[-4,-.8],[-2,.6],[0,-.5],[2,.5],[3.7,0]],count:30,accent:0xc999d4,prop:'cat'},{name:'雞飛狗跳',goal:'把連鎖送到逃跑的小雞',path:[[-4,-1.4],[-1.2,-1.4],[.5,-.2],[2.2,1.4],[3.8,1.4]],count:30,accent:0xf2cf66,prop:'chicken'},{name:'繞圈圈',goal:'完成半圓連鎖',path:Array.from({length:13},(_,i)=>{const a=Math.PI+i*Math.PI/12;return[Math.cos(a)*3.4,Math.sin(a)*3.4-1] as Point}),count:31,accent:0x69c4cc},{name:'叮一聲',goal:'讓最後的骨牌敲響鈴鐺',path:[[-4,-.7],[-2,0],[0,.7],[2,0],[3.8,.6]],count:30,accent:0xf09b65,prop:'bell'},{name:'螺旋',goal:'從外圈一路倒進中心',path:Array.from({length:18},(_,i)=>{const a=i*.38,r=3.9-i*.15;return[Math.cos(a)*r,Math.sin(a)*r] as Point}),count:40,accent:0x94bd65},{name:'飛高高',goal:'完成連鎖，把氣球送上天',path:[[-4,-.6],[-2,.5],[0,-.5],[2,.5],[3.8,0]],count:30,accent:0xe889a8,prop:'balloon'}];
function samplePath(path:Point[],count:number){const lengths:number[]=[];let total=0;for(let i=0;i<path.length-1;i++){const len=Math.hypot(path[i+1][0]-path[i][0],path[i+1][1]-path[i][1]);lengths.push(len);total+=len}const spacing=Math.max(DOMINO_PHYSICS.spacing,total/(count-1)),actual=Math.floor(total/spacing)+1;return Array.from({length:actual},(_,i)=>{let d=Math.min(i*spacing,total);for(let s=0;s<lengths.length;s++){if(d<=lengths[s]||s===lengths.length-1){const t=lengths[s]?Math.min(1,d/lengths[s]):0;return[path[s][0]+(path[s+1][0]-path[s][0])*t,path[s][1]+(path[s+1][1]-path[s][1])*t] as Point}d-=lengths[s]}return path.at(-1)!})}
function heading(points:Point[],i:number){const a=points[Math.max(0,i-1)],b=points[Math.min(points.length-1,i+1)];return Math.atan2(b[0]-a[0],b[1]-a[1])}
const app=document.querySelector<HTMLDivElement>('#app')!,scene=new THREE.Scene();scene.background=new THREE.Color(0xf7e8c9);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.set(0,9,11);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;app.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=8;controls.maxDistance=18;controls.maxPolarAngle=Math.PI*.46;scene.add(new THREE.HemisphereLight(0xfff5dc,0x8c765f,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(4,10,6);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.CylinderGeometry(6.2,6.4,.45,48),new THREE.MeshStandardMaterial({color:0xf1d7a7,roughness:.9}));floor.position.y=-.28;floor.receiveShadow=true;scene.add(floor);
const world=new CANNON.World(),materials=configureDominoWorld(world),ground=createGround(world,materials.groundMaterial,7,7);let dominoes:PivotedDomino[]=[],meshes:THREE.Mesh[]=[],current=0,armed=false,points:Point[]=[];
const hud=document.createElement('div');hud.className='hud';hud.innerHTML=`<div class="top"><div><div class="title"></div><div class="goal"></div></div></div><div class="bottom"><div class="levels"></div><button id="reset">↻</button><button class="primary" id="go">推！</button></div>`;document.body.appendChild(hud);const hint=document.createElement('div');hint.className='hint';hint.textContent='拖曳旋轉場景 · 按「推！」開始';document.body.appendChild(hint);const bar=hud.querySelector('.levels')!;levels.forEach((_,i)=>{const b=document.createElement('button');b.textContent=String(i+1);b.onclick=()=>load(i);bar.appendChild(b)});
function clear(){dominoes.forEach(d=>{if(!d.released)world.removeConstraint(d.hinge);world.removeBody(d.body)});meshes.forEach(m=>scene.remove(m));dominoes=[];meshes=[]}
function load(index:number){current=index;armed=false;clear();const level=levels[index];points=samplePath(level.path,level.count);(hud.querySelector('.title') as HTMLElement).textContent=`${index+1}. ${level.name}`;(hud.querySelector('.goal') as HTMLElement).textContent=level.goal;[...bar.children].forEach((x,i)=>x.classList.toggle('active',i===index));points.forEach((p,i)=>{const yaw=heading(points,i),mesh=new THREE.Mesh(new THREE.BoxGeometry(DOMINO_PHYSICS.width,DOMINO_PHYSICS.height,DOMINO_PHYSICS.thickness),new THREE.MeshStandardMaterial({color:i===0?0xff6b5e:level.accent,roughness:.55}));mesh.position.set(p[0],DOMINO_PHYSICS.height/2+.01,p[1]);mesh.rotation.y=yaw;mesh.castShadow=true;scene.add(mesh);meshes.push(mesh);dominoes.push(createPivotedDomino(world,ground,materials.dominoMaterial,p[0],p[1],yaw))})}
function push(){if(armed||dominoes.length<2)return;armed=true;dominoes.forEach(d=>d.body.wakeUp());startDomino(dominoes[0],heading(points,0))}
(hud.querySelector('#go') as HTMLButtonElement).onclick=push;(hud.querySelector('#reset') as HTMLButtonElement).onclick=()=>load(current);function resize(){const w=Math.min(innerWidth,700),h=innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}addEventListener('resize',resize);resize();load(0);let last=performance.now();function tick(now:number){const dt=Math.min((now-last)/1000,.033);last=now;world.step(1/180,dt,16);releaseFallenDominoes(world,dominoes);dominoes.forEach((d,i)=>{meshes[i].position.copy(d.body.position as unknown as THREE.Vector3);meshes[i].quaternion.copy(d.body.quaternion as unknown as THREE.Quaternion)});controls.update();renderer.render(scene,camera);requestAnimationFrame(tick)}requestAnimationFrame(tick);
