import * as THREE from 'three';
import * as CANNON from 'cannon-es';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import './style.css';

type Point=[number,number];
type Level={name:string;goal:string;path:Point[];count:number;accent:number;prop?:'ball'|'bell'|'cat'|'chicken'|'balloon'};
// Gameplay baseline: keep a visible gap while making the domino slender enough that
// gravity, rather than collision bounce, sustains the cascade after each tipping point.
const DOMINO={thickness:.14,height:1.42,width:.72,spacing:.46,mass:.30};
const levels:Level[]=[
{name:'第一推',goal:'推倒整條骨牌',path:[[-4.2,0],[4.2,0]],count:20,accent:0xf08a72},
{name:'轉個彎',goal:'讓連鎖反應繞過轉角',path:[[-4,-1.8],[-.5,-1.8],[-.5,2.4]],count:19,accent:0x77bfa3},
{name:'蛇蛇走',goal:'沿 S 彎完成連鎖',path:[[-4,-1.2],[-2.4,1.1],[-.7,1.1],[1,-1.1],[2.6,-1.1],[4,1]],count:27,accent:0x7aa7d9},
{name:'滾球球',goal:'把球撞下終點',path:[[-4,0],[3.7,0]],count:19,accent:0xe8b75b,prop:'ball'},
{name:'叫醒貓',goal:'最後一張骨牌要碰到貓',path:[[-4,-.8],[-2,.6],[0,-.5],[2,.5],[3.7,0]],count:24,accent:0xc999d4,prop:'cat'},
{name:'雞飛狗跳',goal:'把連鎖送到逃跑的小雞',path:[[-4,-1.4],[-1.2,-1.4],[.5,-.2],[2.2,1.4],[3.8,1.4]],count:24,accent:0xf2cf66,prop:'chicken'},
{name:'繞圈圈',goal:'完成半圓連鎖',path:Array.from({length:13},(_,i)=>{const a=Math.PI+i*Math.PI/12;return[Math.cos(a)*3.4,Math.sin(a)*3.4-1] as Point}),count:25,accent:0x69c4cc},
{name:'叮一聲',goal:'讓最後的骨牌敲響鈴鐺',path:[[-4,-.7],[-2,0],[0,.7],[2,0],[3.8,.6]],count:24,accent:0xf09b65,prop:'bell'},
{name:'螺旋',goal:'從外圈一路倒進中心',path:Array.from({length:18},(_,i)=>{const a=i*.38,r=3.9-i*.15;return[Math.cos(a)*r,Math.sin(a)*r] as Point}),count:32,accent:0x94bd65},
{name:'飛高高',goal:'完成連鎖，把氣球送上天',path:[[-4,-.6],[-2,.5],[0,-.5],[2,.5],[3.8,0]],count:24,accent:0xe889a8,prop:'balloon'}
];
function samplePath(path:Point[],count:number):Point[]{const lengths:number[]=[];let total=0;for(let i=0;i<path.length-1;i++){const dx=path[i+1][0]-path[i][0],dz=path[i+1][1]-path[i][1];const len=Math.hypot(dx,dz);lengths.push(len);total+=len}const spacing=Math.max(DOMINO.spacing,total/(count-1));const actualCount=Math.floor(total/spacing)+1;return Array.from({length:actualCount},(_,i)=>{let d=Math.min(i*spacing,total);for(let s=0;s<lengths.length;s++){if(d<=lengths[s]||s===lengths.length-1){const t=lengths[s]?Math.min(1,d/lengths[s]):0;return[path[s][0]+(path[s+1][0]-path[s][0])*t,path[s][1]+(path[s+1][1]-path[s][1])*t] as Point}d-=lengths[s]}return path.at(-1)!})}
function heading(points:Point[],i:number){const prev=points[Math.max(0,i-1)],next=points[Math.min(points.length-1,i+1)];return Math.atan2(next[0]-prev[0],next[1]-prev[1])}
const app=document.querySelector<HTMLDivElement>('#app')!;const scene=new THREE.Scene();scene.background=new THREE.Color(0xf7e8c9);const camera=new THREE.PerspectiveCamera(45,innerWidth/innerHeight,.1,100);camera.position.set(0,9,11);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;app.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enablePan=false;controls.minDistance=8;controls.maxDistance=18;controls.maxPolarAngle=Math.PI*.46;controls.target.set(0,0,0);scene.add(new THREE.HemisphereLight(0xfff5dc,0x8c765f,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.5);sun.position.set(4,10,6);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.CylinderGeometry(6.2,6.4,.45,48),new THREE.MeshStandardMaterial({color:0xf1d7a7,roughness:.9}));floor.position.y=-.28;floor.receiveShadow=true;scene.add(floor);
const world=new CANNON.World({gravity:new CANNON.Vec3(0,-10.5,0)});world.allowSleep=true;if(world.solver instanceof CANNON.GSSolver)world.solver.iterations=30;const groundMat=new CANNON.Material('ground'),dominoMat=new CANNON.Material('domino');world.addContactMaterial(new CANNON.ContactMaterial(groundMat,dominoMat,{friction:.55,restitution:0,contactEquationStiffness:1e8,contactEquationRelaxation:3}));world.addContactMaterial(new CANNON.ContactMaterial(dominoMat,dominoMat,{friction:.02,restitution:0}));const ground=new CANNON.Body({type:CANNON.Body.STATIC,shape:new CANNON.Box(new CANNON.Vec3(7,.2,7)),material:groundMat});ground.position.y=-.2;world.addBody(ground);
let bodies:CANNON.Body[]=[],meshes:THREE.Mesh[]=[],prop:THREE.Object3D|null=null,current=0,armed=false,currentPoints:Point[]=[];const hud=document.createElement('div');hud.className='hud';hud.innerHTML=`<div class="top"><div><div class="title"></div><div class="goal"></div></div></div><div class="bottom"><div class="levels"></div><button id="reset">↻</button><button class="primary" id="go">推！</button></div>`;document.body.appendChild(hud);const hint=document.createElement('div');hint.className='hint';hint.textContent='拖曳旋轉場景 · 按「推！」開始';document.body.appendChild(hint);const levelBar=hud.querySelector('.levels')!;levels.forEach((_,i)=>{const b=document.createElement('button');b.textContent=String(i+1);b.onclick=()=>load(i);levelBar.appendChild(b)});
function clear(){bodies.forEach(b=>world.removeBody(b));meshes.forEach(m=>scene.remove(m));bodies=[];meshes=[];if(prop){scene.remove(prop);prop=null}}
function load(index:number){current=index;armed=false;clear();const l=levels[index];currentPoints=samplePath(l.path,l.count);(hud.querySelector('.title') as HTMLElement).textContent=`${index+1}. ${l.name}`;(hud.querySelector('.goal') as HTMLElement).textContent=l.goal;[...levelBar.children].forEach((x,i)=>x.classList.toggle('active',i===index));currentPoints.forEach((p,i)=>{const angle=heading(currentPoints,i);const mesh=new THREE.Mesh(new THREE.BoxGeometry(DOMINO.width,DOMINO.height,DOMINO.thickness),new THREE.MeshStandardMaterial({color:i===0?0xff6b5e:l.accent,roughness:.55}));mesh.position.set(p[0],DOMINO.height/2+.01,p[1]);mesh.rotation.y=angle;mesh.castShadow=true;scene.add(mesh);const shape=new CANNON.Box(new CANNON.Vec3(DOMINO.width/2,DOMINO.height/2,DOMINO.thickness/2));const body=new CANNON.Body({mass:DOMINO.mass,shape,material:dominoMat,allowSleep:true,sleepSpeedLimit:.03,sleepTimeLimit:.5});body.position.set(p[0],DOMINO.height/2+.01,p[1]);body.quaternion.setFromEuler(0,angle,0);body.linearDamping=.005;body.angularDamping=.002;world.addBody(body);body.sleep();meshes.push(mesh);bodies.push(body)});addProp(l)}
function addProp(l:Level){if(!l.prop||!currentPoints.length)return;const end=currentPoints.at(-1)!,prev=currentPoints[Math.max(0,currentPoints.length-2)];const dx=end[0]-prev[0],dz=end[1]-prev[1],len=Math.hypot(dx,dz)||1;const group=new THREE.Group();group.position.set(end[0]+dx/len*.85,.55,end[1]+dz/len*.85);const mat=new THREE.MeshStandardMaterial({color:0xffffff});if(l.prop==='ball')group.add(new THREE.Mesh(new THREE.SphereGeometry(.48,24,16),new THREE.MeshStandardMaterial({color:0x6fa8dc})));else if(l.prop==='bell')group.add(new THREE.Mesh(new THREE.ConeGeometry(.5,.8,20),new THREE.MeshStandardMaterial({color:0xe9b949})));else if(l.prop==='balloon'){const b=new THREE.Mesh(new THREE.SphereGeometry(.45,24,16),new THREE.MeshStandardMaterial({color:0xf48fb1}));b.scale.y=1.2;group.add(b)}else{const body=new THREE.Mesh(new THREE.SphereGeometry(.48,20,14),mat);group.add(body);const e1=new THREE.Mesh(new THREE.ConeGeometry(.16,.35,3),mat);e1.position.set(-.25,.42,0);group.add(e1);const e2=e1.clone();e2.position.x=.25;group.add(e2)}prop=group;scene.add(group)}
function push(){if(armed||bodies.length<2)return;armed=true;bodies.forEach(b=>{b.allowSleep=false;b.wakeUp();b.velocity.setZero();b.angularVelocity.setZero()});const first=bodies[0],second=bodies[1];const dx=second.position.x-first.position.x,dz=second.position.z-first.position.z,len=Math.hypot(dx,dz)||1,dirX=dx/len,dirZ=dz/len;first.applyImpulse(new CANNON.Vec3(dirX*.42,0,dirZ*.42),new CANNON.Vec3(0,DOMINO.height*.46,0))}
(hud.querySelector('#go') as HTMLButtonElement).onclick=push;(hud.querySelector('#reset') as HTMLButtonElement).onclick=()=>load(current);function resize(){const w=Math.min(innerWidth,700),h=innerHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h)}addEventListener('resize',resize);resize();load(0);let last=performance.now();function tick(now:number){const dt=Math.min((now-last)/1000,.033);last=now;world.step(1/180,dt,16);bodies.forEach((b,i)=>{meshes[i].position.copy(b.position as unknown as THREE.Vector3);meshes[i].quaternion.copy(b.quaternion as unknown as THREE.Quaternion)});controls.update();renderer.render(scene,camera);requestAnimationFrame(tick)}requestAnimationFrame(tick);
