import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import { createColorBag } from '../board/BoardGenerator';
import type { Piece } from '../board/model';
import { MatchSystem } from '../systems/MatchSystem';
import { hasImpossibleColorRemainder, selectSolvableMatch } from '../systems/SolvabilitySystem';
import { SwipeController, type ShiftDirection } from '../input/SwipeController';
import { HudController } from '../ui/HudController';

const STARTING_MOVES=20;
export class StackShiftGame {
  private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(38,1,.1,100);private renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});private world=new RAPIER.World({x:0,y:-18,z:0});private pieces:Piece[]=[];private container=new THREE.Group();private match=new MatchSystem();private hud=new HudController();private geometries=[new THREE.BoxGeometry(1.35,1.35,1.35,4,4,4),new THREE.SphereGeometry(.73,24,16),new THREE.IcosahedronGeometry(.78,1)];private nextId=1;private tiltTarget=0;private inputLocked=false;private resolving=false;private last=performance.now();private moves=STARTING_MOVES;private gameOver=false;private pendingLoss=false;
  constructor(private host:HTMLDivElement){this.scene.fog=new THREE.FogExp2(0x34228c,.035);this.camera.position.set(0,1.5,18);this.camera.lookAt(0,.8,0);this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(this.renderer.domElement);this.scene.add(this.container);this.setupLights();this.setupWalls();this.spawn();this.hud.reset(this.moves);new SwipeController(this.renderer.domElement,d=>this.shift(d));document.querySelector('#reset')!.addEventListener('click',()=>this.reset());document.querySelector('#restart')!.addEventListener('click',()=>this.reset());new ResizeObserver(()=>this.resize()).observe(host);this.resize();requestAnimationFrame(n=>this.loop(n))}
  private setupLights(){this.scene.add(new THREE.HemisphereLight(0xbad9ff,0x30105f,3.2));const key=new THREE.DirectionalLight(0xffffff,5);key.position.set(-4,8,8);key.castShadow=true;this.scene.add(key);const rim=new THREE.PointLight(0x8f5cff,25,25);rim.position.set(5,2,5);this.scene.add(rim)}
  private setupWalls(){const wall=(x:number,y:number,z:number,hx:number,hy:number,hz:number)=>{const b=this.world.createRigidBody(RAPIER.RigidBodyDesc.fixed().setTranslation(x,y,z));this.world.createCollider(RAPIER.ColliderDesc.cuboid(hx,hy,hz).setFriction(.45).setRestitution(.1),b)};wall(0,-5,0,4.4,.18,2);wall(0,5,0,4.4,.18,2);wall(-4.55,0,0,.18,5,2);wall(4.55,0,0,.18,5,2);wall(0,0,-1.35,4.5,5,.12);wall(0,0,1.35,4.5,5,.12);const glass=new THREE.MeshPhysicalMaterial({color:0xa99cff,transparent:true,opacity:.16,roughness:.08,transmission:.25,side:THREE.DoubleSide}),floor=new THREE.Mesh(new THREE.BoxGeometry(9.3,.35,2.9),glass);floor.position.y=-5;this.container.add(floor);for(const x of [-4.55,4.55]){const m=new THREE.Mesh(new THREE.BoxGeometry(.28,10,2.9),glass);m.position.x=x;this.container.add(m)}const back=new THREE.Mesh(new THREE.BoxGeometry(9.2,10,.12),glass);back.position.z=-1.35;this.container.add(back)}
  private spawn(){this.pieces.splice(0).forEach(p=>{this.scene.remove(p.mesh);this.world.removeRigidBody(p.body)});const bag=createColorBag();for(let i=0;i<30;i++){const kind=i%3,color=bag[i],mesh=new THREE.Mesh(this.geometries[kind],new THREE.MeshPhysicalMaterial({color,roughness:.22,clearcoat:1,clearcoatRoughness:.15}));mesh.castShadow=true;const x=-3.4+(i%6)*1.35+(Math.random()-.5)*.15,y=-3.9+Math.floor(i/6)*1.45,z=(Math.random()-.5)*.35,body=this.world.createRigidBody(RAPIER.RigidBodyDesc.dynamic().setTranslation(x,y,z)),col=kind===1?RAPIER.ColliderDesc.ball(.73):RAPIER.ColliderDesc.cuboid(.65,.65,.65);this.world.createCollider(col.setDensity(1).setFriction(.5).setRestitution(.12),body);this.scene.add(mesh);this.pieces.push({id:this.nextId++,mesh,body,color})}}
  private shift(d:ShiftDirection){if(this.inputLocked||this.resolving||this.gameOver||this.moves<=0)return;this.inputLocked=true;this.moves--;this.hud.setMoves(this.moves);this.pendingLoss=this.moves===0;this.world.gravity={x:d.dx*20,y:d.dy*20,z:0};this.tiltTarget=d.dx*-.09;this.hud.setGravity(d);window.setTimeout(()=>{this.inputLocked=false;if(this.pendingLoss&&!this.resolving)window.setTimeout(()=>this.finishLossIfNeeded(),700)},260)}
  private pop(group:Piece[]){const selected=selectSolvableMatch(group);if(selected.length<3)return;this.resolving=true;this.pendingLoss=false;for(const p of selected){p.removing=true;p.body.setEnabled(false);const start=performance.now(),base=p.mesh.scale.clone(),animate=(now:number)=>{const t=Math.min((now-start)/260,1),s=t<.35?1+t*.5:1.18*(1-(t-.35)/.65);p.mesh.scale.copy(base).multiplyScalar(Math.max(0,s));p.mesh.rotation.z+=.08;if(t<1)requestAnimationFrame(animate);else{this.scene.remove(p.mesh);this.world.removeRigidBody(p.body);const i=this.pieces.indexOf(p);if(i>=0)this.pieces.splice(i,1)}};requestAnimationFrame(animate)}window.setTimeout(()=>{this.resolving=false;this.match.clear();if(!this.pieces.length){this.finish(true);return}if(hasImpossibleColorRemainder(this.pieces))console.warn('Stack Shift solvability invariant violated',this.pieces.map(p=>({id:p.id,color:p.color})));if(this.moves===0)window.setTimeout(()=>this.finishLossIfNeeded(),700)},430)}
  private finishLossIfNeeded(){if(this.gameOver||this.resolving||this.pieces.some(p=>p.removing))return;const group=this.match.scan(this.pieces,performance.now());if(group){this.pop(group);return}this.finish(false)}
  private finish(won:boolean){if(this.gameOver)return;this.gameOver=true;this.inputLocked=true;this.pendingLoss=false;this.hud.showResult(won)}
  private reset(){this.inputLocked=this.resolving=this.gameOver=this.pendingLoss=false;this.moves=STARTING_MOVES;this.match.clear();this.world.gravity={x:0,y:-18,z:0};this.tiltTarget=0;this.hud.reset(this.moves);this.spawn()}
  private resize(){const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
  private loop(now:number){this.world.timestep=Math.min((now-this.last)/1000,.033);this.last=now;this.world.step();for(const p of this.pieces){if(p.removing)continue;const v=p.body.translation(),q=p.body.rotation();p.mesh.position.set(v.x,v.y,v.z);p.mesh.quaternion.set(q.x,q.y,q.z,q.w)}if(!this.resolving&&!this.gameOver){const group=this.match.scan(this.pieces,now);if(group)this.pop(group)}this.container.rotation.z+=(this.tiltTarget-this.container.rotation.z)*.08;this.renderer.render(this.scene,this.camera);requestAnimationFrame(n=>this.loop(n))}
}
